<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Prihlsi sa</name>
   <tag></tag>
   <elementGuidId>39bd6551-3b90-4aa0-80e4-acbcd8df3aa0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.govuk-button.sign-in-button.green</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8487649d-2dbe-4881-80ba-aaf390a0d6f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button sign-in-button green</value>
      <webElementGuid>04742866-a2e1-48c6-a16b-e804fa3ab604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Login?returnurl=%2F</value>
      <webElementGuid>0fd2a913-9412-4e59-81d1-cb7f05b7979b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prihlásiť sa</value>
      <webElementGuid>6b1373dc-377b-4f1f-90b2-a5d1b583e99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;main-menu&quot;]/div[@class=&quot;menu-wrapper&quot;]/a[@class=&quot;govuk-button sign-in-button green&quot;]</value>
      <webElementGuid>f6692263-a7c5-4bfd-a7b5-6e02c6a8efeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>4fb4dfae-4be5-437b-bc86-6c17e879c82d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/a</value>
      <webElementGuid>02026631-14ce-4116-8d1c-8c64054a1743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Prihlásiť sa')]</value>
      <webElementGuid>0df5dccf-eaec-4a23-a8ca-bdd057a1dc21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elektronické služby portálu regionálneho a vysokého školstva'])[1]/following::a[1]</value>
      <webElementGuid>ee3ca256-861d-4f8c-b8db-adccda073ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Testovacie prostredie'])[1]/following::a[3]</value>
      <webElementGuid>6aacfc88-f716-4306-aca6-060147cc2752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Registrovať sa'])[1]/preceding::a[1]</value>
      <webElementGuid>8d81e6cf-9d61-462d-b0c1-0317890364f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prihlásiť sa']/parent::*</value>
      <webElementGuid>17dec879-eaf2-4c2a-a548-6508f813c374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Login?returnurl=%2F')]</value>
      <webElementGuid>63b2d797-1cae-47a8-968f-461a46fc2948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>78779908-09a5-45a0-8ce0-9049830cde54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Login?returnurl=%2F' and (text() = 'Prihlásiť sa' or . = 'Prihlásiť sa')]</value>
      <webElementGuid>e34cfcd5-6edc-4b41-a8a2-e6e5248304b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
