<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Podpsa iados o piku kvalifikovanm elektronickm podpisom iadatea</name>
   <tag></tag>
   <elementGuidId>363a13a1-22da-4aff-8e7f-8f50626c8ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podpisat-a-odoslat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='podpisat-a-odoslat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>091b462c-5506-485d-85ef-4fd51dea4d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>0778c68b-278e-461d-80e2-2d43570d3385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>ee6c8b23-dcd1-4c26-84f3-f67e938d9466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>980e6995-d450-4bf1-9e54-3fdf02eb5044</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa</value>
      <webElementGuid>24cbce10-4d56-4aa3-8b43-3ae0e56d03d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podpisat-a-odoslat-btn&quot;)</value>
      <webElementGuid>91dea526-f8de-46b8-875f-72f72788c27f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='podpisat-a-odoslat-btn']</value>
      <webElementGuid>dd72fe58-56d2-45aa-953d-70d22af08f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odoslanie-podpisanie-buttons']/div/button</value>
      <webElementGuid>613122ec-dc4a-4f26-909d-a4bc1d008a55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na domovskú stránku'])[2]/following::button[1]</value>
      <webElementGuid>e3485e7e-6c01-4f3b-994c-8c4de70b4da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fond na podporu vzdelávania'])[2]/following::button[1]</value>
      <webElementGuid>92abbaf5-ee6e-42fe-ab10-d0d3d1176bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/preceding::button[1]</value>
      <webElementGuid>2790cb00-9e79-4c38-92af-2b1d5c1a2d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::button[2]</value>
      <webElementGuid>7dd48c73-1667-4e02-aeea-24869f8f9160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa']/parent::*</value>
      <webElementGuid>c8ca7ae6-e7b8-415b-9ec9-08223e93d6ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>7494d5b0-b8d7-4344-9c5f-cd0d2a1e7abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'podpisat-a-odoslat-btn' and @name = 'podpisat-a-odoslat-btn' and (text() = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa' or . = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa')]</value>
      <webElementGuid>ea9abb82-2044-4bde-b698-f8023b39d60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
