<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uloi_file-upload-field</name>
   <tag></tag>
   <elementGuidId>ff4ad386-5410-44d3-8c55-522d482da014</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;file-upload-field&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file-upload-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>60f14830-b745-4b79-85d1-1d602515e54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file-upload-field</value>
      <webElementGuid>bd119ce1-ac0b-4f48-a63c-68e075033624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>eb487cad-e1e8-4299-87e8-26533a966f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/x-7z-compressed, application/vnd.etsi.asic-e+zip, application/vnd.etsi.asic-s+zip, image/bmp, text/csv, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/x-eform-xml, image/gif, application/gzip, text/html, text/html, image/jpeg, image/jpeg, application/vnd.oasis.opendocument.spreadsheet, application/vnd.oasis.opendocument.text, application/pdf, image/png, application/vnd.rar, application/rtf, image/svg+xml, application/x-tar, image/tiff, image/tiff, text/plain, application/xhtml+xml, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/xml, application/x-xades_zep, application/zepx, application/x-xades_zep_data_signatures, application/x-zipzepf, application/zep, application/zip</value>
      <webElementGuid>78df9275-a60a-4a4d-84cf-6731847d2a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-!-margin-top-4 file-upload-field</value>
      <webElementGuid>8b63d87f-b877-46f2-9371-a030fe3ba949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-8&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;vyber-suboru&quot;]/div[@class=&quot;govuk-form-group&quot;]/div[1]/div[@id=&quot;nahrat-prilohu&quot;]/input[@class=&quot;govuk-button govuk-!-margin-top-4 file-upload-field&quot;]</value>
      <webElementGuid>966f8e92-7778-4e11-bf37-5b994ffad937</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='file-upload-field']</value>
      <webElementGuid>99f85f6e-a27f-4707-8fa3-e0ff42dcf592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nahrat-prilohu']/input</value>
      <webElementGuid>243fcfa6-7c62-4fbd-8f9b-f1ec86938c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/fieldset/div/div[2]/div/div/div/input</value>
      <webElementGuid>04e0b813-6035-43ac-a321-f514e7d4e5cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'file-upload-field' and @type = 'file']</value>
      <webElementGuid>4ab8daf7-40ee-4783-9bff-59d4236975c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
