<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_estne vyhlasujem, e vetky daje uveden v iadosti  s pravdiv a som si plne vedom prvnych nsledkov v prpade uvedenia nepravdivch dajov</name>
   <tag></tag>
   <elementGuidId>1d5d2f1c-adb4-46a7-9a90-d8473217df30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_CHB_PravdiveUdaje > div.govuk-checkboxes > div.govuk-checkboxes__item > label.govuk-label.govuk-checkboxes__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_CHB_PravdiveUdaje']/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>37f362e2-6fd2-4ca4-a639-537b5c9e2e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-label govuk-checkboxes__label</value>
      <webElementGuid>c010b39f-fe30-4ed7-8ca5-2f9bb2a77f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_PravdiveUdaje-control</value>
      <webElementGuid>9f471541-c6ff-4a09-9f93-832f1d6fc137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Čestne vyhlasujem, že všetky údaje uvedené v žiadosti  sú pravdivé a som si plne vedomá/ý právnych následkov v prípade uvedenia nepravdivých údajov. </value>
      <webElementGuid>e9b6abb0-8676-43da-acd5-804ac206d133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_CHB_PravdiveUdaje&quot;)/div[@class=&quot;govuk-checkboxes&quot;]/div[@class=&quot;govuk-checkboxes__item&quot;]/label[@class=&quot;govuk-label govuk-checkboxes__label&quot;]</value>
      <webElementGuid>996f12b7-ce38-458b-9e2b-e934637b5f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_CHB_PravdiveUdaje']/div/div/label</value>
      <webElementGuid>166a07da-f17b-4f8e-8eec-fdcdb65ab3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='form.573.Prehlad-24-potvrdenie-print-save_5a11da50-9aec-4f8b-a1a0-d42325a914a4.pdf'])[6]/following::label[1]</value>
      <webElementGuid>223c9554-1aa2-4e36-99a5-f393032c7c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov súboru'])[3]/following::label[1]</value>
      <webElementGuid>42dc12f5-337a-4b07-8697-e41ab6801b86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.fnpv.sk'])[1]/preceding::label[1]</value>
      <webElementGuid>0360830e-1e30-4fe2-a1ce-e149fe283f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísanie žiadosti'])[1]/preceding::label[4]</value>
      <webElementGuid>00d2487a-1173-41b0-9cd7-ba3c4a706174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/label</value>
      <webElementGuid>b72e3ea2-a7a4-48d0-b08f-fbd2e0ebacd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Čestne vyhlasujem, že všetky údaje uvedené v žiadosti  sú pravdivé a som si plne vedomá/ý právnych následkov v prípade uvedenia nepravdivých údajov. ' or . = 'Čestne vyhlasujem, že všetky údaje uvedené v žiadosti  sú pravdivé a som si plne vedomá/ý právnych následkov v prípade uvedenia nepravdivých údajov. ')]</value>
      <webElementGuid>319d2751-0431-4e23-8d89-7af68e88eee6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
