<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Beriem na vedomie, e v slade s  17 ods. 8 zkona o FnPV fond zverejuje na svojom webovom sdle zoznam schvlench piiek, ktor obsahuje meno a priezvisko iadatea, ktormu bolo poskytnutie piky schvlen, dln sumu, lehotu s</name>
   <tag></tag>
   <elementGuidId>bbdbc209-45e6-475f-a216-6ecf5175fcf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_CHB_OsobneUdaje > div.govuk-checkboxes > div.govuk-checkboxes__item > label.govuk-label.govuk-checkboxes__label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_CHB_OsobneUdaje']/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>b6428d3b-def0-472e-aa42-cdcb7a273a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-label govuk-checkboxes__label</value>
      <webElementGuid>851caaa3-6a7c-4ed6-8b61-07ba2d171a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_OsobneUdaje-control</value>
      <webElementGuid>094c7da4-31d4-42ea-99a9-306d776a3f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Beriem na vedomie, že v súlade s § 17 ods. 8 zákona o FnPV fond zverejňuje na svojom webovom sídle zoznam schválených pôžičiek, ktorý obsahuje meno a priezvisko žiadateľa, ktorému bolo poskytnutie pôžičky schválené, dlžnú sumu, lehotu splatnosti a dátum poukázania pôžičky na účet dlžníka a mená a priezviská osôb, ktorým fond pôžičku neposkytol.</value>
      <webElementGuid>33ca178b-35bc-4407-98a9-3d171d0eace8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_CHB_OsobneUdaje&quot;)/div[@class=&quot;govuk-checkboxes&quot;]/div[@class=&quot;govuk-checkboxes__item&quot;]/label[@class=&quot;govuk-label govuk-checkboxes__label&quot;]</value>
      <webElementGuid>b7d574da-57ec-4df3-9d54-154037f37aae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_CHB_OsobneUdaje']/div/div/label</value>
      <webElementGuid>76721c09-910b-4117-a189-14fe1333647f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='www.fnpv.sk'])[1]/following::label[1]</value>
      <webElementGuid>b4a8b5b6-da76-44b7-88ec-82fde54a9af8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='form.573.Prehlad-24-potvrdenie-print-save_5a11da50-9aec-4f8b-a1a0-d42325a914a4.pdf'])[6]/following::label[3]</value>
      <webElementGuid>bdbd7a76-47b1-4319-9667-825c8d58a002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísanie žiadosti'])[1]/preceding::label[2]</value>
      <webElementGuid>f311a433-524c-4458-a3e0-ef4cb5654519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[1]/preceding::label[2]</value>
      <webElementGuid>994d811d-c94c-4c57-9951-cba69ad0bd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Beriem na vedomie, že v súlade s § 17 ods. 8 zákona o FnPV fond zverejňuje na svojom webovom sídle zoznam schválených pôžičiek, ktorý obsahuje meno a priezvisko žiadateľa, ktorému bolo poskytnutie pôžičky schválené, dlžnú sumu, lehotu splatnosti a dátum poukázania pôžičky na účet dlžníka a mená a priezviská osôb, ktorým fond pôžičku neposkytol.']/parent::*</value>
      <webElementGuid>f083c7d4-3c87-4f21-af13-22c603a02382</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[2]/div/div/label</value>
      <webElementGuid>fa8b0461-27ff-46ef-acc7-65ed2424d438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Beriem na vedomie, že v súlade s § 17 ods. 8 zákona o FnPV fond zverejňuje na svojom webovom sídle zoznam schválených pôžičiek, ktorý obsahuje meno a priezvisko žiadateľa, ktorému bolo poskytnutie pôžičky schválené, dlžnú sumu, lehotu splatnosti a dátum poukázania pôžičky na účet dlžníka a mená a priezviská osôb, ktorým fond pôžičku neposkytol.' or . = 'Beriem na vedomie, že v súlade s § 17 ods. 8 zákona o FnPV fond zverejňuje na svojom webovom sídle zoznam schválených pôžičiek, ktorý obsahuje meno a priezvisko žiadateľa, ktorému bolo poskytnutie pôžičky schválené, dlžnú sumu, lehotu splatnosti a dátum poukázania pôžičky na účet dlžníka a mená a priezviská osôb, ktorým fond pôžičku neposkytol.')]</value>
      <webElementGuid>b36dd760-c6f8-43b5-93d4-011f27fb5744</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
