<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>SuitePozicky</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>cd6fc4db-5941-4e0c-89cb-a3d330488b6b</testSuiteGuid>
   <testCaseLink>
      <guid>d919c716-f536-4213-a8b7-602fd8200113</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pozicky B/Pozicka_399090</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>158d4b34-ebb0-4c51-8f4d-6a474c8907db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e791fde0-90d6-44aa-a5a3-a33a126fb391</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pozicky B/PozickaB_399076</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e1453215-c3cb-4dd2-b29b-7e0a832925fc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9bf82fb-045f-4032-81c6-cc54201d05e8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Pozicky B/PozickaB_399079</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d7f86eb-f7e9-46e8-bc15-68ef93d18a33</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
