<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Vyhada</name>
   <tag></tag>
   <elementGuidId>079fdc65-5f3f-4157-8312-dc0fca3ef4c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vyhladat-odoslane-podania-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='vyhladat-odoslane-podania-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>622bb3b7-3689-4a20-b175-bf0a85dfd2e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>vyhladat-odoslane-podania-btn</value>
      <webElementGuid>78a5b6fa-55f2-4030-bb6a-754aa7f1bbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green</value>
      <webElementGuid>efbe627c-729a-4cc1-a636-cf590c760ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vyhľadať</value>
      <webElementGuid>0edd84e9-1dcc-4de3-8d60-1384500b454f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vyhladat-odoslane-podania-btn&quot;)</value>
      <webElementGuid>32fddc93-85a1-40a1-811b-52750218a807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='vyhladat-odoslane-podania-btn']</value>
      <webElementGuid>de171942-fb10-4f16-8c1b-02b9244d04ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zoznam-odoslanych-podani']/div/div[2]/div[2]/div[6]/button</value>
      <webElementGuid>e9194356-31ad-48b3-8f17-6444320268a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear date'])[2]/following::button[1]</value>
      <webElementGuid>e8d7a3dd-f9c2-4e07-852e-ecce20fac35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='false'])[2]/following::button[1]</value>
      <webElementGuid>a6360c0d-c31a-47e4-89dd-0151d1226fe5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zoznam vyhľadaných podaní'])[1]/preceding::button[1]</value>
      <webElementGuid>bf3911ad-68b0-45c2-b378-d950b5112a43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ podania'])[2]/preceding::button[1]</value>
      <webElementGuid>10d7fb19-7cee-44ad-8d04-9a4412ea87ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vyhľadať']/parent::*</value>
      <webElementGuid>2542ad46-b93b-46b6-ac88-e3ee47682c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f47d6f19-c5e0-45d8-ba8d-78fd78200ef0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'vyhladat-odoslane-podania-btn' and (text() = 'Vyhľadať' or . = 'Vyhľadať')]</value>
      <webElementGuid>a62214a0-35fb-4cfb-81af-c297b8a09458</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
