<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Identifiktor_identifikator</name>
   <tag></tag>
   <elementGuidId>01f432d6-d568-43ad-97bc-9660845afd27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifikator</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identifikator']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c4fb011-58a4-49ec-80e1-c498cb868a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifikator</value>
      <webElementGuid>fa05ef35-4b7c-49ae-b58d-19949f5d5026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-input--width-20</value>
      <webElementGuid>88c3eeb6-81dc-4252-b135-4ce91d915335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed1f1462-92da-40c7-8305-9879de69293d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifikator&quot;)</value>
      <webElementGuid>400ec4a7-00e2-4d16-a7ea-357139a69f9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identifikator']</value>
      <webElementGuid>6b0789e6-0406-4999-8a9a-095398b61910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zoznam-odoslanych-podani']/div/div[2]/div[2]/div/div/input</value>
      <webElementGuid>bb438c67-1d6d-427a-a7af-7b612aba47bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a493f8c3-816c-4f2a-952f-d3c247972b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'identifikator' and @type = 'text']</value>
      <webElementGuid>6fe1dc2c-0f0d-4bd5-ad25-31cb7beb4b7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
