<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte svoj identifiktor_DomainName</name>
   <tag></tag>
   <elementGuidId>05457bd2-d4f2-40e9-9bd2-d9fb54168258</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DomainName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DomainName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc169d86-ccb8-45d0-bfac-b502bb3cfc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-input--width-20</value>
      <webElementGuid>6520637e-1e1d-458e-9a17-9d1c16f716c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>DomainNameHint</value>
      <webElementGuid>b64aa33d-6d81-4b7b-a208-f5964fcd9551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f259bc0-d6a0-4c27-8cb3-817b1ef40967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>771f078c-631c-4bb2-bc84-1b4beafc9b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c9579bf5-f0d1-44d6-b169-9d4a0764e2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The DomainName field is required.</value>
      <webElementGuid>2cdb0977-cfce-4b08-b365-e6ee28e2b329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DomainName</value>
      <webElementGuid>6dbc50ba-ed07-4169-bb2b-e54c398860e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DomainName</value>
      <webElementGuid>2921e2df-4ba5-46fd-8f28-571e9482bfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DomainName&quot;)</value>
      <webElementGuid>1e52957c-a8cb-4a95-907d-c9040f3ede25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b196ae6a-f08a-436a-a02f-cfd93c6a4811</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DomainName']</value>
      <webElementGuid>7b1c680f-8b72-439a-83b5-a87b439c7fbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>e76f35e2-96a4-49c3-a59f-e2d315c62add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'DomainName' and @name = 'DomainName']</value>
      <webElementGuid>d9c47f9c-6716-424b-950a-ec210c18a1bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
