<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2168</name>
   <tag></tag>
   <elementGuidId>3e361338-b337-4310-8573-c84b046c9f80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifikator-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='identifikator-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bfa81843-80f3-4384-adc5-87defaf6923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifikator-info</value>
      <webElementGuid>e4f80eb9-d89c-4a81-8eb5-c3cd827c0bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>2d67a6e7-c19e-4c7c-89b6-c07eeed5a7af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2168</value>
      <webElementGuid>a4151682-e497-47af-9380-6aa4caf3d38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifikator-info&quot;)</value>
      <webElementGuid>af2a21cd-0241-4fc8-aa3f-99fd18ff1e1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='identifikator-info']</value>
      <webElementGuid>9da174ad-b110-47cf-b68a-a10238423120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-sekcia']/div/span</value>
      <webElementGuid>62a032ea-ce2d-431f-9888-7892c52d12ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor'])[1]/following::span[1]</value>
      <webElementGuid>3c81e7e8-5972-46c9-87e2-85abe400b7f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informácie o podaní'])[1]/following::span[1]</value>
      <webElementGuid>034e2f70-358b-440d-99c4-d7ccd6faf67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[1]/preceding::span[1]</value>
      <webElementGuid>ae0fdaea-53b8-4f5e-9143-9f0f66795b4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Robert Chamraz'])[1]/preceding::span[1]</value>
      <webElementGuid>cede2416-08c5-41b5-857c-abb6c1b17102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2168']/parent::*</value>
      <webElementGuid>06db72e5-5ddb-4636-b248-3f47f318cfa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>68e36067-2ef1-4511-beb4-93067cc74a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'identifikator-info' and (text() = 'ESRVS-2024-2168' or . = 'ESRVS-2024-2168')]</value>
      <webElementGuid>c2c1b71b-e419-46b8-a294-2741e7855214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
