<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Robert Chamraz</name>
   <tag></tag>
   <elementGuidId>cb077f0b-bba1-4945-a529-61ec4ce497a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meno-a-priezvisko-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='meno-a-priezvisko-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>49afe04f-5693-4d2a-a767-8d15d0c4def2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meno-a-priezvisko-info</value>
      <webElementGuid>94e9833c-ea33-4ce3-b7e0-2c38752e8016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Robert Chamraz</value>
      <webElementGuid>e2317296-f5f1-4d0c-b0c7-4858391f552e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meno-a-priezvisko-info&quot;)</value>
      <webElementGuid>93f3ad3d-d371-46fc-8d14-f2edcf842391</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='meno-a-priezvisko-info']</value>
      <webElementGuid>b82e2f34-3941-4577-b0d9-749db5e3dd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-sekcia']/div[2]/span</value>
      <webElementGuid>f09945f4-9c17-4552-a68d-a2cf83db3262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[1]/following::span[1]</value>
      <webElementGuid>8707ab71-a754-4e14-88d8-0bdf4260ecb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESRVS-2024-2148'])[1]/following::span[1]</value>
      <webElementGuid>57581146-e1d9-4607-b464-490862916925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ podania'])[1]/preceding::span[1]</value>
      <webElementGuid>ef0ba8bc-97d8-4ec3-b7d2-0c455c115dda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podávanie žiadosti o pôžičku pre študentov z Fondu na podporu vzdelávania (bez ručitela)'])[1]/preceding::span[1]</value>
      <webElementGuid>6df4d7a0-79b5-4a5d-bc7f-6a0a57a94e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Robert Chamraz']/parent::*</value>
      <webElementGuid>2c73b6d6-68f1-4bb1-95f0-62381a07bee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>19d1886e-7ef2-424a-adeb-f52fd5c1605b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'meno-a-priezvisko-info' and (text() = 'Robert Chamraz' or . = 'Robert Chamraz')]</value>
      <webElementGuid>a847f82d-a5e9-4354-a79f-1974e2e4b533</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
