<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Marek Tirpk</name>
   <tag></tag>
   <elementGuidId>8de666d0-6bdc-4e28-9716-1f2fe547bd09</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#meno-a-priezvisko-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='meno-a-priezvisko-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4ada4d47-0545-4373-8a3f-008bc8f108e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>meno-a-priezvisko-info</value>
      <webElementGuid>931ae1c1-2440-4caa-a579-a7910c80bf14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>a2aeeaa5-ce13-44c6-b655-91e7d0547034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Marek Tirpák</value>
      <webElementGuid>e4b763f6-d16a-474b-b949-fa80bba555d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;meno-a-priezvisko-info&quot;)</value>
      <webElementGuid>8db69ad3-7e95-4117-b191-395dc070ee8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='meno-a-priezvisko-info']</value>
      <webElementGuid>9d701358-214b-424a-9d82-3e7a41cf6af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-sekcia']/div[2]/span</value>
      <webElementGuid>176ee7e4-1445-497e-aedf-3743ee05ab7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[1]/following::span[1]</value>
      <webElementGuid>828ede88-49ba-4253-b3e1-52deeed0c217</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESRVS-2024-2188'])[1]/following::span[1]</value>
      <webElementGuid>1d1f92d9-27b5-4662-b9b0-cf91b66bb248</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ podania'])[1]/preceding::span[1]</value>
      <webElementGuid>afe7320d-d608-40d9-a1c3-6ccb503392a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podávanie žiadosti o pôžičku pre pedagógov z Fondu na podporu vzdelávania'])[1]/preceding::span[1]</value>
      <webElementGuid>419f1c0e-a7d4-4fa0-95a7-00ee7cff3d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Marek Tirpák']/parent::*</value>
      <webElementGuid>ce227101-e753-44df-b131-49d94f24e210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]/span</value>
      <webElementGuid>037160d0-1d6c-4863-93a4-f22330ce0df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'meno-a-priezvisko-info' and (text() = 'Marek Tirpák' or . = 'Marek Tirpák')]</value>
      <webElementGuid>b6c63219-e03f-4c2f-94ca-c2436ceca373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
