<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2148</name>
   <tag></tag>
   <elementGuidId>10e4437b-bd5c-46c8-b28e-0f898ff528f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifikator-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='identifikator-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>cdf6f99b-bffd-4721-9994-4d658fd2fb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifikator-info</value>
      <webElementGuid>d08fd270-5000-4d87-bb8d-1129504df42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2148</value>
      <webElementGuid>1d259f51-fe7a-4e6d-9167-ab0a9fb6a3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifikator-info&quot;)</value>
      <webElementGuid>fcbed2a6-6599-431a-9ee7-a33ca7ce3f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='identifikator-info']</value>
      <webElementGuid>d21f9ef9-fd62-4d6a-a0ab-f84c452b9d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-sekcia']/div/span</value>
      <webElementGuid>32783c50-1b7b-483a-a02e-090a72022e12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor'])[1]/following::span[1]</value>
      <webElementGuid>878ef1d7-c858-4e2b-a10a-53a565d9e2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informácie o podaní'])[1]/following::span[1]</value>
      <webElementGuid>bc6d2330-bf8e-474c-a0ac-61d0133d41b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[1]/preceding::span[1]</value>
      <webElementGuid>935caec9-d9e9-4695-b152-0e493686b90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Robert Chamraz'])[1]/preceding::span[1]</value>
      <webElementGuid>0ddac3fc-3d45-40c4-a135-ad85487256ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2148']/parent::*</value>
      <webElementGuid>a0615537-6c0e-461f-b3d8-b9d6fb0dec97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>b958901b-b189-4eac-9929-d58435f62056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'identifikator-info' and (text() = 'ESRVS-2024-2148' or . = 'ESRVS-2024-2148')]</value>
      <webElementGuid>e5cb0b69-46bc-4d1d-9d81-6e2d4dc14018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
