<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2188</name>
   <tag></tag>
   <elementGuidId>6ae0529f-0feb-4abb-b187-6a4fc620c7d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifikator-info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='identifikator-info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c90d1130-f5be-4d58-94be-b62833bd850e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifikator-info</value>
      <webElementGuid>0404a444-fdaf-4e03-b9d7-c99856f75a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>e6799b41-c989-4ece-89e7-546d33939eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2188</value>
      <webElementGuid>1ae0d1a8-45cf-4412-917d-3b449a2e0b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifikator-info&quot;)</value>
      <webElementGuid>ce395d8c-33b5-44d1-ab7a-2f2c3cb811eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='identifikator-info']</value>
      <webElementGuid>094a8ebc-a769-4a2e-b273-296a6dadac27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info-sekcia']/div/span</value>
      <webElementGuid>d6e9aa4f-c51f-44a3-9115-7a07cef358de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor'])[1]/following::span[1]</value>
      <webElementGuid>bb641bfc-88c6-43b6-aa1a-876127339634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Informácie o podaní'])[1]/following::span[1]</value>
      <webElementGuid>ad943bd4-92d2-4263-b3ac-c89e5068b938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meno a priezvisko'])[1]/preceding::span[1]</value>
      <webElementGuid>eff350fd-2d5f-44de-b0b3-f6776b5070b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marek Tirpák'])[1]/preceding::span[1]</value>
      <webElementGuid>fbc07f01-e7d9-4424-bbf5-e871af1de0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2188']/parent::*</value>
      <webElementGuid>94b00db9-0c14-49d9-975b-7598a084b1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/span</value>
      <webElementGuid>7f9c437f-5bb0-40a8-a367-2658828bbab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'identifikator-info' and (text() = 'ESRVS-2024-2188' or . = 'ESRVS-2024-2188')]</value>
      <webElementGuid>61422180-aaa6-4a39-ad3a-227aba8219cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
