<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vygenerova potvrdenie</name>
   <tag></tag>
   <elementGuidId>d9793821-c818-4c82-a02b-ec314104a5a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tabulkaZamestnavatelia']/table/tbody/tr[2]/td[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5f7f6be9-4960-4959-b681-08fe3671e76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-link</value>
      <webElementGuid>2d9c1285-0341-4d04-b0c7-8e4c0e67fc6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VygenerovatPotvrdenie</value>
      <webElementGuid>672bf427-7b7b-4d2a-864e-3179d25c0f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1297</value>
      <webElementGuid>ffd1cd0f-9a8c-4f28-814c-e987f2a7ca73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vygenerovať potvrdenie</value>
      <webElementGuid>97afa397-e713-402c-96f4-2fee836644fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavatelia&quot;)/table[@class=&quot;govuk-table&quot;]/tbody[@class=&quot;govuk-table__body&quot;]/tr[4]/td[@class=&quot;govuk-table__cell&quot;]/a[@class=&quot;govuk-link&quot;]</value>
      <webElementGuid>5f545678-d396-4163-9df8-c84f38c1b4c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@name='VygenerovatPotvrdenie'])[4]</value>
      <webElementGuid>6bface71-8779-4f6f-9bef-6fd9a5d53a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/table/tbody/tr[4]/td[4]/a</value>
      <webElementGuid>3ef70476-cbab-4aa4-82dd-59912ff23421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Vygenerovať potvrdenie')])[4]</value>
      <webElementGuid>893fe54c-93a2-4315-9660-e48a57190c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stredná odborná škola'])[1]/following::a[1]</value>
      <webElementGuid>2c2ceedb-e5b2-4f63-a5a3-f675d29c7208</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[3]/following::a[1]</value>
      <webElementGuid>f8a06183-beb1-4d7e-b58e-79581c168c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať'])[1]/preceding::a[1]</value>
      <webElementGuid>4d485314-0d33-4995-9526-eddfe61e1cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[1]/preceding::a[1]</value>
      <webElementGuid>3855d614-19c3-4848-913c-b31e7fd7969a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[4]/a</value>
      <webElementGuid>e722465e-74e3-4cb5-ae58-76acf0b31d67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'VygenerovatPotvrdenie' and (text() = 'Vygenerovať potvrdenie' or . = 'Vygenerovať potvrdenie')]</value>
      <webElementGuid>5dbba760-6ece-4358-96fb-7c404105c8c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
