<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pokraova</name>
   <tag></tag>
   <elementGuidId>f929fae4-8b3f-4277-bcdf-8f31cfba1dbb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pokracovat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pokracovat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>29ce275d-b24b-4397-ad79-b1fd5982996a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pokracovat-btn</value>
      <webElementGuid>cf7db0ec-034f-4bcf-a0f4-68bcbc8bf777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>23cc01ec-0e39-47c1-859c-5347309c750b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>774</value>
      <webElementGuid>4168040c-5e21-4c0e-baa8-2ead07b12902</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pokračovať</value>
      <webElementGuid>7efbf0ec-61a5-4e89-9251-2208a9fae2b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pokracovat-btn&quot;)</value>
      <webElementGuid>da083bed-3ca2-47c5-bc52-b82ff07887db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pokracovat-btn']</value>
      <webElementGuid>dcfe711b-7796-49d9-b3b9-c5d30530f59f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[4]</value>
      <webElementGuid>13d1830c-e68a-4a19-944f-c26b28ab7ce6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/following::button[1]</value>
      <webElementGuid>d22024e7-0101-4d45-9796-bdab00fcad1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/following::button[2]</value>
      <webElementGuid>28534299-a0f2-48c2-a861-c85af509e76d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovať'])[1]/preceding::button[1]</value>
      <webElementGuid>1decd72d-7805-4f76-8046-0efb7570acbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť rozpracované podanie'])[1]/preceding::button[2]</value>
      <webElementGuid>9766142b-aaa4-4044-b369-7be8ad330a57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pokračovať']/parent::*</value>
      <webElementGuid>1642ed0e-422a-430a-8863-431ae101866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>92dd0de9-1229-4287-bdd0-33dfb2f89e87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pokracovat-btn' and (text() = 'Pokračovať' or . = 'Pokračovať')]</value>
      <webElementGuid>6e405f10-bf5c-4034-a7e6-14fa00805325</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
