<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Podpsa</name>
   <tag></tag>
   <elementGuidId>6096345d-0fae-44b7-b0a1-fdf4bd15dcc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podpisat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='podpisat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8e587e99-e99c-4a69-a8bf-973e4d55a2a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podpisat-btn</value>
      <webElementGuid>9b92ae8a-bd93-4354-bfa0-68d06a90ce77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>podpisat-btn</value>
      <webElementGuid>513aeeef-959c-4dad-94a8-a355ef673e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green podpisat-odoslat govuk-!-margin-top-4</value>
      <webElementGuid>2f77014e-487f-4865-a80b-38f7280fc3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>772</value>
      <webElementGuid>46fe762c-0f25-46e2-ae54-3db7653a5814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podpísať</value>
      <webElementGuid>bed683da-0dd6-427b-937f-93eb8caa7eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podpisat-btn&quot;)</value>
      <webElementGuid>599a4bc8-ed3f-4346-a5ee-0491bad77883</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='podpisat-btn']</value>
      <webElementGuid>ca399a9f-35b9-4e7d-8757-30e104aff793</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[2]</value>
      <webElementGuid>d8cf9b5d-edde-45d3-a4c9-b17099841567</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/following::button[1]</value>
      <webElementGuid>98125365-f6d2-4b54-b62b-672fbe61fff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/following::button[2]</value>
      <webElementGuid>30e3b2b8-6465-4c62-8527-475d8d729d63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/preceding::button[1]</value>
      <webElementGuid>bfb27e62-48f9-4662-8506-9f054e1b685e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/preceding::button[2]</value>
      <webElementGuid>e23d4d1f-1381-408f-874c-ab21f35a5962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>28f047de-c825-457a-b459-3516bf0ff967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'podpisat-btn' and @name = 'podpisat-btn' and (text() = 'Podpísať' or . = 'Podpísať')]</value>
      <webElementGuid>e2c644fd-72fe-4052-9584-53b537edfa34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
