<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Sp</name>
   <tag></tag>
   <elementGuidId>892b022f-0ec3-41e5-a623-8114e6010075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='spat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d2d8864a-3a1d-4c28-bcc3-eac0a1dd3ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>spat-btn</value>
      <webElementGuid>77af5eae-2292-4316-8618-10efdd6e94af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button secondary govuk-!-margin-top-4</value>
      <webElementGuid>109901ab-7dae-4470-b446-f50a3ad8ccd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>771</value>
      <webElementGuid>7ed0ac42-cbc0-4ac2-8612-53208ff5a605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Späť</value>
      <webElementGuid>c97d3c6b-b9e0-473c-b4af-46c9234e0459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spat-btn&quot;)</value>
      <webElementGuid>3ba9ef34-7e56-4b63-84e8-46499b1f434b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='spat-btn']</value>
      <webElementGuid>eee1f980-aa04-4fc2-9309-4c1748126bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button</value>
      <webElementGuid>e90160c6-0f1e-46b2-979c-90f3ed67a0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/following::button[1]</value>
      <webElementGuid>04613d3f-bca7-41f7-b5a4-838492e8ac72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa'])[1]/following::button[2]</value>
      <webElementGuid>b1e47238-876a-4981-8e9e-80f1eb4d3a6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/preceding::button[1]</value>
      <webElementGuid>d1f0fd5b-90d6-403f-a574-cf5d2d98b7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/preceding::button[2]</value>
      <webElementGuid>01810f5b-6e1e-40a0-bb4a-15d707b36c45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Späť']/parent::*</value>
      <webElementGuid>f41fd674-6ed9-4144-a616-75b80f1d4281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button</value>
      <webElementGuid>b00ad951-1ec4-42a1-b30a-93c85a999185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'spat-btn' and (text() = 'Späť' or . = 'Späť')]</value>
      <webElementGuid>a2c5bf06-b359-4e0d-859f-2f784d4131fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
