<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Podpsa iados o piku kvalifikovanm el_0eb4be</name>
   <tag></tag>
   <elementGuidId>8bd2935c-355a-4a88-a6e5-79a3dde3f8d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podpisat-a-odoslat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='podpisat-a-odoslat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>beb486af-e258-4c36-b052-96c39adac02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>44be46a4-4948-4f61-8e57-b498ebb5051e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>ce80b05a-771d-476c-b05b-d2de7ea3d0b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>e3ac98dd-6b90-4b06-af53-1620a3e6cce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>2336</value>
      <webElementGuid>f3496bc8-48a8-4e4a-9442-c42f387b2af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa</value>
      <webElementGuid>4ac91fdc-4822-444f-8503-9fc7240b8849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podpisat-a-odoslat-btn&quot;)</value>
      <webElementGuid>9d3f0dfd-b489-4f91-a347-5901426f6de2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='podpisat-a-odoslat-btn']</value>
      <webElementGuid>e631531a-e86f-45ac-9844-97e7ab4f147d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odoslanie-podpisanie-buttons']/div/button</value>
      <webElementGuid>3e04c8fb-b4a1-467b-83e8-0bd9ea655bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na domovskú stránku'])[2]/following::button[1]</value>
      <webElementGuid>91525f74-6a70-47da-97b8-8bd75e238585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fond na podporu vzdelávania'])[2]/following::button[1]</value>
      <webElementGuid>d13e7e12-75da-4f43-b979-b43c0bcddebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/preceding::button[1]</value>
      <webElementGuid>9431ce93-4e09-42f2-8045-15ddca037cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::button[2]</value>
      <webElementGuid>6f22d7aa-805d-42d6-863c-f7464663a9ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa']/parent::*</value>
      <webElementGuid>f605e969-9ab3-472e-a83d-b3e6cfddbe76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>011cbeea-6e42-4957-b62b-aee41827afcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'podpisat-a-odoslat-btn' and @name = 'podpisat-a-odoslat-btn' and (text() = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa' or . = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa')]</value>
      <webElementGuid>0f43a9f2-1518-4ff7-bd17-279d41a3ea62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
