<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi_1</name>
   <tag></tag>
   <elementGuidId>85e39aad-96b9-4f24-8832-52e6acfce89a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-ulozit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-ulozit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5e622dc9-c4ed-4181-9715-fa06ad3cf037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>18fa4303-85b5-4612-8151-b4d845418746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save govuk-button</value>
      <webElementGuid>9612d8a0-616a-4ce5-ad8f-b01b771d88ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-ulozit</value>
      <webElementGuid>9ee04757-d4cd-430a-86e3-c32905b67101</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1738</value>
      <webElementGuid>c6c1a086-3b99-411a-97ad-56caf4e39a9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>7d6f8716-8e9e-4b00-b28b-d7743d2db0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeaterZamestnavatelia&quot;)/div[@class=&quot;section-repeater-container&quot;]/div[@class=&quot;govuk-button-table&quot;]/button[@class=&quot;save govuk-button&quot;]</value>
      <webElementGuid>56820f37-1af7-4f3a-aff4-933f875d5e4f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-ulozit']</value>
      <webElementGuid>897a2720-8f57-40b0-99a5-f896f161cb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeaterZamestnavatelia']/div/div/button</value>
      <webElementGuid>40000630-9ca5-4fb6-80f0-7ec84fd65479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Položka musí byť vyplnená!'])[7]/following::button[1]</value>
      <webElementGuid>0c729898-694e-4442-8653-b7eccf80c4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uveďte sumu po odpočítaní povinných zrážok/bez odvodov a dane, t.j. plat poukazovaný na účet.'])[1]/following::button[1]</value>
      <webElementGuid>772d3285-81e1-4576-ac52-2bc9520b8a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[1]/preceding::button[1]</value>
      <webElementGuid>13792858-1b14-4ff9-98fd-e65ebb708718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI_V_ZP_in_UdajeZamestnavatela'])[2]/preceding::button[2]</value>
      <webElementGuid>6518b384-f671-4f05-a655-bbd569cd80cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uložiť']/parent::*</value>
      <webElementGuid>8b4b12a6-5ee4-4076-8078-065e3c7bfa82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>be87b484-d365-4c74-808f-86f6c715ba2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btn-ulozit' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>8be3a8cd-90d0-4991-8345-1f03f5f4ed9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
