<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>45784201-c65c-4dee-a079-3f0636671244</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-prilohy-btn-D51</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-prilohy-btn-D51']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3f6db48-5993-473f-bcfb-c4191f046aab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-prilohy-btn-D51</value>
      <webElementGuid>ca66a7f3-24e9-43ae-929d-75f3088b4f78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-!-font-size-19 govuk-button secondary</value>
      <webElementGuid>58a96649-5729-472e-9060-242fb263dec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typprilohykod</name>
      <type>Main</type>
      <value>D51</value>
      <webElementGuid>f6521a33-b945-4baf-ab60-094d1ee8cd7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1996</value>
      <webElementGuid>72d4a3e5-09a9-4431-a470-a4162d8b48ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>7d7c65c3-9195-40da-8d63-32b7f294ac5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prilohy-btn-D51&quot;)</value>
      <webElementGuid>cdaee920-1f0d-4982-802e-12818af9ba55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-prilohy-btn-D51']</value>
      <webElementGuid>1370773f-e787-42d7-9464-0056ce274016</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skutocnosti-prilohy-27']/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>eaca7bea-8d98-447f-b27d-8f2f81ab8267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doklad o udelení ocenenia udelené ministrom školstva'])[1]/following::button[1]</value>
      <webElementGuid>f6d5df3c-887c-4f76-894a-48dbc42edfe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spôsob doloženia prílohy'])[10]/following::button[1]</value>
      <webElementGuid>083b8c6d-db4d-4546-92fa-7e351d1c7029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vykonal som dizertačnú skúšku (relevantné iba pre doktoranda v dennej forme štúdia)'])[1]/preceding::button[1]</value>
      <webElementGuid>d406a9d4-0c3b-401a-9914-81ca5f4a7ebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy'])[11]/preceding::button[1]</value>
      <webElementGuid>4115dedc-922b-460f-8e0a-98d138f33ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>30e270a2-5212-4755-a87f-49e4d9b7ce8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-prilohy-btn-D51' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>1ec80cfd-e8e8-4a1f-bd90-4c290f28c043</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
