<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odstrni</name>
   <tag></tag>
   <elementGuidId>3ab0f669-ccca-43e5-8454-0e3f89972c4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabulkaZamestnavateliaOdstranit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabulkaZamestnavateliaOdstranit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0b9fafad-e156-4b1e-8507-6d55e0751598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>6c6e91cc-f4c8-4fc6-b8d0-2666401b8adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button red</value>
      <webElementGuid>be849aa8-3cf9-48ef-8e91-84d4931cdb28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabulkaZamestnavateliaOdstranit</value>
      <webElementGuid>d0101e18-5858-408e-89b2-cad085f3b1fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>851</value>
      <webElementGuid>be0d66da-4951-4da3-935c-72815b4ce35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odstrániť</value>
      <webElementGuid>9b2583cb-edd1-4eb7-89f2-358fcea3fd67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavateliaOdstranit&quot;)</value>
      <webElementGuid>4762f57d-9115-44de-8e63-18b13d08bb46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabulkaZamestnavateliaOdstranit']</value>
      <webElementGuid>a9144750-237d-4274-9afd-637d37ec09ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/div/button[3]</value>
      <webElementGuid>19d6014f-678a-4ad4-8b30-430936930a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[1]/following::button[1]</value>
      <webElementGuid>42afad15-5fa3-4c6d-847b-bbee4fa24761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať'])[1]/following::button[2]</value>
      <webElementGuid>761114fa-e5af-4444-a015-804b8cbf3149</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI_V_ZP_in_UdajeZamestnavatela'])[1]/preceding::button[1]</value>
      <webElementGuid>21a335ef-9236-412f-9e92-cd1d6c988357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov zamestnávateľa'])[2]/preceding::button[1]</value>
      <webElementGuid>fa63b3be-3b26-4f44-a3d5-fc419d893207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odstrániť']/parent::*</value>
      <webElementGuid>f6748cbb-8e81-4af9-9a8c-a06baaf5cb23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>7c688b21-c17c-4425-a67a-bc6d177cfe0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'tabulkaZamestnavateliaOdstranit' and (text() = 'Odstrániť' or . = 'Odstrániť')]</value>
      <webElementGuid>35fd83a7-1965-42cd-85ff-3fc4d5d0b1e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
