<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail_1_2_3</name>
   <tag></tag>
   <elementGuidId>2668c5d5-ab61-4039-a18b-cf6cc196802e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-prilohy-btn-D78</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-prilohy-btn-D78']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b57d8218-e43b-4f2b-adb8-0b1e5ab0b94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-prilohy-btn-D78</value>
      <webElementGuid>7224bd91-1732-40fe-9829-895659b97948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-!-font-size-19 govuk-button secondary</value>
      <webElementGuid>e148d371-eac5-4be1-93dc-ffe67de4cc95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typprilohykod</name>
      <type>Main</type>
      <value>D78</value>
      <webElementGuid>9c6e3a98-7782-43ea-a4a9-5f745c5e8445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1896</value>
      <webElementGuid>547f280d-f105-435e-935a-888784ae59a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>c1262c06-6d92-453a-b7bc-c99f876ff695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prilohy-btn-D78&quot;)</value>
      <webElementGuid>716586fe-49f6-4c0f-99bc-cace322512a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-prilohy-btn-D78']</value>
      <webElementGuid>335daab9-4843-4e33-85bf-99d7b161950d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skutocnosti-prilohy-20']/fieldset/table/tbody/tr[3]/td[3]/button</value>
      <webElementGuid>5ff3dc9e-7371-47a4-b70c-0322612403c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie zamestnávateľa o výške čistého funkčného/služobného platu (5)'])[1]/following::button[1]</value>
      <webElementGuid>988b8e9a-7849-4821-a5c9-2efe7ba012d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[3]/following::button[1]</value>
      <webElementGuid>a70949a5-38ee-4a9e-acb5-ebc33dd2711b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie zamestnávateľa o výške čistého funkčného/služobného platu (4)'])[1]/preceding::button[1]</value>
      <webElementGuid>5196d71c-b41a-4489-b8fb-0d6b82f187cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[5]/preceding::button[1]</value>
      <webElementGuid>ddefd758-da53-4adf-89b0-ced7b0994de9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/button</value>
      <webElementGuid>44ad16db-810f-403b-a82f-cf6e9d2bac71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-prilohy-btn-D78' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>169f6647-e7fb-49fc-92be-e9c5db57fc5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
