<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi_1_2</name>
   <tag></tag>
   <elementGuidId>1ac57411-3b61-4bb1-920f-9f55c857575d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#vyber-suboru > div.govuk-form-group > #ulozit-detail-prilohy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='ulozit-detail-prilohy'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a50e24eb-0f14-41f3-8fe6-cd8477227f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ulozit-detail-prilohy</value>
      <webElementGuid>b0836551-c8a5-486f-8043-644482f88f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>fc31f8a3-3ba0-4066-b2a4-5b1d0bdf7c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1885</value>
      <webElementGuid>98682e07-15ca-4b81-b47c-72752b8fac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>522a87cb-7fb3-496e-8788-ecbb93069bed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-19&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;vyber-suboru&quot;]/div[@class=&quot;govuk-form-group&quot;]/button[@id=&quot;ulozit-detail-prilohy&quot;]</value>
      <webElementGuid>6d8903e1-e27e-41b5-a510-0ff7d1912425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='ulozit-detail-prilohy'])[2]</value>
      <webElementGuid>7e458f44-c1be-41e8-bea4-828f43c07970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vyber-suboru']/div[2]/button[2]</value>
      <webElementGuid>6f20fc5d-2785-41b5-a8b1-3b495a981ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[7]/following::button[1]</value>
      <webElementGuid>66f314fa-e7df-4410-8aee-c55a44e48344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='prílohu k žiadosti doložím v listinnej podobe'])[1]/following::button[2]</value>
      <webElementGuid>52171daa-4cb8-4c91-b92d-e9e926d3a412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy'])[3]/preceding::button[1]</value>
      <webElementGuid>48ff6025-3baa-406f-8fcd-4c69908d2691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spôsob doloženia prílohy'])[3]/preceding::button[1]</value>
      <webElementGuid>fa0b8f6f-ab7c-4152-8bda-1c6c553b000f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button[2]</value>
      <webElementGuid>9732c166-38f5-45e1-8441-6fb172a1ad62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ulozit-detail-prilohy' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>47393aa1-42d8-4d6b-868f-4b485dda5485</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
