<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Skontrolova</name>
   <tag></tag>
   <elementGuidId>cd1a2e2c-8384-4848-9f52-2efcb4bbfe8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#skontrolovat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='skontrolovat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46034770-ef3c-466b-9422-799bd01c13da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>skontrolovat-btn</value>
      <webElementGuid>c824ac26-b226-448c-8917-02d827472177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button primary green govuk-!-margin-top-4 govuk-!-margin-left-2</value>
      <webElementGuid>9b0fef30-3fac-4723-b100-7b051432504c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>775</value>
      <webElementGuid>2da91c17-43a1-4998-b955-38dd34db8d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Skontrolovať</value>
      <webElementGuid>f63c0c5c-8452-4dcd-9190-3c54055f1d60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skontrolovat-btn&quot;)</value>
      <webElementGuid>42bf4ada-0851-43ed-b7e0-edba69afcbcf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='skontrolovat-btn']</value>
      <webElementGuid>f0e1ebe9-3229-45e1-a487-ac84ca116bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[5]</value>
      <webElementGuid>a2e8eeac-9184-4358-b6cc-4c0e1e8a4d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/following::button[1]</value>
      <webElementGuid>4d1ed2cd-f6f2-4821-a108-4c35f7d6309b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/following::button[2]</value>
      <webElementGuid>685d6b68-e82e-4b2a-ab78-ad54fe4c946d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť rozpracované podanie'])[1]/preceding::button[1]</value>
      <webElementGuid>f30435d5-8fce-4106-a7a5-413e2fb50e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť do súboru'])[1]/preceding::button[2]</value>
      <webElementGuid>465bd979-9500-4c2d-9be2-cb30668401e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Skontrolovať']/parent::*</value>
      <webElementGuid>7a1908a0-0a41-482a-a0e0-b8f1b417d107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>1234ef13-3443-4bb7-98f2-c4f0bbf02acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'skontrolovat-btn' and (text() = 'Skontrolovať' or . = 'Skontrolovať')]</value>
      <webElementGuid>ac2b967e-6062-4267-b624-f2cf7a08d1fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
