<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi</name>
   <tag></tag>
   <elementGuidId>fd4fe4a6-e53f-4237-9801-3210f135ca67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;btn-ulozit-3&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='btn-ulozit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4c20f2dc-19d5-4672-9662-2ba9e00090d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>a3356718-9d58-4d0b-9078-5f6a867bb1d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>save govuk-button</value>
      <webElementGuid>6b9e74b5-9015-4e07-8c0c-472ffdc6f6f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>btn-ulozit-3</value>
      <webElementGuid>56bdd11b-921a-4633-8b83-26e595f36f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1264</value>
      <webElementGuid>e55e3d8e-1574-4dd1-900b-1ff4381c009a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>67e38205-7dc9-4525-895b-60860122b0b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeaterZamestnavatelia&quot;)/div[@class=&quot;section-repeater-container&quot;]/div[@class=&quot;govuk-button-table&quot;]/button[@class=&quot;save govuk-button&quot;]</value>
      <webElementGuid>451deec5-d9f2-4257-9870-3afed8b38ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='btn-ulozit-3']</value>
      <webElementGuid>a8d50507-d615-47f5-aa15-0d4eb72c741b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeaterZamestnavatelia']/div[3]/div/button</value>
      <webElementGuid>c346ca68-c55f-4514-98d1-1e8bbd37e78a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Položka musí byť vyplnená!'])[15]/following::button[1]</value>
      <webElementGuid>7eb8de14-f298-4073-b2f0-481c9c23c95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uveďte sumu po odpočítaní povinných zrážok/bez odvodov a dane, t.j. plat poukazovaný na účet.'])[3]/following::button[1]</value>
      <webElementGuid>8b18043a-388d-4f3d-8009-873fdd71cf06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[3]/preceding::button[1]</value>
      <webElementGuid>a539e30a-bc52-4b84-9970-98d229979342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UI_V_ZP_in_UdajeZamestnavatela'])[4]/preceding::button[2]</value>
      <webElementGuid>ad0aa381-030e-4836-b467-dfdabd4d8f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>a3f6617c-04e8-408d-bbe4-021d6d92f4ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'btn-ulozit-3' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>70ce556a-b0e3-48c3-b0b1-b465a325f073</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
