<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prejs na domovsk strnku</name>
   <tag></tag>
   <elementGuidId>01ec0932-eb67-44cf-9470-cee95ce0cbba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go-home-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go-home-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5452cbe-1ae1-4159-b275-00a7f58f1ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-home-btn</value>
      <webElementGuid>875ad574-0389-4dd0-acba-e97af9fac1b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green</value>
      <webElementGuid>b087a560-cb1d-4ffd-9d8c-1a786756e403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>2381</value>
      <webElementGuid>540a445f-d0d9-40d5-8180-ab242c54e198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prejsť na domovskú stránku</value>
      <webElementGuid>5d97673b-8714-47b1-9b4b-ac13afa509dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-home-btn&quot;)</value>
      <webElementGuid>32a89608-0df5-4f63-8938-cf23add2a45d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go-home-btn']</value>
      <webElementGuid>c65d7841-7528-44d4-b047-46e0e16f3f94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-spokojnosti-s-e-sluzbou']/div[4]/button[2]</value>
      <webElementGuid>b9067925-cd37-45c6-97ba-0f70fb192746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať spätnú väzbu'])[1]/following::button[1]</value>
      <webElementGuid>ae64edb2-dc37-4d5c-b113-816d7bf723dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ďakujeme za spätnú väzbu.'])[1]/following::button[2]</value>
      <webElementGuid>25f6ffdc-f3c1-4c2f-9c4a-f03e19da027e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Čo bude nasledovať?'])[2]/preceding::button[1]</value>
      <webElementGuid>d070d5b1-44dc-45f3-9705-ab4e9989e0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prejsť na domovskú stránku']/parent::*</value>
      <webElementGuid>c8236b9a-945e-4778-a7ef-e9fa44c6e800</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>3db1cb53-480c-471f-8ee9-fb358b1b4064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'go-home-btn' and (text() = 'Prejsť na domovskú stránku' or . = 'Prejsť na domovskú stránku')]</value>
      <webElementGuid>e53d72ec-e6d5-44fb-8ca1-07d2918e79c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
