<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odosla</name>
   <tag></tag>
   <elementGuidId>88a3271a-1a75-45a0-a01c-9cf11e964cef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-buttons-section > #odoslat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='odoslat-btn'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>85b3c707-b083-460f-99d5-7d265d9a5529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>odoslat-btn</value>
      <webElementGuid>a463fe84-0b99-4c82-a311-8bf360302634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odoslat-btn</value>
      <webElementGuid>dd58e173-7a82-43ac-a785-bee70e417dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green odoslat govuk-!-margin-top-4</value>
      <webElementGuid>55a0e1aa-544f-401d-8530-a93f23961a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>773</value>
      <webElementGuid>b9c20cfb-fab8-4122-a0be-675a2b978490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odoslať</value>
      <webElementGuid>bc65a047-e631-4822-9921-5a0b11a33314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-buttons-section&quot;)/button[@id=&quot;odoslat-btn&quot;]</value>
      <webElementGuid>fc8e7ef0-4711-4d58-9805-cf333ba5d358</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='odoslat-btn'])[2]</value>
      <webElementGuid>cb05c192-6594-4615-8fd1-ada72f20c5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[3]</value>
      <webElementGuid>05c9663d-3546-4bf8-8d00-d5ebf131f9ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/following::button[1]</value>
      <webElementGuid>4fadc22c-aca5-40b8-bfd3-e3b2ec7564c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/following::button[2]</value>
      <webElementGuid>b76662e4-12d3-4eec-97fd-a05cfb0fdb5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/preceding::button[1]</value>
      <webElementGuid>bf218a2f-5fbe-40a6-a142-93dc756c7625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovať'])[1]/preceding::button[2]</value>
      <webElementGuid>8a1afc5d-d978-4278-a82f-0db3328eb408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[3]</value>
      <webElementGuid>b3091ea5-05b9-4b77-a1be-b1d8f71d83ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'odoslat-btn' and @name = 'odoslat-btn' and (text() = 'Odoslať' or . = 'Odoslať')]</value>
      <webElementGuid>0d85755d-fdd7-4944-b44e-6c983e1063d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
