<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prida</name>
   <tag></tag>
   <elementGuidId>ff453b48-c9bf-4f33-ab47-fd45a30ee88c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabulkaZamestnavateliaPridat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabulkaZamestnavateliaPridat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>496c48fa-8beb-43a4-834e-5d962d4f3ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>daa1db4f-d6e1-4f89-93ae-b8ece3512819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>84eedbd7-0cc1-4cdb-873a-0aa3167bcdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabulkaZamestnavateliaPridat</value>
      <webElementGuid>9fb682cd-0b4c-42d5-b8cf-ce06619d9a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>849</value>
      <webElementGuid>c87486a4-cb5a-427f-baeb-6f96fd9de19d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pridať</value>
      <webElementGuid>8043ead9-12b0-46bb-accb-6dae13553c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavateliaPridat&quot;)</value>
      <webElementGuid>a4fa3aec-c927-4623-ac73-e6940426a997</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabulkaZamestnavateliaPridat']</value>
      <webElementGuid>103a9a40-9e8e-4b73-afcb-06cac29172c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/div/button</value>
      <webElementGuid>7ba9e4b2-e795-4443-a27b-5262247f299d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[3]/following::button[1]</value>
      <webElementGuid>dbb674b7-35dd-4868-a47c-2719dfd58071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stredná odborná škola technická, Košice 1, Košice'])[1]/following::button[1]</value>
      <webElementGuid>f639ebb1-7883-479a-8636-c56d4a0fd2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upraviť'])[1]/preceding::button[1]</value>
      <webElementGuid>72622043-9d5a-4a23-8ef4-1f774fa326cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odstrániť'])[1]/preceding::button[2]</value>
      <webElementGuid>ed654610-d989-4581-a05a-cedfb80a2bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pridať']/parent::*</value>
      <webElementGuid>56f55116-73db-4773-a8e3-a8bd725690f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0ea5c774-b72f-4bcc-a09f-2d9851441358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'tabulkaZamestnavateliaPridat' and (text() = 'Pridať' or . = 'Pridať')]</value>
      <webElementGuid>9c132fe5-67e6-49e5-acc8-e7097e83e006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
