<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail_1</name>
   <tag></tag>
   <elementGuidId>cbf77e6f-6f69-41b3-a63f-f36f23f84b9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-prilohy-btn-D75</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-prilohy-btn-D75']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>911fb17d-52eb-4b4e-b57b-5056f29dbb0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-prilohy-btn-D75</value>
      <webElementGuid>b4e53050-4459-4c62-81b8-90d3bc5d585b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-!-font-size-19 govuk-button secondary</value>
      <webElementGuid>96e4586d-227c-43fd-a06f-57ce1ee49346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typprilohykod</name>
      <type>Main</type>
      <value>D75</value>
      <webElementGuid>6bc841a3-684a-4caf-bfdb-6ac22e9afa5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1902</value>
      <webElementGuid>b7e4ce02-9776-4214-b672-0790149b7419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>794d30f8-c479-4667-ab42-51f0bfb3fd0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prilohy-btn-D75&quot;)</value>
      <webElementGuid>31072946-1069-489d-956e-4dc3f498b9ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-prilohy-btn-D75']</value>
      <webElementGuid>3801a627-203c-4267-8e5a-b57e9c28c08e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skutocnosti-prilohy-20']/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>56b9aa4c-ef1c-4cde-9308-fd0339b3cd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie zamestnávateľa o výške čistého funkčného/služobného platu (2)'])[1]/following::button[1]</value>
      <webElementGuid>a05729b9-58fc-4964-a73e-e7ad976b55de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spôsob doloženia prílohy'])[3]/following::button[1]</value>
      <webElementGuid>a7ca7847-9304-4241-a6a3-b98bf1f3d565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie zamestnávateľa o výške čistého funkčného/služobného platu (3)'])[1]/preceding::button[1]</value>
      <webElementGuid>ef0ce9ba-f5ed-4fa9-83d7-5138d51c8cf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[3]/preceding::button[1]</value>
      <webElementGuid>4ac2d1f8-2e74-4916-a4de-dbf0651a5496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>c67454da-687f-443a-8fe9-01c44777eae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-prilohy-btn-D75' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>3b38d95d-93d8-4463-a4aa-4e6ae8527d02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
