<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ESRVS-2024-2188</name>
   <tag></tag>
   <elementGuidId>6733d7bc-01c0-45a9-b297-b62491b0cf47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.eform_ro.row-value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-content']/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c8ad4016-7f70-4d0e-97ca-2eb5317fc3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>eform_ro row-value</value>
      <webElementGuid>a3fd69e0-082f-4a1c-b045-00532262192d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>2171</value>
      <webElementGuid>7be9f941-13c2-4c08-ad60-88408ae1f5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2188</value>
      <webElementGuid>01a92683-8f3a-4563-8fd6-0bb9108ad95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_Zhrnutie_UI_P_VR_in_Nahlad&quot;)/div[@id=&quot;main-content&quot;]/div[@class=&quot;eform_ro govuk-width-container&quot;]/div[@class=&quot;eform_ro row&quot;]/div[@class=&quot;eform_ro row-value&quot;]</value>
      <webElementGuid>65cc520a-41b8-456e-bdbc-6bd932f795e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-content']/div/div/div[2]</value>
      <webElementGuid>ae5a80ee-93b9-49a0-9bf7-693e7bf32319</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Identifikátor žiadosti'])[1]/following::div[1]</value>
      <webElementGuid>4ba4a52f-b327-4655-8f2b-75b454adb03c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zhrnutie žiadosti'])[2]/following::div[5]</value>
      <webElementGuid>ad0646fe-5625-4529-993f-99dbf9d51bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum vytvorenia'])[1]/preceding::div[1]</value>
      <webElementGuid>da743027-38b2-47cb-ae1c-fb1f44f0779c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Miesto odoslania žiadosti'])[2]/preceding::div[4]</value>
      <webElementGuid>6f013cdb-6f0e-4287-8fd8-8e016306e137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/fieldset/div/div/div/div[2]</value>
      <webElementGuid>772f4f06-7e3d-4947-9d02-a2eb73868d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ESRVS-2024-2188' or . = 'ESRVS-2024-2188')]</value>
      <webElementGuid>0ec83061-b4cc-483f-938e-66e94942303f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
