<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Martin nad itavou (Zlat Moravce)</name>
   <tag></tag>
   <elementGuidId>3c5c032d-8399-4663-b058-dd1eb9e8abea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[value=&quot;110451&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='110451']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3ac14e59-e554-4d41-9d5e-a8871f5d6e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>110451</value>
      <webElementGuid>d16b572f-36d4-4c14-a10a-b99d33d632f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>547</value>
      <webElementGuid>849d4f36-290a-4513-94ed-8c956299de50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Martin nad Žitavou (Zlaté Moravce)</value>
      <webElementGuid>44f790eb-efd3-4a5d-b6f5-af81aaa926f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_Obecautocomplete-list&quot;)/div[2]</value>
      <webElementGuid>4eea926a-4d2c-4912-9a2a-4f0e3e480352</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='110451']</value>
      <webElementGuid>323f8804-e62c-406f-ada4-1b7f8b5bce6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obecautocomplete-list']/div[2]</value>
      <webElementGuid>ed4798c1-a6db-44fb-b0c1-0e5a79e10222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Martin'])[1]/following::div[1]</value>
      <webElementGuid>a1e6b293-7a4b-4617-b914-1a97f1fbecd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='nad Žitavou (Zlaté Moravce)']/parent::*</value>
      <webElementGuid>75a4640f-cd63-4781-8c58-1a771f620765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div[2]</value>
      <webElementGuid>841c8106-e481-47a0-bf15-857f6aab3125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Martin nad Žitavou (Zlaté Moravce)' or . = 'Martin nad Žitavou (Zlaté Moravce)')]</value>
      <webElementGuid>975ab19d-c1b7-4cca-9a41-2cff42439108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
