<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Uloi                                   _989187</name>
   <tag></tag>
   <elementGuidId>533d5375-911d-447e-9fd1-67824fbfc926</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='repeaterZamestnavatelia']/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0a79189e-bbb2-426b-8f15-af281dfd3a73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button-table</value>
      <webElementGuid>3d13a6fe-c707-41bc-8791-b458edb57428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1263</value>
      <webElementGuid>636e072b-7e4e-47ec-8fec-d680d552e4c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                    Uložiť
                                                    Zrušiť
                                                </value>
      <webElementGuid>3bd4dbab-9270-443d-80ed-1c8e67e7935a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;repeaterZamestnavatelia&quot;)/div[@class=&quot;section-repeater-container&quot;]/div[@class=&quot;govuk-button-table&quot;]</value>
      <webElementGuid>82afd073-92a0-4221-a0d7-0259e8b6b7ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='repeaterZamestnavatelia']/div[3]/div</value>
      <webElementGuid>fa6f872c-6c68-4b3d-a309-3b00881849a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Položka musí byť vyplnená!'])[15]/following::div[1]</value>
      <webElementGuid>75dd59fb-81cb-45a3-a58b-5c544aa08817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uveďte sumu po odpočítaní povinných zrážok/bez odvodov a dane, t.j. plat poukazovaný na účet.'])[3]/following::div[1]</value>
      <webElementGuid>858fabc8-b913-438e-866f-218a75cb266e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/div</value>
      <webElementGuid>63584ffc-4c64-494d-8612-e771ff84f840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
                                                    Uložiť
                                                    Zrušiť
                                                ' or . = '
                                                    Uložiť
                                                    Zrušiť
                                                ')]</value>
      <webElementGuid>aef3dbbf-6a9f-4bd7-af2c-fceff5f8cce6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
