<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Martin (Martin)</name>
   <tag></tag>
   <elementGuidId>a6e2eb35-cd69-4acf-8df8-8f4a310a1fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[value=&quot;110449&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@value='110449']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>36e588ae-28c9-4427-bd30-05077b460590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>110449</value>
      <webElementGuid>75325fd1-b568-47a3-901f-d45ded67d97c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>545</value>
      <webElementGuid>6e41d58f-3c27-4b9c-b09d-af45f48ab697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Martin (Martin)</value>
      <webElementGuid>c2473b49-47da-4963-8278-3bd209cf7dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_Obecautocomplete-list&quot;)/div[1]</value>
      <webElementGuid>9593fed5-234d-468a-957c-015c8d0c7a57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@value='110449']</value>
      <webElementGuid>ac78e7a8-3afe-4535-be1b-adafdca1d39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obecautocomplete-list']/div</value>
      <webElementGuid>7c930ed6-5f6e-45af-af60-e58159cafb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vyhľadajte obec po zadaní prvých 3 znakov a vyberte obec zo zoznamu zobrazených obcí !'])[1]/following::div[2]</value>
      <webElementGuid>12173e00-e01e-4a38-abcd-e7ce6af89c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Obec/Mesto'])[3]/following::div[2]</value>
      <webElementGuid>3b097940-fc6d-4dbf-b776-7145b475a2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='(Martin)']/parent::*</value>
      <webElementGuid>672416b9-13b2-49f6-813b-5696028222f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div[2]/div/div</value>
      <webElementGuid>5e9ea2ce-5ef5-4460-a729-4b55201d6892</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Martin (Martin)' or . = 'Martin (Martin)')]</value>
      <webElementGuid>35bff850-26d0-4329-b4e5-8632a771c5c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
