<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte poadovan splatnos piky na cel_03b518</name>
   <tag></tag>
   <elementGuidId>300ab13e-4c1a-4459-8968-8bb5572f826e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e38e6ab-96a8-47bd-aa2d-3bac2b3c942f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>961e17ac-d7ad-4a03-9a95-cd9b7ff94ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control</value>
      <webElementGuid>4163a369-815c-4a49-b6fe-595b7cef38fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control</value>
      <webElementGuid>7d3948c8-3d7c-4f75-96d0-bf56df73a167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>37da7191-f624-47ea-b7d4-e86dcb6e2563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-hint</value>
      <webElementGuid>2f3d4e3d-7113-409b-8d63-6d43cfe44e14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>793</value>
      <webElementGuid>9ddfc98c-3d6c-41c8-8b79-d3fad27cb250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control&quot;)</value>
      <webElementGuid>e1232a6e-2ee8-47cd-ae8c-8e4d46dc00b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control']</value>
      <webElementGuid>e7de9044-9db1-4764-8cf5-12084f1d4d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky']/input</value>
      <webElementGuid>9cecb75e-5d65-494a-a9cf-159792791474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div[2]/input</value>
      <webElementGuid>4390c6e7-ce5d-46f8-9fde-22d993bf74da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control' and @name = 'UI_V_ZP_in_VyskaLehotaPozicky_SplatnostPozicky-control' and @type = 'number']</value>
      <webElementGuid>08617c66-c97d-4760-a840-0fec3a45771b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
