<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poloka mus by vyplnen_UI_V_ZP_in_Udaj_cdc09e</name>
   <tag></tag>
   <elementGuidId>5c52d692-803f-4e82-916d-9bf801535952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_UdajeZamestnavatela_Email-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Email-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>44c199d0-b3e2-4f33-b440-cd6a8e5e0759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>23c4d243-10ca-440c-abb8-580478fca17c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-control</value>
      <webElementGuid>8022bf01-e1d6-4980-96af-0a788df37ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-control</value>
      <webElementGuid>49a81555-7651-4830-823d-6e8af1551d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>30c3e9f6-1526-475b-8266-036781e27029</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-hint</value>
      <webElementGuid>f1a83160-b384-44b9-9234-9f43c19fc473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1362</value>
      <webElementGuid>7f277f11-a0fb-45e3-9336-e6033468f586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZamestnavatela_Email-control&quot;)</value>
      <webElementGuid>081bdabf-5332-459f-b259-02261142c6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Email-control']</value>
      <webElementGuid>26f3e427-8120-488a-839f-87244a65eaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZamestnavatela_Email']/input</value>
      <webElementGuid>ae244462-5d74-4f05-af56-8a854994e16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/fieldset/div[3]/input</value>
      <webElementGuid>513bae61-1793-4d20-bfd9-15a8eac28aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_UdajeZamestnavatela_Email-control' and @name = 'UI_V_ZP_in_UdajeZamestnavatela_Email-control' and @type = 'text']</value>
      <webElementGuid>1c9dbc3e-8141-470c-9cb7-47c27f234966</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
