<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uvete presn nzov zamestnvatea, kde pr_60e2d0</name>
   <tag></tag>
   <elementGuidId>d9e1e7c1-187b-405a-9223-8ea08e3fb315</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>585fa240-9db2-425b-8581-57594fb7653d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>eec77353-0eb7-4f8c-b814-e4ab1c4d3d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3</value>
      <webElementGuid>8775e150-0548-40b1-8724-0e707c432653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3</value>
      <webElementGuid>23e9daa2-58a1-4b15-adf6-8fe1d86d0c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd3d8d82-c94f-4af4-b04e-2b2d2e214f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-hint</value>
      <webElementGuid>c6934c0d-1c86-470c-b3de-275e4620deac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>886</value>
      <webElementGuid>1470c66b-e500-47df-9ed0-a71390f73e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3&quot;)</value>
      <webElementGuid>00d7572c-a2e9-4405-beda-95de1a011d26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3']</value>
      <webElementGuid>4d20e9a9-6a29-43ba-bd67-8a0642dc1baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov-3']/input</value>
      <webElementGuid>b6a8c124-dc0a-43e6-8a9f-cac44008b395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/fieldset/div[2]/input</value>
      <webElementGuid>4b6abf6b-f8c0-48cc-ae55-6eed2659338a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3' and @name = 'UI_V_ZP_in_UdajeZamestnavatela_Nazov-control-3' and @type = 'text']</value>
      <webElementGuid>3403c5ec-acfc-4bb3-8713-f2045638da6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
