<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte kontaktn e-mailov adresu_UI_V_6695e3</name>
   <tag></tag>
   <elementGuidId>563aff49-d17f-448b-a062-15ddf05858d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_UdajeZamestnavatela_Email-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Email-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7349c359-275f-4b29-a5a4-d85eff339626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>2788473c-3b15-44d7-9c02-a986a427c3eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-control-3</value>
      <webElementGuid>03c12d7c-0378-4c44-834c-27eacd1b20e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-control-3</value>
      <webElementGuid>c70e7dad-6e1a-41a3-a0a7-7a6fc4069187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43fc607a-94ee-45ed-8dfd-d240e3646bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Email-hint</value>
      <webElementGuid>68735a82-24d3-4a2f-a492-62e5f6d375b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>879</value>
      <webElementGuid>a8781c22-39d2-4838-b957-4c9396fcc638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZamestnavatela_Email-control-3&quot;)</value>
      <webElementGuid>2127c759-6362-4f36-8468-08db15b84187</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Email-control-3']</value>
      <webElementGuid>4ba2740d-fa06-4664-b9cf-65b979f2cf0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZamestnavatela_Email-3']/input</value>
      <webElementGuid>b064c3ab-de19-4511-927e-fe1a0d02df85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div[3]/input</value>
      <webElementGuid>aa221ff9-4d99-4015-a3e2-324547376ccb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_UdajeZamestnavatela_Email-control-3' and @name = 'UI_V_ZP_in_UdajeZamestnavatela_Email-control-3' and @type = 'text']</value>
      <webElementGuid>68342db1-3426-4b29-b627-1ea1cc2a47d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
