<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ak ste uviedli v adrese ulicu je zada_fa5d3a</name>
   <tag></tag>
   <elementGuidId>72e2e2c9-39a2-4799-ab58-bb5c3c7bcb8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2356ecf5-b1a4-46fa-b632-f89ab0b27d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>dcfe8840-1e65-4dbf-983a-05d4d8290a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3</value>
      <webElementGuid>4ef85dad-acb5-4dc5-9b8b-85d7d932fab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3</value>
      <webElementGuid>4d56f12b-5542-4b95-ad70-8e1e44444f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3cd4775-ac42-4672-87e9-301699f3b363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-hint</value>
      <webElementGuid>2c5568fa-05a3-401d-8020-bb250bb4a8f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1172</value>
      <webElementGuid>3c0e6549-7bcc-4924-902b-d8b2833b5e13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3&quot;)</value>
      <webElementGuid>fc8bdf42-e31c-4cba-b15f-c9b34e828ce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3']</value>
      <webElementGuid>590367e4-0ec0-420d-9dfc-41793f025dab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-3']/input</value>
      <webElementGuid>bcb110bd-25d5-444c-b46e-45ffdabf3f49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset/div[6]/input</value>
      <webElementGuid>a6b694c1-1511-40af-a113-c303bb7ce31a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3' and @name = 'UI_V_ZP_in_AdresaZamestnavatelaSR_OrientacneCislo-control-3' and @type = 'text']</value>
      <webElementGuid>1caffd8a-9eea-4ea9-9cc0-90b517dfa3d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
