<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte orientan slo trvalho pobytu_U_0c10e3</name>
   <tag></tag>
   <elementGuidId>967b739e-f449-4512-be96-2d208a4e94f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73f0823c-21ec-40f3-95d4-51ff81fcf0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>e185dff3-aaeb-4e8e-b102-df6cb7184742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control</value>
      <webElementGuid>994a3756-de71-4f58-8692-c912f1ea0636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control</value>
      <webElementGuid>c95c5767-c418-4a35-a181-ec224ec108b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a319d1fc-6bdd-4b82-b4c2-01799f8a9d80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-hint</value>
      <webElementGuid>43e53cf0-d726-498c-8017-5175db234581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>374</value>
      <webElementGuid>7ae5d5c9-9eba-4158-8c1f-2e068c2c79eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control&quot;)</value>
      <webElementGuid>859fe4b9-f012-4471-86d2-05de3f144629</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control']</value>
      <webElementGuid>7618ec41-8989-4d0d-86f4-36cbc7e591b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaSlovenska_OrientacneCislo']/input</value>
      <webElementGuid>f58ab425-55b2-4437-8945-2713bffc27c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>fe565be0-6843-476e-b1bf-b7216bc97e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control' and @name = 'UI_V_ZP_in_AdresaSlovenska_OrientacneCislo-control' and @type = 'text']</value>
      <webElementGuid>b50382b6-0093-4474-a4ab-b0dcc03a806c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
