<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vygenerova potvrdenie_checkbox</name>
   <tag></tag>
   <elementGuidId>10487b9a-f939-41dc-a085-271193ca213e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='checkbox'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7100102-032f-4888-ae18-9de7b9b6701a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input non-template-chb</value>
      <webElementGuid>53f10aed-8779-4ba5-9a85-6ce98c45e7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1afedffc-d9e5-446f-b22d-8bc5a4dba904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2b888d4d-bca8-4c9f-8847-9a91b882e84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fadd9c90-5d30-4877-b127-067deb94adfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>857</value>
      <webElementGuid>814eafb0-c79e-4610-9001-0dd5f81bd17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavatelia&quot;)/table[@class=&quot;govuk-table&quot;]/tbody[@class=&quot;govuk-table__body&quot;]/tr[2]/td[@class=&quot;govuk-table__cell&quot;]/div[@class=&quot;govuk-checkboxes&quot;]/div[@class=&quot;govuk-checkboxes__item&quot;]/input[@class=&quot;govuk-checkboxes__input non-template-chb&quot;]</value>
      <webElementGuid>664341ae-ee15-4426-86be-fabb86872d5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='checkbox'])[2]</value>
      <webElementGuid>7954c7b9-5ce4-4f22-b216-7108224b9413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/table/tbody/tr[2]/td/div/div/input</value>
      <webElementGuid>f180e8fb-b050-4076-9013-97cfb33ff84a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div/div/input</value>
      <webElementGuid>f9e2285b-cd68-4508-8d74-55e8ce37ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'checkbox' and @type = 'checkbox']</value>
      <webElementGuid>b5b7f7b2-ce3e-46a9-ad4c-9151f5b9f56c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
