<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_De_UI_V_ZP_in_PracovnaPozicia_DatumNa_cbfb29</name>
   <tag></tag>
   <elementGuidId>e1f1ba7c-f62b-436b-8cf9-80a69ab0e722</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eeb35f4b-eaac-4bd0-92de-d7754bbdadcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>44352791-8763-4191-ab2b-8540cc174fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>d7bfb298-c99b-4533-9bd4-30297e0b831d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Uveďte dátum nástupu do zamestnania. </value>
      <webElementGuid>45810ca9-f6d5-43db-ae48-d0b06c934403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3</value>
      <webElementGuid>5d97c268-69d2-435a-af99-5a8a5720a8d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e775c06b-787a-47cd-bcfa-5e25d6230c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3</value>
      <webElementGuid>ff499d9f-e7f6-4884-81b3-919b2126c857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1207</value>
      <webElementGuid>e67c569a-3e95-4d24-96cd-374253b39ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3&quot;)</value>
      <webElementGuid>4c695a2b-ea77-4eb3-a965-9b35277d0ebf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3']</value>
      <webElementGuid>1d22a91a-e8a7-49d7-9530-afc8c3ed483c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-control-3']/div/div/input</value>
      <webElementGuid>28feb1f1-2b25-4694-a9dd-a9209bd5fb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[2]/div/div/div/input</value>
      <webElementGuid>012bd143-22ce-447c-90dc-106d61ade494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Uveďte dátum nástupu do zamestnania. ' and @id = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3' and @name = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day-3']</value>
      <webElementGuid>7c6d4b1c-b766-4514-86b8-70585ef78121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
