<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ObecMesto_UI_V_ZP_in_AdresaZamestnava_5303d2</name>
   <tag></tag>
   <elementGuidId>7cfabfa7-1256-4702-aa9d-55ecc174e42e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3d2723b8-5216-47bc-8eda-44e19c7134bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>489a5ad4-97c5-4e84-92c5-3b2c55fef560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>aabed9e2-ee0e-42c1-8ab4-1ddc70decc5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8bcdb4c2-c81c-44b7-b8d9-942532ced800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3</value>
      <webElementGuid>f35f7542-a930-4141-8da7-023ef69014ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3</value>
      <webElementGuid>1fc4b8eb-5d84-443a-a13b-43d3156df77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1156</value>
      <webElementGuid>eb077e43-799b-4482-a0e0-09fd2aec88c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3&quot;)</value>
      <webElementGuid>efb063b1-f8f5-4c68-906c-7e2be57927fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3']</value>
      <webElementGuid>8ada2ff2-4b27-4298-a89e-bb00f4f93e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-3']/input</value>
      <webElementGuid>bb559207-f295-42c1-bac5-0799808bf67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset/div[2]/input</value>
      <webElementGuid>ed80c23e-db33-438e-ba13-cc1d101aa008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3' and @name = 'UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control-3']</value>
      <webElementGuid>f8fcbce7-6ea4-4cec-84c4-926e47a88e5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
