<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_De_UI_V_ZP_in_PracovnaPozicia_DatumNa_0fb358</name>
   <tag></tag>
   <elementGuidId>71cdc717-6d54-454b-b08d-1c204608072f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e07b1c79-07b8-4cd8-8bda-ce8710b3e9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>0bb6aa2b-d990-482f-8d45-775cb2b3ff7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>f3e0fdfa-8524-40ee-b14f-043084477f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Uveďte dátum nástupu do zamestnania. </value>
      <webElementGuid>711149c1-bef9-4014-9b04-f4d0f8fd1e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day</value>
      <webElementGuid>9ae29db6-5c17-4e1a-a5b9-2375fbda40b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f0556c56-c190-4267-bf62-f761c6bcae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day</value>
      <webElementGuid>15ac7210-1d0e-465f-949a-cdf4d175b768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1680</value>
      <webElementGuid>1e9ffd38-b33f-455f-85a6-93afb252e475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day&quot;)</value>
      <webElementGuid>9325abb4-cb78-4b52-9c53-f158e78214dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day']</value>
      <webElementGuid>20ca726f-ba67-4025-810d-f11e80389238</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-control']/div/div/input</value>
      <webElementGuid>c62c8c9f-0f9b-4375-b089-6742879d704a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[2]/div/div/div/input</value>
      <webElementGuid>ab68f731-4839-46e6-b19d-4f9463f81ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Uveďte dátum nástupu do zamestnania. ' and @id = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day' and @name = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-day']</value>
      <webElementGuid>b0c73325-0df9-4404-8f8b-8b4b8cefaf7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
