<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uvete presn nzov zamestnvatea, kde pr_ffa6a4</name>
   <tag></tag>
   <elementGuidId>dabafb76-32b8-41c9-bdb1-5b03366aaad4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_UdajeZamestnavatela_Nazov-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a9d7311-a9c9-4c4e-879f-753eb2e734a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>949fc935-e45d-4147-9ffb-abb67b56f95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-control</value>
      <webElementGuid>57ba5ec5-0c22-4109-b79b-e44e46382cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-control</value>
      <webElementGuid>22c85e3f-93dd-45f3-abad-95a6bf5016fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6945512-a57d-4641-9505-d501b05ecae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_UdajeZamestnavatela_Nazov-hint</value>
      <webElementGuid>68769f9e-c537-4577-a26e-52d9bda4c39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1365</value>
      <webElementGuid>5e251c39-327e-4300-9d25-25b14816f5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZamestnavatela_Nazov-control&quot;)</value>
      <webElementGuid>2e361518-8c3f-4b0d-9cff-6340fec024b5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov-control']</value>
      <webElementGuid>7c2e3921-051e-4928-b7d0-c506a00d11a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZamestnavatela_Nazov']/input</value>
      <webElementGuid>f0b475a4-a4af-4c87-8937-0bb0c1dd1c15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/fieldset/div[2]/input</value>
      <webElementGuid>6c39a7a9-9f1c-4814-994d-567da6417f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_UdajeZamestnavatela_Nazov-control' and @name = 'UI_V_ZP_in_UdajeZamestnavatela_Nazov-control' and @type = 'text']</value>
      <webElementGuid>3113a82c-0a8d-4dfd-94e5-baecd2d58ea0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
