<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nie_typ-27</name>
   <tag></tag>
   <elementGuidId>6685746e-f658-481d-800e-06bc64b9a6ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typ-27</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typ-27']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f62f390-4eeb-4e76-ae67-2342856107bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>50dcc387-b798-4b60-b33f-218867bdd629</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typ-27</value>
      <webElementGuid>6219d027-af89-4670-b9c9-86c33ea8c5ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>e1429ec4-d036-4def-b1ba-ec113b8b1e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>918b7f38-bc1b-4771-8ca4-535f9f0fdd6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eec76954-100c-4130-8b5f-3f1a42fa45e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typ-27</value>
      <webElementGuid>030c4623-4a04-45d3-ba30-66ea8959149f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typkriteria</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>17ccf794-734a-44f0-9f1c-c99b945e3bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>conditional-napoveda-27</value>
      <webElementGuid>7bed3e36-3828-4304-a829-b2d836288a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1799</value>
      <webElementGuid>0df89169-1fdb-4b3b-b712-04b89541c594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typ-27&quot;)</value>
      <webElementGuid>355a81b9-86b3-42c2-aebb-c70a7cbbd47f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typ-27']</value>
      <webElementGuid>43e7caa1-7b2a-41d8-af34-85e9bba028d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rbSkutocnost-27']/fieldset/div/div/input</value>
      <webElementGuid>4726e167-721f-42e4-a5b1-baf3768bfffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/fieldset/div/div/input</value>
      <webElementGuid>65184f7c-037f-4aef-bd21-4daebb585ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'typ-27' and @type = 'radio' and @id = 'typ-27']</value>
      <webElementGuid>d19b6b98-57fd-4945-ac0e-58c5b7165d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
