<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Spolon vekos priloench sborov nesmie _e74e60</name>
   <tag></tag>
   <elementGuidId>8842aded-858c-4613-98ed-b26e3d09cb11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#prilohu-dolozim-v-listinnej</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='prilohu-dolozim-v-listinnej']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6acf0b23-9703-4bee-b5f9-589482da9c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>prilohu-dolozim-v-listinnej</value>
      <webElementGuid>31c618d4-f3d2-4e15-a472-7f3a5eec6f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>55e67b95-cd13-418a-a1fc-e227a3bb2863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9b12f0a4-5563-4a89-8509-1eaaa83079e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1965</value>
      <webElementGuid>d322e441-651c-46e1-b3c8-22fae01c0d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-20&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;vyber-suboru&quot;]/div[@class=&quot;govuk-form-group&quot;]/div[@class=&quot;govuk-checkboxes govuk-hint-cb&quot;]/div[@class=&quot;govuk-checkboxes__item govuk-checkboxes govuk-checkboxes--small&quot;]/input[@id=&quot;prilohu-dolozim-v-listinnej&quot;]</value>
      <webElementGuid>cda582b6-a909-4357-bb4d-0e0c5a875dce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='prilohu-dolozim-v-listinnej']</value>
      <webElementGuid>af09758b-c4a1-455d-af80-ff2ce77aca66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vyber-suboru']/div/div[3]/div/input</value>
      <webElementGuid>d1655597-934e-4355-b16c-22fa11871eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div[3]/div/input</value>
      <webElementGuid>00cce24e-8b2e-44b4-acf0-03bf608bacbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'prilohu-dolozim-v-listinnej' and @type = 'checkbox']</value>
      <webElementGuid>46ac1fd0-5424-4837-a817-5792ffc40183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
