<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte kontaktn e-mailov adresu_UI_V_aee6cc</name>
   <tag></tag>
   <elementGuidId>7bd7a3f5-c155-4b78-b2d6-6c3d53987acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Email-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4d5105fc-00e5-42d6-a275-38b89df98531</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>a135ef5d-6f96-42f5-aa09-2e264bbf3b04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      <webElementGuid>404b3378-1dd5-48b6-a0bd-f7770968337c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      <webElementGuid>f70cc955-f2e5-4a33-b06f-5d95020e06d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f3cf73f6-66d6-4634-9013-35af0bd8d0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-hint</value>
      <webElementGuid>cf987bbb-fd9c-4503-8f1d-79b0a40da050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>390</value>
      <webElementGuid>8aa2f76b-5e41-4a21-a4ee-1ce9568736a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_KontaktneInformacie_Email-control&quot;)</value>
      <webElementGuid>5cdf757c-0f41-44f3-8a2c-564611490035</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Email-control']</value>
      <webElementGuid>bce0d433-4892-47cb-a882-b0408be02643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_KontaktneInformacie_Email']/input</value>
      <webElementGuid>e55e3d30-18f4-4b1f-be0d-024d8d0f716b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[2]/input</value>
      <webElementGuid>281dbdd3-8c4f-4bef-b97b-125b01e75ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_KontaktneInformacie_Email-control' and @name = 'UI_V_ZP_in_KontaktneInformacie_Email-control' and @type = 'text']</value>
      <webElementGuid>83fd1ca8-908d-40f4-b18c-78dcc83fc3f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
