<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uvete sumu po odpotan povinnch zrokbe_b4c6aa</name>
   <tag></tag>
   <elementGuidId>3055280c-6f4e-412e-a162-4fc968d5b575</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9ee4864-e939-45f6-8ebe-6a18c7792f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>a2c4a359-4d1e-417e-956e-57c2da16f49b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3</value>
      <webElementGuid>e16c6b48-998d-4d3a-9492-baf7dc8953fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3</value>
      <webElementGuid>67aef693-96fc-49e7-8377-1a19dd7d2a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0d243f04-711d-467e-a698-5e0a2ede0b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-hint</value>
      <webElementGuid>96c982a7-5bfa-4f2c-914b-8980464bfa5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1258</value>
      <webElementGuid>4e5cdfba-f36a-4c6e-af2a-3375bc94060b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3&quot;)</value>
      <webElementGuid>0ae7fc17-4437-49e6-ab2f-17eba9bd8425</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3']</value>
      <webElementGuid>7750c739-8449-4dd0-b3e4-872149a35422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty-3']/input</value>
      <webElementGuid>9528d5dd-24af-4206-be41-9647a87e4bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[8]/input</value>
      <webElementGuid>25752893-535e-464c-92c0-952c9bf03d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3' and @name = 'UI_V_ZP_in_PracovnaPozicia_PlatCisty-control-3' and @type = 'text']</value>
      <webElementGuid>5c29a735-2b0a-4789-8a7f-3f16c1f0d304</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
