<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte orientan slo, kam bude v prpa_557c52</name>
   <tag></tag>
   <elementGuidId>ff3d63f5-ed82-4791-8876-36c775797c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>779f6118-9309-480e-85a3-ca78d1ce01b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>a0dd7d4f-c260-43ca-8e91-5b409fee98ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control</value>
      <webElementGuid>0b814a87-0cda-4481-8d53-74f8e252e636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control</value>
      <webElementGuid>f82c9019-1c81-4ba6-b7d2-2f124aabecd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e0b395e2-6408-48f4-a8e8-5a9d85c7000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-hint</value>
      <webElementGuid>6dae9a91-fbce-454d-8345-f57fcea65211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>724</value>
      <webElementGuid>323bbecf-6f92-4136-b69c-0ea87d0caa5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control&quot;)</value>
      <webElementGuid>613adf94-3765-4e89-bc24-90cb5a86d624</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control']</value>
      <webElementGuid>c5fa37c5-6b84-47c1-9060-558f9a5db0d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo']/input</value>
      <webElementGuid>7ffc1568-c02b-46dd-b430-3f8a51e5b276</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/fieldset/fieldset/div[5]/input</value>
      <webElementGuid>8301bcbd-ec08-4946-9732-b646adb828f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control' and @name = 'UI_V_ZP_in_AdresaKorespodencnaSlovenska_OrientacneCislo-control' and @type = 'text']</value>
      <webElementGuid>21194d6d-2881-45af-a315-92ba7d51e609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
