<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poloka mus by vyplnen_UI_V_ZP_in_Prac_84127b</name>
   <tag></tag>
   <elementGuidId>43f9d6a1-5d32-4e91-a050-2f76d74d9680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f149957-2ae2-4d81-bb8b-e6b4154e9038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>ec414bc0-afc8-4444-931b-830754ac84ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1</value>
      <webElementGuid>38a74d86-162d-4d6c-9b0e-d16e44fe34e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-group</value>
      <webElementGuid>f5c8cfb9-f2ec-4928-8ee9-a1879c065314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>67edfe91-1010-42c0-857e-2c51e5a04e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a693afec-bc5d-427a-958f-53665495e37b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1243</value>
      <webElementGuid>60b028ad-dbde-4a74-bdec-41178d3a9647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1&quot;)</value>
      <webElementGuid>91829ca9-afe5-47b9-b8be-f454d3a9de96</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1']</value>
      <webElementGuid>6ea51366-033f-45e2-8313-41d976f5c015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_DruhZmluvy']/fieldset/div/div/input</value>
      <webElementGuid>729a46c3-6c48-4153-89a2-5cc9bf6303b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/fieldset/div/div/input</value>
      <webElementGuid>ed310dfa-411b-4d51-8b9c-ec010e556f81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-input-1' and @name = 'UI_V_ZP_in_PracovnaPozicia_DruhZmluvy-group' and @type = 'radio']</value>
      <webElementGuid>e7ee86ba-a411-4dba-bb8c-2ce4546986dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
