<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte potov smerovacie slo_UI_V_ZP__de53d1</name>
   <tag></tag>
   <elementGuidId>231f45e5-189f-4b35-80df-bd1962350a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc4f2590-b480-4111-8036-8b435b2d2f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>8158677c-86cb-4a44-ac66-3cd19a6342bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3</value>
      <webElementGuid>552decac-74d0-4ea9-a89a-5bb9e17eebea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3</value>
      <webElementGuid>a60b3cc1-127c-4794-bef1-d1d79bd066a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79f11d2b-83ba-45de-9189-26d638be5396</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-hint</value>
      <webElementGuid>7262bd56-0ab2-43e0-9a6d-41fb98116e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1176</value>
      <webElementGuid>2d7512c9-07a7-47d7-b1d8-ee8f3fe1ee06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3&quot;)</value>
      <webElementGuid>98bfcf91-f6e6-460b-a924-5921eccc4138</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3']</value>
      <webElementGuid>a1de0e5f-62e7-46ed-8a36-0f4eaeb0ae2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-3']/input</value>
      <webElementGuid>180dab71-552b-47fc-91f4-5dface0f849b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset/div[7]/input</value>
      <webElementGuid>0ed30b32-e494-418f-8fa2-c4e3cb9e8194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3' and @name = 'UI_V_ZP_in_AdresaZamestnavatelaSR_PSC-control-3' and @type = 'text']</value>
      <webElementGuid>84a24a56-0e00-4cfe-bb1e-238179d39689</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
