<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte obec alebo mesto, kam bude v _9b039a</name>
   <tag></tag>
   <elementGuidId>153131ed-4b3c-43dc-9f86-297205f6383a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68e4f176-3e8a-4df0-ad01-432e0db45190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>75d97db5-9004-42f2-8d00-272463c6202e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>fe52dfd4-f8a1-48e0-950e-4923ab5b1eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cc4bc501-36ef-4efa-ba6e-0b43ae25f7a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control</value>
      <webElementGuid>adf8fd6a-b2bd-4542-9126-efb926724705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control</value>
      <webElementGuid>2c3db147-f1c6-4af7-8969-a27b7ddb3607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>440</value>
      <webElementGuid>a380d4d2-62f9-45da-9e9b-e5a05552f28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control&quot;)</value>
      <webElementGuid>f380242c-041c-4dad-b573-4a35de22cf0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control']</value>
      <webElementGuid>a4ae4ba7-884f-4952-9329-6745c58402d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec']/input</value>
      <webElementGuid>1656d301-5493-48dd-9767-dbde05a60d55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/fieldset/fieldset/div/input</value>
      <webElementGuid>a26d8735-7832-4696-9812-2fa9da570336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control' and @name = 'UI_V_ZP_in_AdresaKorespodencnaSlovenska_Obec-control']</value>
      <webElementGuid>7644c98c-842c-4b31-bfda-ef3ea260c726</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
