<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nie_typ-29</name>
   <tag></tag>
   <elementGuidId>f30e721a-cae1-41a5-be01-acd708842caa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typ-29</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typ-29']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f52dfa6c-f454-48c1-8ecd-0ff127015b82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>277df1b9-622d-412d-a67a-288ba00791d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typ-29</value>
      <webElementGuid>f852b9de-535a-4a9f-9094-7e5c21f31577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>18bba2ef-0634-490e-9f13-b2a9d693f72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>abdfd8bc-f599-4080-963a-f7acfb2204bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ee144617-7218-43ec-b197-0639915356bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typ-29</value>
      <webElementGuid>ca1b6954-4a49-4a19-9c4e-2840d7a8ac2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typkriteria</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>4762c2c6-ec42-4764-8737-093bf769865d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>conditional-napoveda-29</value>
      <webElementGuid>6a7ee170-48da-493a-8322-3856efdb3748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1817</value>
      <webElementGuid>30f83ab2-5bc8-4fa1-837b-fafafeecb229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typ-29&quot;)</value>
      <webElementGuid>76f447e2-b9ae-4212-8b5e-3691f3a3a232</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typ-29']</value>
      <webElementGuid>5107b62d-4047-4db3-9f1b-321042301ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rbSkutocnost-29']/fieldset/div/div/input</value>
      <webElementGuid>a276ac31-0220-46cc-aeff-bd10135dccbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[7]/fieldset/div/div/input</value>
      <webElementGuid>ad1b626c-12a4-46c6-a19c-bd7ab89cd779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'typ-29' and @type = 'radio' and @id = 'typ-29']</value>
      <webElementGuid>d24ef814-f6fb-4dd1-9e3a-76369d3e9084</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
