<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poadovan vka piky (zaokrhlene na stov_c8e10c</name>
   <tag></tag>
   <elementGuidId>fdfd6ef8-4478-495a-acbe-f74ea8205680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9568927f-6479-4fdf-8f9a-eb11d4370e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>b0167be8-026d-46fa-95a5-fce584f62506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control</value>
      <webElementGuid>f1bb57e4-eb6b-45c0-aa6c-2c3a412a556d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control</value>
      <webElementGuid>171a1cb3-b868-4327-a26c-4e5f3b7eb46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c35c62c3-71d3-4d1d-aa32-915c0230d16a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>874faed3-9be2-4b12-a99e-bf3ada35b343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-hint</value>
      <webElementGuid>cc496a3f-2284-4031-b85c-5dd52bf546c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>803</value>
      <webElementGuid>9859840a-c712-4d06-be27-d9cf5cddfa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control&quot;)</value>
      <webElementGuid>9e719aa8-c55a-49da-8e52-6b39edf47fba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control']</value>
      <webElementGuid>288abc0f-e23c-4133-bb01-5c57bdedb199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky']/input</value>
      <webElementGuid>2fc4b700-b02f-4bbb-b9bd-ee16baffb215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/input</value>
      <webElementGuid>da401b09-351c-41ab-acb7-b90559fb6709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control' and @name = 'UI_V_ZP_in_VyskaLehotaPozicky_VyskaPozicky-control' and @type = 'number' and @title = '.']</value>
      <webElementGuid>9596714b-0247-4f89-9159-c9417b845ce2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
