<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vyhadajte obec po zadan prvch 3 znako_4b7030</name>
   <tag></tag>
   <elementGuidId>a6a9b9b0-0604-457a-8104-db98678e7afc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0a35e59-7ab3-4500-be05-0e739adc2063</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>83a10a8a-6cb2-45a9-9efd-490a60e6d31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>b84ce216-eccc-4b79-ac2d-584aed93a206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>78767da4-f1ae-463b-a423-139a4cee0578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control</value>
      <webElementGuid>7dc640c7-e599-4d33-b610-6686e68ee7bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control</value>
      <webElementGuid>fdaacabf-5ccd-431d-9658-bb2e8060e2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1630</value>
      <webElementGuid>1bf507a3-8bb5-401a-900b-9d3e34f9373a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control&quot;)</value>
      <webElementGuid>b436b85c-ddfd-46f0-baf1-768d82540355</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control']</value>
      <webElementGuid>e1d8af2f-6c1e-442b-9413-6a17b63c001d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaZamestnavatelaSR_Obec']/input</value>
      <webElementGuid>07fd3bba-c2bf-43c6-bd81-9486490d4dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/fieldset/fieldset/div[2]/input</value>
      <webElementGuid>9b948490-80f6-4f82-a040-8c2cf01f75d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'search' and @id = 'UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control' and @name = 'UI_V_ZP_in_AdresaZamestnavatelaSR_Obec-control']</value>
      <webElementGuid>f3a33aef-0334-4962-9e1a-ef523602ee0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
