<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_doktorand v dennej forme tdia_UI_V_ZP_9333fb</name>
   <tag></tag>
   <elementGuidId>c73c31e3-b359-40d3-9ae5-79f7a8201b94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5175ea8-0a60-41ff-8fa9-4c0a3209b558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>c961d93a-385a-4d88-9aa5-079c5b4cde24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control</value>
      <webElementGuid>0e4de07f-08d4-483b-a80b-b3e7af61e21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control</value>
      <webElementGuid>bb889577-bf2e-4ca4-a15c-372a15a094e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>21cf5cf1-ac28-4d72-82dc-56bb524670c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a42559d3-8db4-45c7-8599-8b37d3e79bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>764</value>
      <webElementGuid>fc4e2504-f2d6-4ff5-905f-58289397df8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control&quot;)</value>
      <webElementGuid>5bdeb839-9994-4f1b-989a-9fa17b4e556a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control']</value>
      <webElementGuid>7fa16af2-2a0f-4e70-86d2-37a622ad4d68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel']/div/div/input</value>
      <webElementGuid>7c72f995-468f-4168-ab74-ae4f44d9afe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>c7d224e1-17e8-4034-9368-af8507864632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control' and @name = 'UI_V_ZP_in_ZaradenieZiadatela_VysokoskolskyUcitel-control' and @type = 'checkbox']</value>
      <webElementGuid>d05a6c37-02dd-4fc0-ad50-a1de06a56b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
