<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vyberte minimlne jednu, alebo viac mo_efdf69</name>
   <tag></tag>
   <elementGuidId>4a045698-c94d-4c15-bebd-9573373813d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63f08af9-64fd-4577-8eb3-e7c73f4f033f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>6d8a1cd7-b4bb-4f56-8807-c8b5c90f2d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3</value>
      <webElementGuid>430ffab1-c2a6-4ae4-89e2-c82212243765</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3</value>
      <webElementGuid>989bbb53-65ac-445b-ad97-115c9f214098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>482fcf67-f588-4dc7-8276-6934fa44ba49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d7918c35-8ed7-4271-9ad3-ebe2e64986c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1211</value>
      <webElementGuid>261c0c57-92e7-4674-a57a-7b925f1aeef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3&quot;)</value>
      <webElementGuid>ed8ccc5f-0a70-42d4-8068-76907d53c32c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3']</value>
      <webElementGuid>04657136-21af-4d1d-a033-eb77d2070607</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-3']/div/div/input</value>
      <webElementGuid>bf821af4-63ee-419e-a39e-177c1dfb70b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[3]/div/div/div/input</value>
      <webElementGuid>9ad5493f-86b2-4282-a5f5-94debf748aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3' and @name = 'UI_V_ZP_in_PracovnaPozicia_PedagogickyZamestnanec-control-3' and @type = 'checkbox']</value>
      <webElementGuid>5e674f9a-8762-4dbe-ac19-65050b497e18</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
