<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte najvy zskan titul (v prpade v_aad6cd</name>
   <tag></tag>
   <elementGuidId>a161b23a-77f3-4005-b151-4f35857d6af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_IdentifikacneUdaje_Titul-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_IdentifikacneUdaje_Titul-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d3fe9716-f8cb-45a6-8ed0-f0b3e3a510c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>e18c6fcc-9c0b-4af0-be70-e3986b962bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_IdentifikacneUdaje_Titul-control</value>
      <webElementGuid>dcbe4490-2bdf-4ec5-a24c-5d9ede80e1b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_IdentifikacneUdaje_Titul-control</value>
      <webElementGuid>61005da5-d507-4856-ba34-1646d981c71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a794a4b3-c529-4a8c-94d3-050c92b4c59e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_IdentifikacneUdaje_Titul-hint</value>
      <webElementGuid>54d0837f-e111-47b6-827c-648870f60a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>59</value>
      <webElementGuid>14eb7820-0b0d-4727-a23c-ebb054e4e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_IdentifikacneUdaje_Titul-control&quot;)</value>
      <webElementGuid>6684902e-8597-489f-9ad9-b16da1a3df1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_IdentifikacneUdaje_Titul-control']</value>
      <webElementGuid>9fc3d649-3ab4-4f83-a8d5-e439cdae8ded</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_Titul']/input</value>
      <webElementGuid>c8a779c3-66a9-4317-a9b9-855ea8d6391f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5d4e0d88-208b-4001-8794-193f64af4c08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_IdentifikacneUdaje_Titul-control' and @name = 'UI_V_ZP_in_IdentifikacneUdaje_Titul-control' and @type = 'text']</value>
      <webElementGuid>2298bfd7-9f39-477b-9207-9f31fd38a005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
