<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poloka mus by vyplnen_UI_V_ZP_in_Prac_cae66d</name>
   <tag></tag>
   <elementGuidId>771253ab-61db-4c02-84fa-b486db50137a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_PlatCisty-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c95c389-6266-44ca-9934-bc063071b129</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>afd7cf04-13d2-403d-b847-7b7a10d6e4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-control</value>
      <webElementGuid>b0299180-d041-471e-9ad2-014a70035f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-control</value>
      <webElementGuid>8b13c7be-5715-433e-bab4-2713139c8ff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0ff65c96-108c-406f-b5b3-a0a764afd3a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatCisty-hint</value>
      <webElementGuid>6b297dd2-dd36-43fb-bb1a-2103c4fb2500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1735</value>
      <webElementGuid>e2dcab21-9c08-49b3-95c4-bf6981e13b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_PlatCisty-control&quot;)</value>
      <webElementGuid>2033e0b8-d63f-4270-8607-9ab0494d5950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty-control']</value>
      <webElementGuid>62a14df3-5f2e-42c9-880d-e8efebbebe4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_PlatCisty']/input</value>
      <webElementGuid>f7ac3316-5545-43a6-affa-3ebca9900d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/input</value>
      <webElementGuid>423dd77d-91e9-4d72-a6d1-59b61712dfd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_PracovnaPozicia_PlatCisty-control' and @name = 'UI_V_ZP_in_PracovnaPozicia_PlatCisty-control' and @type = 'text']</value>
      <webElementGuid>eb01b899-ac1e-4454-bc75-8a274f1532e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
