<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mesiac_UI_V_ZP_in_PracovnaPozicia_Dat_82fcb9</name>
   <tag></tag>
   <elementGuidId>d89af400-b435-4fb6-8bc6-28c073b95fae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4657e5b1-aca7-412a-80f1-c35666c14691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2619fd89-680f-4135-b7d4-6036c9d4b904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>2ccffb4d-f227-4253-8ed7-b51d43603484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Uveďte dátum nástupu do zamestnania. </value>
      <webElementGuid>7eb3fc70-526e-4bc3-978a-6f702a4bbdfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3</value>
      <webElementGuid>76d43010-5b98-49cb-974a-868aa5cac34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e3d9c1c8-958a-463b-a358-bad7a70b3d16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3</value>
      <webElementGuid>5f7820e2-5f3b-4a0d-8878-133d35a5c5f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1206</value>
      <webElementGuid>dd0a65eb-70c4-4fe2-8186-9821d26bde0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3&quot;)</value>
      <webElementGuid>1d637fce-c890-4394-a985-0d102eb6f97f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3']</value>
      <webElementGuid>0ea72034-6b02-42b2-80fd-6aa0d658b9bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-control-3']/div[2]/div/input</value>
      <webElementGuid>cd8a7bfe-5a91-4ccf-a9f5-6730dea8af05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[2]/div/div[2]/div/input</value>
      <webElementGuid>cc9d41dd-193e-4833-80e3-5a55ae981f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Uveďte dátum nástupu do zamestnania. ' and @id = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3' and @name = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-month-3']</value>
      <webElementGuid>b8c38409-c638-4efd-8686-2838d376df53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
