<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vyberte minimlne jednu, alebo viac mo_04f0d9</name>
   <tag></tag>
   <elementGuidId>7f766bf2-221f-466f-9fb4-5dfca313131b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf77e9e5-b9c5-41cb-88a7-27dcca693e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fce07476-0162-4749-97b7-c1ec15743ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>10e84cbd-f90a-4393-8efe-3b640384dbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control</value>
      <webElementGuid>df447cf4-b6b2-462c-8d40-a4501b8e57e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control</value>
      <webElementGuid>47f345fc-526f-4898-ab17-fb6a0af9ada8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>59dafe65-c0e6-4a23-b5cd-1d76c599bab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>757</value>
      <webElementGuid>d82c1564-4c83-4e39-9180-23870388af05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control&quot;)</value>
      <webElementGuid>239ff804-081b-43dc-9811-db4d5182cb24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control']</value>
      <webElementGuid>82545e52-9eaa-48de-a7d4-ae39844c3c17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec']/div/div/input</value>
      <webElementGuid>dbba5bff-3740-4de5-84b9-282a1a3df919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[6]/div/div/div/div/input</value>
      <webElementGuid>5b9a66a6-a863-4eb6-a892-855af41dcd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control' and @name = 'UI_V_ZP_in_ZaradenieZiadatela_PedagogickyZamestnanec-control' and @type = 'checkbox']</value>
      <webElementGuid>db81e0dd-3834-4b4d-aedb-931795d36b44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
