<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte miesto odoslania iadosti_UI_V_59ba54</name>
   <tag></tag>
   <elementGuidId>ec16e9fd-b43d-49bf-b000-823db1e216b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bff41b3b-d68a-4cc3-862b-06601672f3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>0feac161-248a-4b1f-b9e4-1f632cee1b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      <webElementGuid>8872d9aa-2435-4069-a25d-7b9cb3aa06a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      <webElementGuid>b2cee2c3-9dba-4bc9-851d-e021dae02932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bc4b389b-0674-4550-996c-88bf6e0f7398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-hint</value>
      <webElementGuid>b559027c-4f3c-4ddf-baad-55504a995dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1937</value>
      <webElementGuid>4b04912d-1807-4933-8022-21fd410b1aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control&quot;)</value>
      <webElementGuid>d9aae421-f43a-420a-a0e9-7ae949201f0e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control']</value>
      <webElementGuid>e7ce24c6-654d-47cb-b267-9f7f6b53645b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania']/input</value>
      <webElementGuid>87e94163-c624-4178-83db-98e8dd319788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/fieldset/fieldset/div/input</value>
      <webElementGuid>db5f1288-505f-46f4-8d56-83ff6598324e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control' and @name = 'UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control' and @type = 'text']</value>
      <webElementGuid>beb58ba1-7075-4581-a307-d8189258faf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
