<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_no_UI_V_ZP_in_AdresaSlovenska_ZhodaAd_32b5fe</name>
   <tag></tag>
   <elementGuidId>270039b1-ad18-43c1-bcb2-0e1045f6ac77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>af36d9a4-8633-4967-bce8-7ffe445d1740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>c1e3089d-246f-492e-abdd-01c3b5465651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2</value>
      <webElementGuid>844bd1cc-b04f-452e-97c2-bc1d62747d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-group</value>
      <webElementGuid>b1a64a79-8857-4917-ae58-5f184230f9cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b2fd938d-0454-4109-82e3-1dc4e75fafc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2577600d-74c5-4f18-bd0a-313f2f93035c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>380</value>
      <webElementGuid>e411a67d-f59b-440f-8250-bd75f5121e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2&quot;)</value>
      <webElementGuid>13eaff09-b4df-4a5c-b00f-c627246e488b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2']</value>
      <webElementGuid>02adbbf7-383e-4d80-b99b-4f4975400c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy']/fieldset/div/div[2]/input</value>
      <webElementGuid>fd7386ae-bfb3-43a2-8037-a0966e65f8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/fieldset/div/div[2]/input</value>
      <webElementGuid>1235cdb4-3ee1-4b47-9157-f358612fbf5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-2' and @name = 'UI_V_ZP_in_AdresaSlovenska_ZhodaAdresy-group' and @type = 'radio']</value>
      <webElementGuid>90af592a-23c4-4129-a761-906e9e8af827</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
