<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Poloka mus by vyplnen_UI_V_ZP_in_Prac_796394</name>
   <tag></tag>
   <elementGuidId>1652c057-e3ba-4fe2-97c5-170ca8eebece</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_PlatHruby-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatHruby-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51b5af95-fc17-40fb-87d7-287595df78c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>ebf068ea-f209-46fc-abc2-7edfcfda394a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatHruby-control</value>
      <webElementGuid>dcf60f2b-85ce-4dea-a5f3-d19dc8fb5f61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatHruby-control</value>
      <webElementGuid>052c8145-ffed-45c0-a86a-4751740cd77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b0e65eb-0396-4631-bc8b-093fe6d0c700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_PlatHruby-hint</value>
      <webElementGuid>f8ea5c24-93fb-481f-a182-ac961f274643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1731</value>
      <webElementGuid>689530b0-fe3f-41e0-80fe-4cf1debbb814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_PlatHruby-control&quot;)</value>
      <webElementGuid>6f1c3ca4-c9fa-4d5e-b33d-e9bac987dd84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_PlatHruby-control']</value>
      <webElementGuid>ad3184d5-63ad-4b93-8ee1-f73778f20211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_PlatHruby']/input</value>
      <webElementGuid>bc6cc17d-b33f-4500-82dd-85fae4a08649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div[7]/input</value>
      <webElementGuid>433c4c91-0e3d-40e8-9794-2d34617477f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_PracovnaPozicia_PlatHruby-control' and @name = 'UI_V_ZP_in_PracovnaPozicia_PlatHruby-control' and @type = 'text']</value>
      <webElementGuid>bad241d4-81b7-4383-9a73-5b70d61e11e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
