<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tabuka zamestnvatelia Riadky . 1, 2 s_5c0fce</name>
   <tag></tag>
   <elementGuidId>8db99cfa-960c-4af7-a495-610bc368b2bb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chb-all&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='chb-all']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd1b695b-4317-4670-a53d-11186a2748f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>4fbf89eb-1a55-46c8-97f6-95ea22e7d0e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chb-all</value>
      <webElementGuid>5ce52873-3416-4b2c-b716-b14958db6cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>406297dd-e86f-419f-abc3-e4349aa254d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1320</value>
      <webElementGuid>b643d0e2-a297-4f40-92ea-7afcfee1e746</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavatelia&quot;)/table[@class=&quot;govuk-table&quot;]/thead[@class=&quot;govuk-table__head&quot;]/tr[1]/th[@class=&quot;govuk-table__cell&quot;]/div[@class=&quot;govuk-checkboxes&quot;]/div[@class=&quot;govuk-checkboxes__item&quot;]/input[@class=&quot;govuk-checkboxes__input&quot;]</value>
      <webElementGuid>b61f3825-59ea-431e-a824-51ca3a772ad9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chb-all']</value>
      <webElementGuid>0e7455ef-7b51-4fca-a395-374f0a26e763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/table/thead/tr/th/div/div/input</value>
      <webElementGuid>f754b770-4ac9-4af0-b5e0-33945bd2eab9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/div/input</value>
      <webElementGuid>95cfcb9f-d273-4fa8-8b23-7d39ae4f2fcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'chb-all' and @type = 'checkbox']</value>
      <webElementGuid>d33a6bbd-9616-4826-bc4c-ef4d1ebe47b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
