<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rok_UI_V_ZP_in_PracovnaPozicia_DatumN_22e03d</name>
   <tag></tag>
   <elementGuidId>8383bc63-f70b-4947-9e4b-adb5c023210e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f255a5cd-f4e7-4819-90e9-18121144f3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d8fcac78-ccc0-4f5a-8005-08294364996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-4</value>
      <webElementGuid>04a6343b-57d6-4c2c-88b5-bb64fdfa828c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Uveďte dátum nástupu do zamestnania. </value>
      <webElementGuid>ae99bcdd-85f0-4fd3-bfad-e581a1faee22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3</value>
      <webElementGuid>c180a60d-b5db-4638-a90f-ce0f7d65ae59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>2ff5735c-25e3-409e-a674-e4c57ce3f31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3</value>
      <webElementGuid>b2abd925-bc5e-44d7-beaa-9dad247187c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1208</value>
      <webElementGuid>1d4ca848-9a55-4d02-9aeb-0cf7adb3b114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3&quot;)</value>
      <webElementGuid>0c396fff-8827-4ca6-af6d-cf18a25c6d68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3']</value>
      <webElementGuid>06a93736-3699-4f9c-a080-4ab69b7730bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_DatumNastupu-control-3']/div[3]/div/input</value>
      <webElementGuid>90a9d4b5-6bf7-4c00-8433-5e22f3718e5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[2]/div/div[3]/div/input</value>
      <webElementGuid>b3e87dd4-2152-436d-b2b4-1d69d1735b13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Uveďte dátum nástupu do zamestnania. ' and @id = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3' and @name = 'UI_V_ZP_in_PracovnaPozicia_DatumNastupu-year-3']</value>
      <webElementGuid>c6d41b99-47b1-4fc0-abc6-95bbb1604b2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
