<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Uloi_file-upload-field</name>
   <tag></tag>
   <elementGuidId>9f08a93e-d007-484d-8e0f-ca1b642bc39e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;file-upload-field&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='file-upload-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4f4aad6e-506f-4eea-a42f-5f67889fd28e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file-upload-field</value>
      <webElementGuid>babbcd79-acd7-412f-aa90-fb2aefdd02fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>47d3d2c4-f3a5-420b-920e-d1ea73a139f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>application/x-7z-compressed, application/vnd.etsi.asic-e+zip, application/vnd.etsi.asic-s+zip, image/bmp, text/csv, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/x-eform-xml, image/gif, application/gzip, text/html, text/html, image/jpeg, image/jpeg, application/vnd.oasis.opendocument.spreadsheet, application/vnd.oasis.opendocument.text, application/pdf, image/png, application/vnd.rar, application/rtf, image/svg+xml, application/x-tar, image/tiff, image/tiff, text/plain, application/xhtml+xml, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/xml, application/x-xades_zep, application/zepx, application/x-xades_zep_data_signatures, application/x-zipzepf, application/zep, application/zip</value>
      <webElementGuid>5cf03de0-362a-423c-8e97-003ac3de5313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button govuk-!-margin-top-4 file-upload-field</value>
      <webElementGuid>eb7d82d5-e58d-43d7-9930-1c1e483fa731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1870</value>
      <webElementGuid>16077d6c-6aea-4552-93c3-457b20beb0e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-19&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;vyber-suboru&quot;]/div[@class=&quot;govuk-form-group&quot;]/div[1]/div[@id=&quot;nahrat-prilohu&quot;]/input[@class=&quot;govuk-button govuk-!-margin-top-4 file-upload-field&quot;]</value>
      <webElementGuid>bb450c2d-0956-45a9-8c72-fe0f48758860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='file-upload-field']</value>
      <webElementGuid>748b9161-41c8-42a2-a74e-5c65adae73c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nahrat-prilohu']/input</value>
      <webElementGuid>7f590806-f482-4050-8c6b-cb2d568f5f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/fieldset/div/div[2]/div/div/div/input</value>
      <webElementGuid>b0bdfe0b-5cd7-47de-9090-74922131ec13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'file-upload-field' and @type = 'file']</value>
      <webElementGuid>6f45adec-8a92-4549-87ff-bfd0741c649d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
