<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_urit</name>
   <tag></tag>
   <elementGuidId>6f987d8d-dc4e-4fc8-aa06-3ed1256aa149</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_TypZmluvy']/fieldset/div/div[2]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c6129f64-e0b0-4e31-ba90-1a8c03f2d9c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-label govuk-radios__label</value>
      <webElementGuid>9adbb503-1119-41f6-b5b2-5e8e915687a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vyberte jednu z možností. </value>
      <webElementGuid>59040dad-cbf8-43a9-bec4-8c7598c5eb98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>UI_V_ZP_in_PracovnaPozicia_TypZmluvy-input-2</value>
      <webElementGuid>f9c6b1e3-acd1-43af-acf9-678796cd15df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1722</value>
      <webElementGuid>f444b173-54c6-4656-8930-1d7dc874c97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>určitú</value>
      <webElementGuid>d0873ef7-33ba-4bbf-a8ed-ae1d26d1c0ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_PracovnaPozicia_TypZmluvy&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;govuk-radios govuk-radios--inline govuk-radios--conditional&quot;]/div[@class=&quot;govuk-radios__item&quot;]/label[@class=&quot;govuk-label govuk-radios__label&quot;]</value>
      <webElementGuid>287293c8-484c-422c-85b6-b496f5b84cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_PracovnaPozicia_TypZmluvy']/fieldset/div/div[2]/label</value>
      <webElementGuid>0ee5e3ee-b1cb-4a59-a5b9-400336e8cfc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='neurčitú'])[1]/following::label[1]</value>
      <webElementGuid>fa8b4f6d-94c8-4b2a-9df7-9fa113508816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Položka musí byť vyplnená!'])[3]/following::label[2]</value>
      <webElementGuid>22cfa8a0-7a01-4f1c-862d-117c3f9a4630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dátum ukončenia pracovného pomeru'])[1]/preceding::label[1]</value>
      <webElementGuid>3f9835d1-a576-448b-a06c-6f9a4273789f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte dátum.'])[1]/preceding::label[2]</value>
      <webElementGuid>3f53e740-f9b9-4101-9d11-02b185a4abca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='určitú']/parent::*</value>
      <webElementGuid>bd9770a2-a397-4f0e-ac7c-4df9745059a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/div[2]/label</value>
      <webElementGuid>245c88a0-8e1e-4707-aab8-3a039fbc492b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = 'Vyberte jednu z možností. ' and (text() = 'určitú' or . = 'určitú')]</value>
      <webElementGuid>54b75d38-c6a7-461d-a8dc-95508f4fb6d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
