<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Stredn odborn kola technick, Koice 1, Koice</name>
   <tag></tag>
   <elementGuidId>0e34bfdb-16c9-4cd5-8c79-bc345509e04b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@name='NazovZamestnavatela'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5c52c60-2e35-4d1e-873f-c61fa022b8a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NazovZamestnavatela</value>
      <webElementGuid>4d7a91de-0c9a-43ce-b7c8-67df2507ae75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>847</value>
      <webElementGuid>438cfb9c-dc0b-4cf2-9b68-fc7b78e89713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Stredná odborná škola technická, Košice 1, Košice</value>
      <webElementGuid>c66dbebb-c5b5-450f-9e59-865fe62b6e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavatelia&quot;)/table[@class=&quot;govuk-table&quot;]/tbody[@class=&quot;govuk-table__body&quot;]/tr[3]/td[@class=&quot;govuk-table__cell&quot;]/span[1]</value>
      <webElementGuid>e72e90e5-cdff-418f-9a7b-9d2683d9df52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@name='NazovZamestnavatela'])[3]</value>
      <webElementGuid>8bdc73b6-3919-4e80-a1a2-5102def80e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/table/tbody/tr[3]/td[3]/span</value>
      <webElementGuid>8800a375-e9a4-48dc-9432-16ce6dad114a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[2]/following::span[2]</value>
      <webElementGuid>ae65b793-22a1-4aa0-b4a9-7e26b0db49f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stredná odborná škola Policajného zboru Košice, Košice-Juh 1, Košice'])[1]/following::span[2]</value>
      <webElementGuid>2a038664-d878-49ee-be21-1b9a8e46b620</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[3]/preceding::span[1]</value>
      <webElementGuid>97dbb0f4-1532-4861-9927-b223222729b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pridať'])[1]/preceding::span[1]</value>
      <webElementGuid>da23d8e5-8c15-4d6e-8c6d-e1eca87ec3f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Stredná odborná škola technická, Košice 1, Košice']/parent::*</value>
      <webElementGuid>81b36bd5-2864-42af-9ef0-c5648cedeb59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/span</value>
      <webElementGuid>303bb9dd-eeaa-4424-8f7e-3c34e6fb320e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'NazovZamestnavatela' and (text() = 'Stredná odborná škola technická, Košice 1, Košice' or . = 'Stredná odborná škola technická, Košice 1, Košice')]</value>
      <webElementGuid>567fe5e3-0ac4-4323-9356-4ebc83b84af1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
