<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_01.01.1980</name>
   <tag></tag>
   <elementGuidId>cb4693db-ce45-48a3-8895-f0a1cb817f47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia > label.govuk-label.bold > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bee66938-e678-412a-8c2d-389c6f015842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>99daa967-e7de-40a8-914c-2e68956295c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>61</value>
      <webElementGuid>201af8d6-c983-4d68-8752-2362b59c4b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01.01.1980</value>
      <webElementGuid>adb657c3-40a9-4588-a6ad-716fbd340de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>d581618f-d766-42ad-94bf-f5122896ee31</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia']/label/span</value>
      <webElementGuid>2d745155-21fc-454c-8ac5-69383fcc973b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[1]/preceding::span[3]</value>
      <webElementGuid>519cdade-288f-4b00-af06-2100306a101d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[1]/preceding::span[5]</value>
      <webElementGuid>6f12ece5-c0e4-4e5f-bb28-9fadc4ff3376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01.01.1980']/parent::*</value>
      <webElementGuid>891f7759-72ab-4988-b8dd-07b02c37c586</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label/span</value>
      <webElementGuid>e1bddb79-a011-4858-9611-2adb36a57b3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '01.01.1980' or . = '01.01.1980')]</value>
      <webElementGuid>5220880a-6ac5-4479-9fc6-a6e383d7f539</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
