<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2188</name>
   <tag></tag>
   <elementGuidId>a3020d9a-780d-4a28-b130-9daf4d5df614</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_P_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9b3690bb-abb9-424b-8159-c86d996c9eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>ffca8421-dd02-4a1d-9d05-ccfbf51059e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>cf64c950-5c3a-4382-be82-1fd3b832319d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2188</value>
      <webElementGuid>2dbee264-3de4-4d7d-9e63-cc41dcb460a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_P_ZP_in_UdajeZiadosti_IdentifikatorPodania&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>ef6f2f75-e544-45aa-8bca-e70332a0aa26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_P_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      <webElementGuid>027c2743-7552-4efc-b438-d529abc0427c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pri vypĺňaní sa vyskytli nasledovné problémy'])[1]/following::span[1]</value>
      <webElementGuid>a2a11f5a-392a-4ce3-8cf8-50474d055b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje žiadateľa'])[2]/preceding::span[6]</value>
      <webElementGuid>67cefc96-32c6-4cf4-b85c-dca9acddf988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2188']/parent::*</value>
      <webElementGuid>00c6d3ea-e18c-444c-8640-5977554a1dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>508ac920-3726-401e-92f7-e420f467325a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ESRVS-2024-2188' or . = 'ESRVS-2024-2188')]</value>
      <webElementGuid>2992ffb4-3f8a-482c-afdd-06b753a785c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
