<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_2</name>
   <tag></tag>
   <elementGuidId>46f8196a-4d44-42eb-b4ed-50027a956fe1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@name='PorCislo'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1455f5ec-c3f6-44d0-9675-388859d6a42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PorCislo</value>
      <webElementGuid>0cb88436-2e7b-4976-b533-9d18ce4f0524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>866</value>
      <webElementGuid>dc989ddf-7a98-4a03-aa41-0f1f61a6351f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2759362e-7e54-4f66-85db-3745b51ba138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaZamestnavatelia&quot;)/table[@class=&quot;govuk-table&quot;]/tbody[@class=&quot;govuk-table__body&quot;]/tr[3]/td[@class=&quot;govuk-table__cell&quot;]/span[1]</value>
      <webElementGuid>2faf9848-f31c-4cff-9471-6d52093a3b12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@name='PorCislo'])[3]</value>
      <webElementGuid>1ac2d58c-42e9-4b7f-b186-0d19ca2086cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tabulkaZamestnavatelia']/table/tbody/tr[3]/td[2]/span</value>
      <webElementGuid>677d7cf2-9bc5-4d9a-bd88-25d29b6ac7e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[2]/following::span[1]</value>
      <webElementGuid>ccbcfcb8-bfce-4d11-ae2e-2fc5e2f45f2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stredná odborná škola Policajného zboru Košice, Košice-Juh 1, Košice'])[1]/following::span[1]</value>
      <webElementGuid>8c6ba9ca-4b4e-4d85-9418-3bdb47780dbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Stredná odborná škola technická, Košice 1, Košice'])[1]/preceding::span[1]</value>
      <webElementGuid>7eb8dd8d-fec8-4dca-8467-8dfccd881640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vygenerovať potvrdenie'])[3]/preceding::span[2]</value>
      <webElementGuid>9b2348ca-2517-4b63-86d6-f60018455ed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2']/parent::*</value>
      <webElementGuid>273ab7ef-72d5-4ed6-9125-d56d35101aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/span</value>
      <webElementGuid>a679d575-b565-46ba-a1d7-a18c1caab508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@name = 'PorCislo' and (text() = '2' or . = '2')]</value>
      <webElementGuid>93292c8e-b063-4645-8981-55c4b9ccc570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
