<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi_2</name>
   <tag></tag>
   <elementGuidId>e04b7b03-0f91-4b2b-b616-c29720110253</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ulozit-detail-prilohy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='ulozit-detail-prilohy'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2cf71190-3110-4d33-be61-b9373f63491b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ulozit-detail-prilohy</value>
      <webElementGuid>bbca793e-535c-4474-b128-dd0100412477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>59e63773-0cdf-4f8c-9f1c-97950912404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>634c6ed9-6302-4d7e-8f25-e3d8675e59bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-1&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;referencne-registre&quot;]/div[@class=&quot;govuk-form-group&quot;]/button[@id=&quot;ulozit-detail-prilohy&quot;]</value>
      <webElementGuid>50ee9b8e-8bde-470a-a90e-09695c7bf3a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='ulozit-detail-prilohy'])[2]</value>
      <webElementGuid>730ffe11-0b28-4395-b2fd-05c5875e8a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='referencne-registre']/div[2]/button[2]</value>
      <webElementGuid>650714d8-289d-4bbe-a787-344f10be4718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[1]/following::button[1]</value>
      <webElementGuid>8cf9320a-c7aa-4b6d-b98e-6733b6d7884f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='súhlasím so získaním údajov z referenčných registrov'])[1]/following::button[2]</value>
      <webElementGuid>cb8138bf-3950-4d7c-964e-98db14771ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odobrať'])[1]/preceding::button[1]</value>
      <webElementGuid>efc93657-63df-4eec-bf6b-966ae7116f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spoločná veľkosť priložených súborov nesmie presiahnuť 20 MB.'])[1]/preceding::button[1]</value>
      <webElementGuid>f49ef3c6-b2a6-4d52-839e-009e8acf4c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button[2]</value>
      <webElementGuid>e7577b0d-10d9-481f-b349-279c5c7d81c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ulozit-detail-prilohy' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>eef48222-b19b-454e-9725-d5746e4255e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
