<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi</name>
   <tag></tag>
   <elementGuidId>d4c6b396-d170-4afe-8360-17b6f7b5eb6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tabulkaStudiumUlozit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='tabulkaStudiumUlozit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4122f962-3666-43d9-94ba-1395498ad07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e7f2c327-34fa-4b0c-a920-7f5918223013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button</value>
      <webElementGuid>8e305ddd-3a19-4f6f-a3d5-6067c02fc9f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tabulkaStudiumUlozit</value>
      <webElementGuid>87e5e193-830a-4ca6-92ed-dfb9902a70be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>c1a779da-a363-4a82-b98c-961c38ccca47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaStudiumUlozit&quot;)</value>
      <webElementGuid>b93edb97-fb5a-42cd-b42f-33428f8741f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>416</value>
      <webElementGuid>25f4f347-ea60-4dd5-a225-fdd5a25cc6bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='tabulkaStudiumUlozit']</value>
      <webElementGuid>32776806-c366-4b25-9c0e-0f868ba0a676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//fieldset[@id='UI_V_ZP_in_InformacieStudium_UI_V_ZP_in_TabulkaStudium']/button</value>
      <webElementGuid>85bb2fae-c833-455d-997b-d08a439160bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lekárska fakulta'])[1]/following::button[1]</value>
      <webElementGuid>4fa5ba5f-5b37-4676-8719-5065b10286f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Univerzita Komenského v Bratislave'])[1]/following::button[1]</value>
      <webElementGuid>4cdd825c-a64f-4f17-882a-4eb9000a1f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Na akej vysokej škole študujete?'])[1]/preceding::button[1]</value>
      <webElementGuid>7a61d5d3-978e-46f3-a065-9d2648fe401f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov vysokej školy'])[1]/preceding::button[1]</value>
      <webElementGuid>64fa77e1-dad0-4ad7-9e23-e3547eddb844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Uložiť']/parent::*</value>
      <webElementGuid>881faf8b-b9e0-4adf-9947-cbf13c2b6d7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>0acafa7f-ee90-4fca-9fa9-5cb2333b9905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'tabulkaStudiumUlozit' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>f57b1f27-2a52-4864-b83d-64f86fd40c66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
