<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Uloi_1</name>
   <tag></tag>
   <elementGuidId>bfd2dc8d-04b9-4899-92de-10a0e682911d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ulozit-detail-prilohy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ulozit-detail-prilohy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>839e399a-b04e-44ae-add3-e6d328924631</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ulozit-detail-prilohy</value>
      <webElementGuid>b96c4537-9bc7-4bb2-a59a-ddfcda96a9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>89db58c5-a4a5-4357-a8bc-247cd04bfe4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Uložiť</value>
      <webElementGuid>8475c002-7c8a-4364-b8f5-fae489ac71f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-1&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;referencne-registre&quot;]/div[@class=&quot;govuk-form-group&quot;]/button[@id=&quot;ulozit-detail-prilohy&quot;]</value>
      <webElementGuid>fa451339-634b-401d-a7cf-0eb9f2483251</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ulozit-detail-prilohy']</value>
      <webElementGuid>427be31e-290a-4c98-b25f-9e81f06064a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='referencne-registre']/div[2]/button[2]</value>
      <webElementGuid>9baead6f-fa82-4eeb-8f17-55245665dd4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zrušiť'])[1]/following::button[1]</value>
      <webElementGuid>60b4f2e1-bc71-43c5-b9fe-b7b92e79b91c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='súhlasím so získaním údajov z referenčných registrov'])[1]/following::button[2]</value>
      <webElementGuid>a821128a-b590-459c-a8a2-df9bea16df35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odobrať'])[1]/preceding::button[1]</value>
      <webElementGuid>c70e25df-2503-4bbb-986c-0b1e30021b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spoločná veľkosť priložených súborov nesmie presiahnuť 20 MB.'])[1]/preceding::button[1]</value>
      <webElementGuid>91908aab-9661-4c66-9fa4-0c06ce51cf28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>895c9648-7f27-4ba1-9e3c-43a60bcde594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ulozit-detail-prilohy' and (text() = 'Uložiť' or . = 'Uložiť')]</value>
      <webElementGuid>1a54393b-657c-48ac-a998-f8ed3cc3a472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
