<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail</name>
   <tag></tag>
   <elementGuidId>494860b2-80d0-4793-b60c-fb14a2f22cb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-prilohy-btn-D1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-prilohy-btn-D1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6cf2c289-dfb9-45ae-8ee1-40c1af823703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-prilohy-btn-D1</value>
      <webElementGuid>fa2224a9-5077-4d24-b433-54ead165f93e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-!-font-size-19 govuk-button secondary</value>
      <webElementGuid>448dc4a1-6530-44a3-a56f-153eda380178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typprilohykod</name>
      <type>Main</type>
      <value>D1</value>
      <webElementGuid>1bd63c0a-f474-41d7-9b0b-e266e9a573fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>de118713-0b9a-4c6f-8b48-62c8b2766a53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prilohy-btn-D1&quot;)</value>
      <webElementGuid>8b5267e8-62e5-42c5-b2e0-70bd297c9bab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-prilohy-btn-D1']</value>
      <webElementGuid>7e73881b-a42d-4b4f-8913-cc2591382733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skutocnosti-prilohy-1']/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>f2d5e0d7-bf32-469d-a6bd-aa33733ee628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie o návšteve VŠ v SR (žiadateľ)'])[1]/following::button[1]</value>
      <webElementGuid>763a1839-f541-4d23-8866-3f31f43f9390</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Spôsob doloženia prílohy'])[4]/following::button[1]</value>
      <webElementGuid>0ef1f85a-009b-4f14-9e5e-2bd8888928bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Som členom domácnosti, ktorej sa poskytuje pomoc v hmotnej núdzi'])[1]/preceding::button[1]</value>
      <webElementGuid>bdf92e3f-5e34-4693-8a6d-fc33a386de94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy'])[5]/preceding::button[1]</value>
      <webElementGuid>4f146fa0-8185-4197-87e4-8cd995b88201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/table/tbody/tr/td[3]/button</value>
      <webElementGuid>988d1bcb-d258-435f-9c00-409ce60a309d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-prilohy-btn-D1' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>3cb56440-dd5f-4370-b286-043a372d1d66</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
