<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Detail_1_2</name>
   <tag></tag>
   <elementGuidId>7ea99b19-8fbe-4ff5-b175-d925a45f5f6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#detail-prilohy-btn-D10</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='detail-prilohy-btn-D10']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69f70e7a-a380-470e-aea6-fc4ab34f0df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>detail-prilohy-btn-D10</value>
      <webElementGuid>1327bd96-1a45-4bfa-9ab6-7ba28cc81b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-!-font-size-19 govuk-button secondary</value>
      <webElementGuid>e16e3044-4417-49ff-be98-ceb8ed2f2f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typprilohykod</name>
      <type>Main</type>
      <value>D10</value>
      <webElementGuid>dea769c2-3490-499a-b20b-44150e34ae65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Detail</value>
      <webElementGuid>1de0a75a-432b-433e-ab99-5d8c84867718</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detail-prilohy-btn-D10&quot;)</value>
      <webElementGuid>18330159-7de3-49b4-9d67-a56fb7468ee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='detail-prilohy-btn-D10']</value>
      <webElementGuid>0af61135-68c0-4428-9d5a-590d4c7d1d97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='skutocnosti-prilohy-5']/fieldset/table/tbody/tr[2]/td[3]/button</value>
      <webElementGuid>ee38cf68-fee2-447d-b57a-1a09017d31d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Potvrdenie o poberaní dávok v hmotnej núdzi (žiadateľ je poberateľom dávok)'])[1]/following::button[1]</value>
      <webElementGuid>24e30f6a-d23b-4283-b6fe-b42f85f82401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail'])[8]/following::button[1]</value>
      <webElementGuid>ea1e0446-f77f-4051-8089-a0f5534193f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Som nezaopatreným dieťaťom (vek do 26 rokov), ktorému zomrel rodič alebo osvojiteľ'])[1]/preceding::button[1]</value>
      <webElementGuid>1302737c-4732-4f4d-94d0-cf31b8420899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Typ prílohy'])[6]/preceding::button[1]</value>
      <webElementGuid>80191d63-dcc6-4e34-82b0-cfb6925b8c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/fieldset/table/tbody/tr[2]/td[3]/button</value>
      <webElementGuid>afb781c1-1985-4acf-a02e-0029d37cb9e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'detail-prilohy-btn-D10' and (text() = 'Detail' or . = 'Detail')]</value>
      <webElementGuid>bebf2ade-e845-45e0-9c90-06e13ec45ade</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
