<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odosla nepodpsan iados o piku a vytl_be1331</name>
   <tag></tag>
   <elementGuidId>db9bfb88-9c0c-41ad-a8a8-47f3d2129978</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#odoslat-nepodpisane-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='odoslat-nepodpisane-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6fda3caf-45b8-4657-950d-74b5ffd9acb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>odoslat-nepodpisane-btn</value>
      <webElementGuid>36d29ec7-48d1-4b62-bafd-4ce434779796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odoslat-nepodpisane-btn</value>
      <webElementGuid>4e2639e4-b6fa-4a0f-bfc7-6098fa7700f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>15b825ab-0e0f-47db-acfd-f64653d94690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár</value>
      <webElementGuid>4eef2e24-8f1b-432e-aa66-931b3c9cbccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;odoslat-nepodpisane-btn&quot;)</value>
      <webElementGuid>0a21c533-115f-4b9a-b38f-826987f59f2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='odoslat-nepodpisane-btn']</value>
      <webElementGuid>2a546165-6a9b-4303-b58f-ddf09ce52d23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odoslanie-podpisanie-buttons']/div[2]/button</value>
      <webElementGuid>1c4ab399-2c91-4e27-9d6d-222832b76fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa'])[1]/following::button[1]</value>
      <webElementGuid>c8df5546-444e-456c-8b8c-c9555ba863f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na domovskú stránku'])[2]/following::button[2]</value>
      <webElementGuid>5d71abb4-4ac9-420a-847b-5555fbe9661b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::button[1]</value>
      <webElementGuid>6e648214-4ca0-4080-9c1a-d8ff23b9e40e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/preceding::button[2]</value>
      <webElementGuid>89483cf0-f836-4548-ba58-d1b5fb097d04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár']/parent::*</value>
      <webElementGuid>8a606836-217c-432d-8d15-4a3f643601b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div[2]/button</value>
      <webElementGuid>353f0ddc-92a0-484e-8de5-dfddb6bd6d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'odoslat-nepodpisane-btn' and @name = 'odoslat-nepodpisane-btn' and (text() = 'Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár' or . = 'Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár')]</value>
      <webElementGuid>30372ea4-a45e-4677-8987-0671ac4777a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
