<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pokraova</name>
   <tag></tag>
   <elementGuidId>fd201668-612c-486c-97ff-884a5dbf69a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pokracovat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='pokracovat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b81517ab-a10a-4f8f-b296-515731febb69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pokracovat-btn</value>
      <webElementGuid>63c32db4-5720-4c00-8491-538490aad14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>d1a301a3-b5e5-44fc-a2a7-19a9611d22aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pokračovať</value>
      <webElementGuid>d34a2846-9250-4583-8a69-67d75e9c0760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pokracovat-btn&quot;)</value>
      <webElementGuid>53c34d1d-db49-4148-b156-832cc0762064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>406</value>
      <webElementGuid>49cc20b9-0191-4397-b610-e93bf1fae926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='pokracovat-btn']</value>
      <webElementGuid>1957b99e-c629-4762-8d18-4b7006f3a7bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[4]</value>
      <webElementGuid>77975d06-59e2-43ad-9d7b-7421945d3f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/following::button[1]</value>
      <webElementGuid>fd160cd0-85f6-424c-a5bf-2789934a4845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/following::button[2]</value>
      <webElementGuid>7aefa0f9-b72d-4c67-9849-1dc1d7801766</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovať'])[1]/preceding::button[1]</value>
      <webElementGuid>d507a0bb-88f3-4233-b75d-37568e3a0496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uložiť rozpracované podanie'])[1]/preceding::button[2]</value>
      <webElementGuid>d3e18e22-1229-4e36-8990-0ecc5c7a49da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pokračovať']/parent::*</value>
      <webElementGuid>96fdf2d7-6873-4fe8-8d5e-88c1d2a7a1c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[4]</value>
      <webElementGuid>87aedefd-2536-435c-b8ca-39093b69e878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'pokracovat-btn' and (text() = 'Pokračovať' or . = 'Pokračovať')]</value>
      <webElementGuid>ee60c94d-2caf-4649-84f9-c8b8e4b49a6f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
