<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Podpsa</name>
   <tag></tag>
   <elementGuidId>08ee0b2a-a2d0-4d25-94ba-ed4196834c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podpisat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='podpisat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a13c500d-4436-49a5-b002-76d21a1a8091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podpisat-btn</value>
      <webElementGuid>72cccdc3-1424-4efe-8dda-24ebb05da5f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>podpisat-btn</value>
      <webElementGuid>93a4f969-5272-458b-923c-49a878d30608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green podpisat-odoslat govuk-!-margin-top-4</value>
      <webElementGuid>97f37824-f9ad-49fd-8a84-a28a88d2a9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>404</value>
      <webElementGuid>ca5174b2-f499-4e87-b7d4-4692da32b708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podpísať</value>
      <webElementGuid>ab600049-98a9-43c1-ba16-447f8996fb7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podpisat-btn&quot;)</value>
      <webElementGuid>455ef91e-f712-4297-a549-631961ae147f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='podpisat-btn']</value>
      <webElementGuid>addcf5bb-4c8e-4546-a4ca-5a3dfadc4769</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[2]</value>
      <webElementGuid>729ee19f-7506-426d-be4c-b180b55547ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/following::button[1]</value>
      <webElementGuid>a15f5c34-4c1f-4690-83ea-f4a1efadd66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/following::button[2]</value>
      <webElementGuid>c80cd9d2-444c-4135-9330-c5f541303241</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať'])[2]/preceding::button[1]</value>
      <webElementGuid>04c634af-f67d-478e-bfdf-c7aedb1e3d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/preceding::button[2]</value>
      <webElementGuid>188ee063-22a3-41bf-a058-78869ee3bb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]</value>
      <webElementGuid>3f57f915-5ac4-4eeb-ad36-ca3fec2a2554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'podpisat-btn' and @name = 'podpisat-btn' and (text() = 'Podpísať' or . = 'Podpísať')]</value>
      <webElementGuid>a51c1c57-3b24-4a43-8e26-7e3a2c683eb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
