<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Prejs na domovsk strnku</name>
   <tag></tag>
   <elementGuidId>3e475a3d-06d1-41c6-a27d-2df2576f9b55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#go-home-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='go-home-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3ddc6027-214e-49e0-9aba-6ba989dc459c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>go-home-btn</value>
      <webElementGuid>61510911-79be-4a81-b2ff-1218392a23e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green</value>
      <webElementGuid>c03d8c3f-fafe-42f5-bb73-59abcd3acc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1189</value>
      <webElementGuid>85d2d858-23fc-458b-8781-89e9caa356cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prejsť na domovskú stránku</value>
      <webElementGuid>ac464e06-aa0c-47fc-bc5e-e6a38db8df1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;go-home-btn&quot;)</value>
      <webElementGuid>1ad281aa-43bf-4758-b313-fb33bbe67808</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='go-home-btn']</value>
      <webElementGuid>ae0434e2-465b-4335-8b13-de6ba145886e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hodnotenie-spokojnosti-s-e-sluzbou']/div[4]/button[2]</value>
      <webElementGuid>e8fc1d78-f7b6-4a13-9159-67fc66e85223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať spätnú väzbu'])[1]/following::button[1]</value>
      <webElementGuid>3a9a59db-a39f-4111-ba60-8220038d754b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ďakujeme za spätnú väzbu.'])[1]/following::button[2]</value>
      <webElementGuid>97ae7d6b-6de7-49ac-9a1e-a2a795bdf34f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Čo bude nasledovať?'])[2]/preceding::button[1]</value>
      <webElementGuid>54e618da-6f3b-46e8-8688-d0b44f5aca1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prejsť na domovskú stránku']/parent::*</value>
      <webElementGuid>03c61cdb-b9bf-4a06-bcc3-e30fe0950269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>9fffd32a-e16d-42c8-a453-5b3e61390510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'go-home-btn' and (text() = 'Prejsť na domovskú stránku' or . = 'Prejsť na domovskú stránku')]</value>
      <webElementGuid>249dd365-2127-4bf2-a8d5-5f7126f8f715</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
