<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Odosla</name>
   <tag></tag>
   <elementGuidId>4a87edce-05bd-4e9a-bfa4-a1775ae923cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-buttons-section > #odoslat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//button[@id='odoslat-btn'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3caa4fc5-b307-42bf-8279-a20d2f72a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>odoslat-btn</value>
      <webElementGuid>fb1599eb-40e6-448c-ba48-54d2d1767afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>odoslat-btn</value>
      <webElementGuid>b95e9275-f933-45f6-ab85-e9ca912f7ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green odoslat govuk-!-margin-top-4</value>
      <webElementGuid>99f2373b-f4e8-48f3-9ba4-12127b26161b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>405</value>
      <webElementGuid>a2883352-06b9-476d-97f7-2a08c1019e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Odoslať</value>
      <webElementGuid>a71b59b4-1068-4e67-b31e-9a27b597bd69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-buttons-section&quot;)/button[@id=&quot;odoslat-btn&quot;]</value>
      <webElementGuid>2af25755-8e44-4260-b491-d9948c86975e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='odoslat-btn'])[2]</value>
      <webElementGuid>29649581-52d3-42b4-b9ea-6b8e85f25e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='form-buttons-section']/button[3]</value>
      <webElementGuid>d6ba594f-70c7-43ed-92a6-b90dafc02376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podpísať'])[2]/following::button[1]</value>
      <webElementGuid>d366e3e5-cd51-4375-945b-8ae53791ab22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/following::button[2]</value>
      <webElementGuid>91e829f2-0326-461a-9445-2f3b71471882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pokračovať'])[1]/preceding::button[1]</value>
      <webElementGuid>31bfc05e-4088-4b38-9fea-349e6ff5917f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skontrolovať'])[1]/preceding::button[2]</value>
      <webElementGuid>369d4687-409a-4283-926e-cbecfc3a20ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>b8acaf37-a833-472b-b89f-feb1b25f019d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'odoslat-btn' and @name = 'odoslat-btn' and (text() = 'Odoslať' or . = 'Odoslať')]</value>
      <webElementGuid>a1c9438d-80a3-4413-8795-6800fd196bed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
