<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Podpsa iados o piku kvalifikovanm el_0eb4be</name>
   <tag></tag>
   <elementGuidId>0b811d70-544c-488c-a76c-5287f3d0411d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#podpisat-a-odoslat-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='podpisat-a-odoslat-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c512bf2-e578-49e8-8bfa-e16fccdc32c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>d518829d-653a-4f0d-8884-230ec9a5e9b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>podpisat-a-odoslat-btn</value>
      <webElementGuid>6a8f20e3-cc79-4bdf-9e87-0a05967862b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-button green govuk-!-margin-top-4</value>
      <webElementGuid>843cbe3f-fd61-4be2-b797-57471fbcce41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>1109</value>
      <webElementGuid>2b8316f3-3048-4767-97e8-97e34b960d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa</value>
      <webElementGuid>56f38201-7757-403c-bc96-073d4495f222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;podpisat-a-odoslat-btn&quot;)</value>
      <webElementGuid>45a3aa15-7a0e-47aa-8549-214612e5608a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='podpisat-a-odoslat-btn']</value>
      <webElementGuid>6fdbb7ea-c825-4021-acaf-814c3f2c8aeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='odoslanie-podpisanie-buttons']/div/button</value>
      <webElementGuid>54ff6588-4918-46bd-9416-0ccb7d6c9ccc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prejsť na domovskú stránku'])[2]/following::button[1]</value>
      <webElementGuid>1a8fc249-5e60-478d-a119-25887a42e699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fond na podporu vzdelávania'])[2]/following::button[1]</value>
      <webElementGuid>a2cf3c49-bcab-488d-a0c2-4e20ec892645</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Odoslať nepodpísanú žiadosť o pôžičku a vytlačiť vyplnený formulár'])[1]/preceding::button[1]</value>
      <webElementGuid>62c509a4-ce5f-4c6c-a78b-1c3ef41227cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Späť'])[1]/preceding::button[2]</value>
      <webElementGuid>2f5247f4-c0aa-44ce-8704-c575b667cc59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa']/parent::*</value>
      <webElementGuid>732499f9-daea-4e8d-80b7-835a4f3e9629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>bc589c0b-666a-46a2-985f-d02a3cb30481</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'podpisat-a-odoslat-btn' and @name = 'podpisat-a-odoslat-btn' and (text() = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa' or . = 'Podpísať žiadosť o pôžičku kvalifikovaným elektronickým podpisom žiadateľa')]</value>
      <webElementGuid>ebec4310-4cfd-40b7-994f-dc68845d88e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
