<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_daje zo iadosti o piku boli odoslan</name>
   <tag></tag>
   <elementGuidId>461c7573-f270-482f-be82-8ca6fb11a0e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.govuk-panel__title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='formular']/div/div[2]/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8dbdb545-dcf2-4dc3-92d1-f7e24e988755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-panel__title</value>
      <webElementGuid>9d03c940-39cf-4e93-b63a-9a28635e53be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Údaje zo žiadosti o pôžičku boli odoslané.</value>
      <webElementGuid>1e241af4-ef6d-4ead-93e4-0327aa89bab6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;formular&quot;)/div[@class=&quot;govuk-width-container&quot;]/div[@class=&quot;govuk-main-wrapper&quot;]/div[@class=&quot;govuk-panel govuk-!-margin-bottom-8 govuk-panel--green-confirmation&quot;]/h1[@class=&quot;govuk-panel__title&quot;]</value>
      <webElementGuid>b3d0cc7a-91bc-490d-987a-7818fc3a3a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='formular']/div/div[2]/div/h1</value>
      <webElementGuid>88005502-e981-4259-b1fa-4641ceae6c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Formulár žiadosti o pôžičku (bez zabezpečenia ručiteľom)'])[1]/following::h1[1]</value>
      <webElementGuid>7871a4a1-00ce-44e5-8750-75814f684911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podávanie žiadosti o pôžičku pre študentov z Fondu na podporu vzdelávania'])[1]/following::h1[1]</value>
      <webElementGuid>aa771884-21b8-4ac3-a29e-cef22cabbdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Podávanie žiadosti o pôžičku pre študentov z Fondu na podporu vzdelávania (bez ručiteľa)'])[1]/preceding::h1[1]</value>
      <webElementGuid>d7b4847f-d0ed-4596-8ae4-987bba6bf606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje žiadateľa'])[1]/preceding::h1[2]</value>
      <webElementGuid>82bb7c05-2b46-4a88-962c-0e02e111d5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Údaje zo žiadosti o pôžičku boli odoslané.']/parent::*</value>
      <webElementGuid>0da98bd5-6196-4413-908a-d3f0c302de4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>baf92f29-2264-44f2-83b5-35a928fb3b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Údaje zo žiadosti o pôžičku boli odoslané.' or . = 'Údaje zo žiadosti o pôžičku boli odoslané.')]</value>
      <webElementGuid>6ea9289e-aa06-4068-98cb-9d3a72f07412</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
