<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte telefnne slo vrtane medzinrod_dbbd6c</name>
   <tag></tag>
   <elementGuidId>12e37604-fbb5-4f65-9bb1-af669534f274</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_KontaktneInformacie_Telefon-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Telefon-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e3944ae5-c9dc-4a11-9467-75133dd49f18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>5e12adc4-edaa-4a6b-9557-25dc0b4bb8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Telefon-control</value>
      <webElementGuid>f542afc0-c66e-47ee-bc2b-a0a0764f85b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Telefon-control</value>
      <webElementGuid>b3b855b4-7272-4996-835d-5933928141ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0c4f0888-dda8-4b86-a4bf-57a9811a7d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Telefon-hint</value>
      <webElementGuid>5d79628d-37eb-418b-8b21-86e71c625085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_KontaktneInformacie_Telefon-control&quot;)</value>
      <webElementGuid>ed7b2aab-a6ff-4887-9400-589878d30bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>376</value>
      <webElementGuid>2b267073-b2d1-4530-a31b-123d90798282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Telefon-control']</value>
      <webElementGuid>0042ca49-f11d-4baa-96a4-cad22c3d55ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_KontaktneInformacie_Telefon']/input</value>
      <webElementGuid>155d4780-4ed5-43e5-b776-e9e23333e62b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[3]/input</value>
      <webElementGuid>109d3530-d84b-4391-b6b3-888c5f940f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_KontaktneInformacie_Telefon-control' and @name = 'UI_V_ZP_in_KontaktneInformacie_Telefon-control' and @type = 'text']</value>
      <webElementGuid>2ad1a55e-cdc2-4339-8fe5-e3ddbce2890f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
