<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rok_UI_V_ZP_in_DalsieStudiumSlovenska_e3d9a8</name>
   <tag></tag>
   <elementGuidId>49ed7bef-a81f-40ba-b502-9b975d1cebd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8c194de8-ef4e-483d-b803-39a92dee1be1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>25f16fcb-414f-426c-8558-fe320946841e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-4</value>
      <webElementGuid>d18e4dba-529c-45f3-9a2d-dbff185c99e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Predpokladaný dátum štátnej skúšky. </value>
      <webElementGuid>9806975f-6024-4892-b717-b1344a883221</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year</value>
      <webElementGuid>a0ceae4d-5658-4268-acb3-8b2d61187283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>84257dea-1a6f-4057-a2a1-b43e2005aeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year</value>
      <webElementGuid>61894e0b-cb08-4b37-9104-ecdba2d3050b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year&quot;)</value>
      <webElementGuid>a9bf7523-44f4-461e-b1a9-2d13d7b34fef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year']</value>
      <webElementGuid>0939f926-67e2-402b-9522-e9b751ad0f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-control']/div[2]/div/input</value>
      <webElementGuid>f11de33d-9fde-4197-bb5f-b12564898965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/div/input</value>
      <webElementGuid>968bf1c1-6fa2-41e4-b436-df06f04ea617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Predpokladaný dátum štátnej skúšky. ' and @id = 'UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-year']</value>
      <webElementGuid>f5153e38-e308-49ec-ac68-d131d94e72e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
