<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nie_typ-9</name>
   <tag></tag>
   <elementGuidId>eb20a45c-1bf1-4cb1-8e1e-47c07d82425f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typ-9</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typ-9']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5962ff1a-4252-45df-adca-b41c95c19f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>d1379e2f-6e4c-42c8-a4c6-d93161e57cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typ-9</value>
      <webElementGuid>c1fbbea8-1383-464d-8c26-bda517bb8725</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>f83ae36f-6f67-43e8-b24e-e470e8a54d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c09c10d9-7448-463c-87eb-b0dce6d4a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typ-9</value>
      <webElementGuid>57489739-0d51-4730-b855-18a9ded048be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typkriteria</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>4bdb4e2f-be78-4a7c-9647-e6e8be5fecd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>conditional-napoveda-9</value>
      <webElementGuid>1862ad10-e136-48bb-a9a1-8593b0ff2e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d08b4c5f-74d7-4d29-93ae-cb3d698b88a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>799</value>
      <webElementGuid>cd5d7622-258b-40ce-b305-266b17e3907e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typ-9&quot;)</value>
      <webElementGuid>5dc5b3b9-2332-4618-9e38-f285a139b107</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typ-9']</value>
      <webElementGuid>f357d9b7-32db-4e8f-8516-42580c25dc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rbSkutocnost-9']/fieldset/div/div/input</value>
      <webElementGuid>0b586a4b-fe9b-4bab-bb8c-4cb435f9b413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[5]/fieldset/div/div/input</value>
      <webElementGuid>eff0ad76-ac7c-4bc5-9467-f63599294d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'typ-9' and @type = 'radio' and @id = 'typ-9']</value>
      <webElementGuid>545d93ce-806b-4071-8136-eda5376c9eee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
