<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte poadovan splatnos piky na cel_96d0f4</name>
   <tag></tag>
   <elementGuidId>820489e6-7f91-4160-a773-9a2984e33d74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_VyskaALehota_LehotaPozicky-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_VyskaALehota_LehotaPozicky-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>55379fe4-c5a3-4201-a133-ca364f3d2a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>20429f99-0f62-464e-9d13-6e2acd6c960d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_LehotaPozicky-control</value>
      <webElementGuid>706b2507-8f7c-469b-b5a4-a421f4110bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_LehotaPozicky-control</value>
      <webElementGuid>03bba1f8-c4c9-452e-8747-54ec9227478e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>4a352c53-b4ef-4bdb-9e01-b07a7f975311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_LehotaPozicky-hint</value>
      <webElementGuid>4a8f6d94-aae3-4b2d-947f-d7fff23a66a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_VyskaALehota_LehotaPozicky-control&quot;)</value>
      <webElementGuid>c38039dd-ba4c-480a-8e68-1c6a5b9d71c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_VyskaALehota_LehotaPozicky-control']</value>
      <webElementGuid>d53ffd98-a967-48d7-909f-9b913fcf5784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_VyskaALehota_LehotaPozicky']/input</value>
      <webElementGuid>cce432b3-9903-4625-b1d7-50585f01161d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div[2]/input</value>
      <webElementGuid>dbe3c3f0-f367-472f-a44a-43d5ec67a59c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_VyskaALehota_LehotaPozicky-control' and @name = 'UI_V_ZP_in_VyskaALehota_LehotaPozicky-control' and @type = 'number']</value>
      <webElementGuid>dd746872-567c-4dc3-823c-1c82b5a26edf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
