<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_I. stupe_UI_V_ZP_in_SkolaSlovenska_St_7dbc3c</name>
   <tag></tag>
   <elementGuidId>bacfe1ea-f132-4270-8a0b-7f18cf53eec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='UI_V_ZP_in_SkolaSlovenska_StupenVzdelania-group'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3304acd1-7d6e-4765-8bad-466646354a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>ccc7f8ac-3d25-4576-93a3-4893bed10e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_StupenVzdelania-group</value>
      <webElementGuid>ede3fc24-54d8-4981-9c38-b99aaeacfdb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>924b2105-805a-4006-ba22-78d9009cdaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f72d5909-89cf-4726-863b-367b2b43bd8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_StupenVzdelania&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;govuk-radios&quot;]/div[@class=&quot;govuk-radios__item&quot;]/input[@class=&quot;govuk-radios__input&quot;]</value>
      <webElementGuid>d70f52f9-15f2-4760-aca5-4ebafc2623ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>511</value>
      <webElementGuid>39fff600-33b9-4ff5-ae8a-b12a5bad9426</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@name='UI_V_ZP_in_SkolaSlovenska_StupenVzdelania-group'])[2]</value>
      <webElementGuid>87c0685c-c9c7-4e14-bf6d-67427896cca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_StupenVzdelania']/fieldset/div/div[2]/input</value>
      <webElementGuid>c94e4b67-f010-4ebd-991f-03fa3658efe6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/fieldset/div/div[2]/input</value>
      <webElementGuid>f3f20fdb-1784-4a1e-98a2-a8ab5cc3c9dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'UI_V_ZP_in_SkolaSlovenska_StupenVzdelania-group' and @type = 'radio']</value>
      <webElementGuid>8cc0eaa5-78f3-49b6-868e-2ed13e300b2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
