<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rok_UI_V_ZP_in_SkolaSlovenska_DatumZa_88e07d</name>
   <tag></tag>
   <elementGuidId>fb985fad-17f3-41bc-b3b5-85c71ebca8ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f616c3ae-7f14-4421-8361-e96e4c873921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>3ab6bd55-485b-44aa-9d83-f2a35b28ba85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-4</value>
      <webElementGuid>93b938eb-cf1b-42f2-97ce-885203f0698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dátum zápisu na štúdium v aktuálnom akademickom roku </value>
      <webElementGuid>17c1af4a-a442-47da-b08a-4970de7b5bc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year</value>
      <webElementGuid>63a4f59c-e86f-46ed-891d-a0e8bda06e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f1568312-fa9e-4fce-a69f-533e3e5db84a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year</value>
      <webElementGuid>ee053950-70df-4b7a-8dc6-b84058e485a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year&quot;)</value>
      <webElementGuid>a14a9bf2-e6d3-4377-aed4-179658e17e67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year']</value>
      <webElementGuid>c72dd628-cab5-498a-b9ad-ee7d33597445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-control']/div[3]/div/input</value>
      <webElementGuid>4454b7b2-3edd-4c55-b186-14bb8c166933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>5f7d4d0b-0929-4d94-b1f0-eea38dcfcb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Dátum zápisu na štúdium v aktuálnom akademickom roku ' and @id = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year' and @name = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-year']</value>
      <webElementGuid>87199bfd-115e-4369-935a-291be57b4445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
