<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_tudent  III. stupa vysokokolskho tdia_8c32d4</name>
   <tag></tag>
   <elementGuidId>15efea67-ee6f-4e89-b50d-38e40abf4597</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_VyskaALehota_VyskaPozicky-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_VyskaALehota_VyskaPozicky-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f761b238-4798-49d8-a577-0a0a4bb4f374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>4e3a2be6-b159-41eb-a4b6-dcebcc5a6410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_VyskaPozicky-control</value>
      <webElementGuid>dfbda724-976b-4559-aa1e-4cdea7d3e69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_VyskaPozicky-control</value>
      <webElementGuid>896bb1a8-89f9-49ce-ab4e-434a19913158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9ef50b83-09a4-4004-82f7-dbc28b48dc5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_VyskaALehota_VyskaPozicky-hint</value>
      <webElementGuid>ff50e05c-f847-4e1f-8bb6-69de83deb819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_VyskaALehota_VyskaPozicky-control&quot;)</value>
      <webElementGuid>55c16751-42c3-44d9-a0cc-df5218dda885</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_VyskaALehota_VyskaPozicky-control']</value>
      <webElementGuid>262673b8-d599-44a6-a1b3-e998cf94f3e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_VyskaALehota_VyskaPozicky']/input</value>
      <webElementGuid>e1a6a9b8-5266-468a-b0bf-d52921845301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/input</value>
      <webElementGuid>970496df-70c6-44ac-9970-a996d3a596ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_VyskaALehota_VyskaPozicky-control' and @name = 'UI_V_ZP_in_VyskaALehota_VyskaPozicky-control' and @type = 'number']</value>
      <webElementGuid>3a53140e-f640-4a41-b242-ca78bd12c722</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
