<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte kontaktn e-mailov adresu_UI_V_aee6cc</name>
   <tag></tag>
   <elementGuidId>134c561f-7a14-4e8e-b753-ede8485261e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Email-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a98e2a32-b008-4b91-82f2-1f5ac7496d2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>d0c0c5c1-8a6a-4fe8-8cef-283cf1a74cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      <webElementGuid>4f2c4912-ddec-4f03-8afa-5bd56d444d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-control</value>
      <webElementGuid>e800068d-406e-4b54-84c1-8f8adec926c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e5775e0b-9a7d-4ad6-9234-cdb5dad36c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_KontaktneInformacie_Email-hint</value>
      <webElementGuid>71581d72-25fe-4e50-81ed-1c184e0016da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_KontaktneInformacie_Email-control&quot;)</value>
      <webElementGuid>e3e5cdfd-c68c-45a7-82eb-ac5c4a043c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>384</value>
      <webElementGuid>48fcbe8d-92fb-4523-b850-c117f301610c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_KontaktneInformacie_Email-control']</value>
      <webElementGuid>7c32234a-57a1-48b8-b64c-e2d93ea4c3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_KontaktneInformacie_Email']/input</value>
      <webElementGuid>2161adb7-3c5e-4ecf-b91a-4fcffd715282</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[5]/div[2]/input</value>
      <webElementGuid>7265c577-3c39-4f8e-8192-98ba3484b246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_KontaktneInformacie_Email-control' and @name = 'UI_V_ZP_in_KontaktneInformacie_Email-control' and @type = 'text']</value>
      <webElementGuid>28b6dd6f-ca30-4816-8bb7-5f84857471cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
