<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nie_typ-8</name>
   <tag></tag>
   <elementGuidId>a42e509c-f4b5-4ba8-8e66-61164a912a6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typ-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typ-8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c64077d5-43f3-4931-a062-3cd38b54bdf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>1774c611-47c2-4888-bf76-5ed9677f3b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typ-8</value>
      <webElementGuid>11c95ed6-2830-4e37-bfb1-ee75eaf95c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d1cf1a71-f3e4-484c-b2d7-7c17ad0f9190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>03fcbad4-f59e-4bd5-a765-ae92fd83d82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typ-8</value>
      <webElementGuid>e89813e3-0234-49d3-96e3-511dbe6a839b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typkriteria</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>e3b456ab-9f30-4c92-a52f-fad86660a191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>conditional-napoveda-8</value>
      <webElementGuid>4eb33d23-a81f-47b1-81e1-071fc0b3569c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2c21d914-8fa6-4e0b-a940-bacf10f89374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>788</value>
      <webElementGuid>ceb568ec-eab3-41bb-b253-ea52790b4001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typ-8&quot;)</value>
      <webElementGuid>237e0058-4453-4f16-86ce-a1e705fae1d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typ-8']</value>
      <webElementGuid>567a8cf7-7a12-423e-9498-90bf2b477df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rbSkutocnost-8']/fieldset/div/div/input</value>
      <webElementGuid>7f51f673-8c13-462d-97a0-80ec9c7e9ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/div/input</value>
      <webElementGuid>80a16b42-968a-448f-aba0-91935810054e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'typ-8' and @type = 'radio' and @id = 'typ-8']</value>
      <webElementGuid>c8a800fc-3d32-4566-92d6-76f06d605167</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
