<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Oznamu o monosti predkladania iadost _3ca0bd</name>
   <tag></tag>
   <elementGuidId>d4c00c9e-66ce-454a-8db8-3cc6bd612110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#typ-5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='typ-5']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d9d5aaf-88ba-4837-82ca-ab702325b274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>804df11b-53cb-4860-a210-ada1d57fee00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>typ-5</value>
      <webElementGuid>1e226ca2-7a26-42d1-91bc-927bf2c931e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ccce9a22-d6ef-4a87-ae34-aa9f71a0c669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>19d75fb0-6792-4ba6-bb0f-674653e7739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>typ-5</value>
      <webElementGuid>83933f3f-04ed-4819-9b7b-d7224580f288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>typkriteria</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a2b9ac24-b9c1-49b4-81c3-ecf8ec7af86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>conditional-napoveda-5</value>
      <webElementGuid>eb96e8cd-5a23-4763-ada4-234d04f398a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>783519ee-af01-489e-bb6b-f4cb75536b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;typ-5&quot;)</value>
      <webElementGuid>81ebbd05-ff2b-407b-b22b-fd84bfb8c533</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='typ-5']</value>
      <webElementGuid>2371b4c4-5975-42e6-974d-df228559a515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rbSkutocnost-5']/fieldset/div/div/input</value>
      <webElementGuid>c5bdac29-bae9-41cf-bdfd-2bf8a698cb46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/fieldset/div/div/input</value>
      <webElementGuid>a1419627-767c-4451-8ef1-1a097e1c5fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'typ-5' and @type = 'radio' and @id = 'typ-5']</value>
      <webElementGuid>481a47f3-f119-4edc-b71a-647d422f1f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
