<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte adresu koly_UI_V_ZP_in_SkolaS_4fb274</name>
   <tag></tag>
   <elementGuidId>e8c1b408-1bd6-435c-a6f5-7c68b9a3bc9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ec42c497-6e8b-49c0-b6ce-5a9f632675cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input</value>
      <webElementGuid>bbd4e57d-12d9-4265-bae4-0e6b5f17e685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control</value>
      <webElementGuid>5d9c296c-5f14-40cc-9906-6e821c825843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control</value>
      <webElementGuid>03a28c5f-a919-414c-9f03-3e944bd670dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8b349908-34a1-4ecb-82c1-b5df2b861574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-hint</value>
      <webElementGuid>ae65af8e-d532-4eb0-b322-4aa8e2de06e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control&quot;)</value>
      <webElementGuid>b06c2acf-992b-4d28-a052-55bcd3179050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>492</value>
      <webElementGuid>f2977f0c-bbe0-465d-983a-c8acb9205968</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control']</value>
      <webElementGuid>5dc3b0aa-468c-4540-b9cb-6c9cc352a94b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_AdresaSkoly']/input</value>
      <webElementGuid>6487c8ea-9425-4e45-ad56-19ef6b3aa057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[3]/input</value>
      <webElementGuid>6fc9bf4f-21c8-4b68-873e-56003b5b9f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control' and @name = 'UI_V_ZP_in_SkolaSlovenska_AdresaSkoly-control' and @type = 'text']</value>
      <webElementGuid>08fd5956-c05e-481d-bfb5-1959994f0757</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
