<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mesiac_UI_V_ZP_in_SkolaSlovenska_Datu_9c1a47</name>
   <tag></tag>
   <elementGuidId>3f09bae9-5833-4df8-a99e-1fbd6a44abd7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04838dc3-c739-4c59-a3a8-984afea4fb74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>17872dcc-5b0e-4db9-b654-188677f91e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>9fd8f43d-9dc5-40db-90c7-fa8aaf44c696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Predpokladaný dátum štátnej skúšky. </value>
      <webElementGuid>59d3d29d-4c7d-41cb-a383-e92b8f4a3af4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month</value>
      <webElementGuid>36bb2048-f6b4-4a3c-80d9-dae6c2546469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>0d1bb892-8733-4ed6-b16a-d632c8c2f29b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month</value>
      <webElementGuid>4bcb0e33-9bd4-48cc-8c69-0701ab7ce019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month&quot;)</value>
      <webElementGuid>24f88c8b-a16c-4ace-8c1d-d8d27de9531d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month']</value>
      <webElementGuid>7f522a64-f98e-44c2-9c0b-b1661401d407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-control']/div/div/input</value>
      <webElementGuid>ffa448f7-40bb-43d8-800d-eb6ac8ec70d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div/input</value>
      <webElementGuid>8e5f20df-4abb-49a0-8395-28b5876b1678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Predpokladaný dátum štátnej skúšky. ' and @id = 'UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month' and @name = 'UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-month']</value>
      <webElementGuid>d0e2bfd7-95c4-43d6-948a-49927bec26ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
