<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_shlasm so zskanm dajov z referennch r_c9102a</name>
   <tag></tag>
   <elementGuidId>28be9be5-8e6d-4c7b-a5a7-a1b378a5d558</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_CHB_PravdiveUdaje-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_CHB_PravdiveUdaje-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d584494-f50c-4a54-85ba-3d1d1b0236d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>f47805e2-a08e-4b5e-8ab2-4ab935846013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_PravdiveUdaje-control</value>
      <webElementGuid>77594f7b-26e4-41dc-9b49-93d843f8d4ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_PravdiveUdaje-control</value>
      <webElementGuid>a51872b1-18c2-4ed0-930d-e8279b59e914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ea6952a3-ed77-44c2-b98b-c493fbd2bf1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>32f92dcb-621a-4158-90af-8c765bcf0523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_CHB_PravdiveUdaje-control&quot;)</value>
      <webElementGuid>4d95519c-a033-4f80-a2e3-f3655ac2c9fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_CHB_PravdiveUdaje-control']</value>
      <webElementGuid>0aadec32-9ff7-4f54-be7b-b1f4001f6e42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_CHB_PravdiveUdaje']/div/div/input</value>
      <webElementGuid>a07bb537-2c4a-480e-8467-d5e189f64792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/div/div/input</value>
      <webElementGuid>b767111f-9bbd-460c-b703-2284a8d3a4b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_CHB_PravdiveUdaje-control' and @name = 'UI_V_ZP_in_CHB_PravdiveUdaje-control' and @type = 'checkbox']</value>
      <webElementGuid>c2f6934c-cdd9-4271-8d5c-86f038b50a98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
