<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zobrazi detail_UI_V_ZP_in_SkolaSloven_03cebd</name>
   <tag></tag>
   <elementGuidId>15ca61e6-6c7b-4aee-8bc6-a1d2a580bddc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1102294d-a635-438b-964d-7c9c9d7ac912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>0f77593a-f463-4d08-86ec-5f04b6761f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1</value>
      <webElementGuid>6939b5be-c8b4-42ad-bba2-cd8dfa007003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-group</value>
      <webElementGuid>25bf34f3-ba67-4852-950d-fcda3481810e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>633f1e85-c2e8-45ad-8254-62fb9d84ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>107c5fd1-4e60-4971-a44a-2b70e64413a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1&quot;)</value>
      <webElementGuid>bcf2574e-8ed2-4ffc-834e-a4ccba4aedaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>538</value>
      <webElementGuid>fa92f78a-1fa8-43c3-85cb-b47c7e213b8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1']</value>
      <webElementGuid>19b815dd-6942-453a-a08e-200e8688d792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DlzkaStudia']/fieldset/div/div/input</value>
      <webElementGuid>f9ec21f8-9eb5-4f40-92c1-5fbd89ce43fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/fieldset[2]/div[7]/fieldset/div/div/input</value>
      <webElementGuid>24cc9c92-5959-4eb5-985e-ba1464ea1ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-1' and @name = 'UI_V_ZP_in_SkolaSlovenska_DlzkaStudia-group' and @type = 'radio']</value>
      <webElementGuid>f5abcd4b-0dfc-4730-b74c-6774b43ce4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
