<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mesiac_UI_V_ZP_in_DalsieStudiumSloven_ae0432</name>
   <tag></tag>
   <elementGuidId>1d5b1e5f-3614-40ff-96c5-441da510292e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b78e5dd-1f5f-4528-8eb0-5593098118cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d1e05aee-80de-4a31-a3db-a8c9da7cb481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>0f4420fa-92a4-4424-8203-779d28729093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Predpokladaný dátum štátnej skúšky. </value>
      <webElementGuid>9b34d59e-4326-47c8-813c-1ad2a07944c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month</value>
      <webElementGuid>ec123d46-dd15-4f26-a180-6a1da30c69af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>01d81038-0214-4e7f-9cfa-14001235d146</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month</value>
      <webElementGuid>b5e7e05b-d353-457f-91e3-25072287b7b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month&quot;)</value>
      <webElementGuid>72559f25-5645-4da5-94d9-79bf5caf2d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month']</value>
      <webElementGuid>89302568-701d-47a6-83b7-964a136c599d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-control']/div/div/input</value>
      <webElementGuid>94f1fb68-dcbb-435f-ae59-793c3e0d288a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/input</value>
      <webElementGuid>ad568ddf-530c-41db-87a1-e7e45340738b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Predpokladaný dátum štátnej skúšky. ' and @id = 'UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_DatumStatnejSkusky-month']</value>
      <webElementGuid>2ac5e0bf-640c-4ea6-839f-dbd625ab12e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
