<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zhoduje sa Vaa korepondenn adresa s a_6ce0fa</name>
   <tag></tag>
   <elementGuidId>00bd4fb3-e009-4093-acc6-aa9b8c4b8c0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e5e86d60-0434-423d-93d6-1f456e959fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>42827299-9df4-4b39-b416-d38a42dc32bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1</value>
      <webElementGuid>0355355a-4208-419c-be06-1b48e60386d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-group</value>
      <webElementGuid>a6e9ccbd-be50-469a-8b91-5e239f296dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dedfe7d1-6e39-4e42-aa28-d1203b42e8f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a4641093-ec7f-4d45-a65f-923140cd80e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>374</value>
      <webElementGuid>636d55d7-42c2-460f-ad33-f69e974f33c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1&quot;)</value>
      <webElementGuid>65baebe7-75f8-4da9-b0d7-b2d22f414682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1']</value>
      <webElementGuid>19abac32-f386-4959-84a1-d85f1f94a4ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy']/fieldset/div/div/input</value>
      <webElementGuid>082da25f-cede-4e31-a3f0-f304a7a17cab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[4]/div/fieldset/div/div/input</value>
      <webElementGuid>236e4ed3-bf22-482f-ab95-c6393f6fd24a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-1' and @name = 'UI_V_ZP_in_ZhodaAdresy_ZhodaAdresy-group' and @type = 'radio']</value>
      <webElementGuid>7892763c-93ca-4d37-b725-d1fdb6577aff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
