<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_II. stupe_UI_V_ZP_in_DalsieStudiumSlo_199592</name>
   <tag></tag>
   <elementGuidId>6c1a7751-bf5e-4c36-96cb-82644f21f7c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62c2a3d4-baf0-4dfa-890d-0dad3c68a559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>b17b9132-817a-434c-ab62-215d000a5958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3</value>
      <webElementGuid>7ad27f94-e9b3-4d2c-a544-0e00b3da3c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-group</value>
      <webElementGuid>159c4143-2d34-40d0-8a54-886dabaca5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a1e661c9-9396-418e-b193-05466e430ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>bdfcfdc5-807f-4536-b79b-934d92ea76a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3&quot;)</value>
      <webElementGuid>0c89dfa2-b66a-428e-9156-04757890acc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3']</value>
      <webElementGuid>7eff722f-cf89-43f6-815a-6da33efd01e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania']/fieldset/div/div[3]/input</value>
      <webElementGuid>7f5a3a97-af30-48d1-8125-c681c2047c5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/fieldset/div/div[3]/input</value>
      <webElementGuid>1207a9be-9bb1-4392-9981-2a5431adf046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-input-3' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_StupenVzdelania-group' and @type = 'radio']</value>
      <webElementGuid>580be699-0398-4faf-ad5c-16206be41004</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
