<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mesiac_UI_V_ZP_in_SkolaSlovenska_Datu_c1c0f2</name>
   <tag></tag>
   <elementGuidId>9304d396-37f1-4346-9ea2-b156e42ef778</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79d9bf33-5886-4d9f-9a8a-f203530ea95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a78cc810-ceee-41e2-a54a-585ab2f8558f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>bdb44ac7-b6d6-4172-88ed-17b23d8a7e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dátum zápisu na štúdium v aktuálnom akademickom roku </value>
      <webElementGuid>a4febb30-79c8-407b-b097-d1e06e06ee5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month</value>
      <webElementGuid>efb26c23-e76e-43b4-b4f5-2e2f8090f42d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>48666f27-359b-4f23-95b1-5601a8e153b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month</value>
      <webElementGuid>5abe4846-d43f-49bd-92a7-52feda90331a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month&quot;)</value>
      <webElementGuid>fb4dbd64-3ada-4526-9025-a3850513e440</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month']</value>
      <webElementGuid>28d88d82-2f0e-4a25-8cae-ccff6b671733</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-control']/div[2]/div/input</value>
      <webElementGuid>3398e3f8-a8e5-4dad-9c1f-2329c48e49c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a30ce660-1f32-43af-8abc-3127fca55457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Dátum zápisu na štúdium v aktuálnom akademickom roku ' and @id = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month' and @name = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-month']</value>
      <webElementGuid>7a0a1852-200b-4d68-82e8-a6c4c024f09c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
