<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_De_UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day</name>
   <tag></tag>
   <elementGuidId>ad7ca975-d8b3-484d-9f49-ddf5ad6e4ff7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dedb06da-ecb6-42bf-a229-c5e7eeaef588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f69a66ab-d049-4d20-8e4d-37c9f7266f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-2</value>
      <webElementGuid>49862d07-12e9-4d66-ba30-6e39b790744f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Dátum zápisu na štúdium v aktuálnom akademickom roku. </value>
      <webElementGuid>09e4beec-a1da-4384-ad2b-4f9078a79cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day</value>
      <webElementGuid>7748b878-3f9d-4db4-8320-b99392233ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>762067b7-65b1-490a-b411-c92b56ad70fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day</value>
      <webElementGuid>3b9cacc0-3ad1-41bb-8d1b-5382451221db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day&quot;)</value>
      <webElementGuid>3249188a-cf33-4670-9673-ad16b2210293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day']</value>
      <webElementGuid>65dfd48b-d883-4cab-a4b7-6d8f47ba6809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DatumZapisu-control']/div/div/input</value>
      <webElementGuid>c68e10c9-2113-4259-b2d4-1767303e1287</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/input</value>
      <webElementGuid>daec9ee0-7ba4-4c8b-becc-910c58c02f7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Dátum zápisu na štúdium v aktuálnom akademickom roku. ' and @id = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day' and @name = 'UI_V_ZP_in_SkolaSlovenska_DatumZapisu-day']</value>
      <webElementGuid>3714095a-147e-4c0f-a752-be3c10c6eff6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
