<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ttna prslunos_UI_V_ZP_in_Identifikacn_033c20</name>
   <tag></tag>
   <elementGuidId>d291b301-9c7f-433d-8f8a-0d5b52867846</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>36b8d377-1841-45a1-bc3a-819e843109ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-radios__input</value>
      <webElementGuid>59a162fd-6570-43fc-8961-3bcc51a57c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1</value>
      <webElementGuid>32b543e2-fef1-46fe-9dea-dfe29cb2a18f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-group</value>
      <webElementGuid>c1f28d82-70ee-4f25-b530-7c9d0d2a01b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>77899a10-b40e-4ead-b0d8-8a53d23cebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d29cbf6-4ff5-487c-937e-3771bfb7e739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d1bd1b22-e380-4f18-a159-2a45c605f358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1&quot;)</value>
      <webElementGuid>6c123011-9cad-4243-a9c8-e28d12a3c3bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1']</value>
      <webElementGuid>0c1329e7-f7d5-4c9c-b116-dc647ea4e355</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost']/fieldset/div/div/input</value>
      <webElementGuid>6aaf1808-2c85-4a48-91bc-c96f961e8d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/input</value>
      <webElementGuid>8f59da89-eb45-4cf0-80b9-c46cf0358b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-1' and @name = 'UI_V_ZP_in_IdentifikacneUdaje_StatnaPrislusnost-group' and @type = 'radio']</value>
      <webElementGuid>b2485a1f-63eb-4924-a90a-93d37776cdff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
