<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Potvrdenie o nvteve V v SR (iadate)_s_46946e</name>
   <tag></tag>
   <elementGuidId>afb26019-0fc2-407e-b74d-0e876374e08c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#suhlasim-so-ziskanim-z-registrov</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='suhlasim-so-ziskanim-z-registrov']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bff7a49e-c0a7-4938-8561-9263fb114c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>suhlasim-so-ziskanim-z-registrov</value>
      <webElementGuid>3b2c6bba-865c-40b4-9280-25a440c17b97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>bd94e3f5-83c8-4806-b104-ac3afb46a2e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0187032a-1938-431a-aad0-fe9abe735e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;skutocnosti-prilohy-1&quot;)/fieldset[@class=&quot;govuk-fieldset&quot;]/div[@class=&quot;detail-prilohy-section&quot;]/div[@id=&quot;referencne-registre&quot;]/div[@class=&quot;govuk-checkboxes govuk-form-group&quot;]/div[@class=&quot;govuk-checkboxes__item govuk-checkboxes govuk-checkboxes--small&quot;]/input[@id=&quot;suhlasim-so-ziskanim-z-registrov&quot;]</value>
      <webElementGuid>a3ade9d6-2584-4319-860b-a38643965812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='suhlasim-so-ziskanim-z-registrov']</value>
      <webElementGuid>029057c8-3717-4251-a755-916f74867ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='referencne-registre']/div/div/input</value>
      <webElementGuid>646c8047-3993-4835-931c-cd32cdcdec86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/fieldset/div/div/div/div/input</value>
      <webElementGuid>88bcba38-2693-4b6f-8d6f-4842c5cb67d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'suhlasim-so-ziskanim-z-registrov' and @type = 'checkbox']</value>
      <webElementGuid>a1027a9d-3953-4c9c-865d-efedc7effe03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
