<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rok_UI_V_ZP_in_SkolaSlovenska_DatumSt_7956e6</name>
   <tag></tag>
   <elementGuidId>516e5f51-6f5f-4859-a53e-7fbda54ed86d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ceaa66de-b8ce-46f6-96a8-65918116b93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7872686-6909-470e-83c8-c7d46b1e81fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input govuk-date-input__input govuk-input--width-4</value>
      <webElementGuid>f7014035-6105-46b3-b708-eb5716ebb08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Predpokladaný dátum štátnej skúšky. </value>
      <webElementGuid>7bbe7fbd-4918-49d1-b282-a78a637ace79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year</value>
      <webElementGuid>d8b2aa54-1ef0-4985-bf89-bfe6632e8df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>11fe3a4d-fef0-46e8-b1a6-ccbeb22e2fa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year</value>
      <webElementGuid>e1969157-caa7-4f13-a946-d54742be62d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year&quot;)</value>
      <webElementGuid>15082265-6c74-4f17-aa87-05e2277455da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year']</value>
      <webElementGuid>1972efca-95ba-4091-8eda-dc6ccb6432be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-control']/div[2]/div/input</value>
      <webElementGuid>d213b281-4de9-4922-b761-f63740cd1204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/input</value>
      <webElementGuid>ae932555-04ab-4116-9b50-e40f798abcb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@title = 'Predpokladaný dátum štátnej skúšky. ' and @id = 'UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year' and @name = 'UI_V_ZP_in_SkolaSlovenska_DatumStatnejSkusky-year']</value>
      <webElementGuid>2b3edd4b-f23d-448a-aac7-adc4331eea43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
