<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_www.fnpv.sk_UI_V_ZP_in_CHB_OsobneUdaj_50afb9</name>
   <tag></tag>
   <elementGuidId>de6721cc-f41d-4eaf-b02f-3a6d3e1a7511</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_CHB_OsobneUdaje-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_CHB_OsobneUdaje-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88be6cc1-6e01-48f4-9513-ad3757dde375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-checkboxes__input</value>
      <webElementGuid>8e47e3c2-de09-4b97-9096-690f4e8c085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_OsobneUdaje-control</value>
      <webElementGuid>779f6e47-f0e3-4ab3-9ca6-934a3ca99f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_CHB_OsobneUdaje-control</value>
      <webElementGuid>2b7d0c80-559e-4876-a1b5-3384a6c35be5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>8f66fa9a-9f4a-4c84-9a60-6f172e5f3ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>caadda0d-db46-40b0-bfd8-437a2e1d93c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_CHB_OsobneUdaje-control&quot;)</value>
      <webElementGuid>f684e035-0d5b-425f-b725-56d78314f490</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_CHB_OsobneUdaje-control']</value>
      <webElementGuid>61032cc6-ff32-40c1-9c9e-6fa616fd09a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_CHB_OsobneUdaje']/div/div/input</value>
      <webElementGuid>26859968-d752-4a28-aafe-cac359642378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>2f0046e8-465e-445c-9a8b-827c3f586171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_CHB_OsobneUdaje-control' and @name = 'UI_V_ZP_in_CHB_OsobneUdaje-control' and @type = 'checkbox']</value>
      <webElementGuid>7426424a-dd5e-40c1-b408-48b4b8987562</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
