<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zadajte miesto odoslania iadosti_UI_V_59ba54</name>
   <tag></tag>
   <elementGuidId>2de67da7-48a9-4e89-a70b-33da767d159f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>33ec0d72-8d20-4e4e-a5aa-d920d5ebd4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-input </value>
      <webElementGuid>1e4cb328-7e1a-4050-98f3-c98997d71638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      <webElementGuid>e6a04fd3-6bb9-4a3a-82cf-24e8ce10d602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control</value>
      <webElementGuid>6328da07-abc7-4371-8308-9fd0722a4ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd6392c3-7916-4869-828d-7678ce2fd3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-hint</value>
      <webElementGuid>ea03435c-fdd6-4cb7-a232-6da655d02bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control&quot;)</value>
      <webElementGuid>21ebcd69-70f6-4976-b8b9-dab64b97aaa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control']</value>
      <webElementGuid>f10398fc-6fb5-470f-98c7-724d34943c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania']/input</value>
      <webElementGuid>d0c6cf2b-10a4-4582-aea4-141e81f82b5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/fieldset/fieldset/div/input</value>
      <webElementGuid>2669f15b-3599-4731-a8d4-aee184da3b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control' and @name = 'UI_V_ZP_in_DatumAMiestoOdoslania_MiestoOdoslania-control' and @type = 'text']</value>
      <webElementGuid>ec4ac52e-ad04-4f24-ae69-c75666445fee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
