<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vber Evanjelick bohosloveck fakulta _9b66ac</name>
   <tag></tag>
   <elementGuidId>6c2eb2b7-94a4-457c-81ca-6ec1ce1ade87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e58f979c-3863-40b0-8377-3bc8f84a2f96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>afd97c6b-a89c-49bb-9e36-b61759796a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control</value>
      <webElementGuid>c5668f8f-b5fd-40c1-bcfa-920ca06039e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control</value>
      <webElementGuid>ea3fc7cb-ff40-4953-8396-ba638c6abaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Výber Evanjelická bohoslovecká fakulta Fakulta managementu Fakulta matematiky, fyziky a informatiky Fakulta sociálnych a ekonomických vied Fakulta telesnej výchovy a športu Farmaceutická fakulta Filozofická fakulta Jesseniova lekárska fakulta v Martine Lekárska fakulta Pedagogická fakulta Právnická fakulta Prírodovedecká fakulta Rímskokatolícka cyrilometodská bohoslovecká fakulta</value>
      <webElementGuid>2a5ffe45-a2b5-4cd9-866e-baf9ea8a1027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control&quot;)</value>
      <webElementGuid>16a4bcc5-0b81-4f09-ab3c-de6ab29c8215</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control']</value>
      <webElementGuid>3590631c-67b1-4844-a773-337c2c0e9ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty']/select</value>
      <webElementGuid>257e531a-b216-4080-a135-7a360be83024</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[2]/following::select[1]</value>
      <webElementGuid>4f3010c0-fb16-44ad-87e8-6e945f6507b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[2]/following::select[1]</value>
      <webElementGuid>f167bfb7-433c-49ad-be84-b4c7a9dcc29a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aktuálne navštevovaný stupeň VŠ vzdelania'])[2]/preceding::select[1]</value>
      <webElementGuid>0dd085c4-86fe-4a1e-aa15-57189a58e0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I. stupeň'])[2]/preceding::select[1]</value>
      <webElementGuid>e6f3fc94-737d-4a6a-8549-6331b8b2d9cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/select</value>
      <webElementGuid>d5e8b6f3-e043-4c84-94b0-69a6ef051b7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovFakulty-control' and (text() = ' Výber Evanjelická bohoslovecká fakulta Fakulta managementu Fakulta matematiky, fyziky a informatiky Fakulta sociálnych a ekonomických vied Fakulta telesnej výchovy a športu Farmaceutická fakulta Filozofická fakulta Jesseniova lekárska fakulta v Martine Lekárska fakulta Pedagogická fakulta Právnická fakulta Prírodovedecká fakulta Rímskokatolícka cyrilometodská bohoslovecká fakulta' or . = ' Výber Evanjelická bohoslovecká fakulta Fakulta managementu Fakulta matematiky, fyziky a informatiky Fakulta sociálnych a ekonomických vied Fakulta telesnej výchovy a športu Farmaceutická fakulta Filozofická fakulta Jesseniova lekárska fakulta v Martine Lekárska fakulta Pedagogická fakulta Právnická fakulta Prírodovedecká fakulta Rímskokatolícka cyrilometodská bohoslovecká fakulta')]</value>
      <webElementGuid>1a1a064f-755a-45e7-8982-6aaea0e05f64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
