<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1                                   _4271de</name>
   <tag></tag>
   <elementGuidId>43414fed-832c-44a8-a411-565c0c6ca9bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d43bf7b9-c24e-4f4c-b47f-689b5142eae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>5883aec3-ad76-4c59-a697-5946c81a3f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control</value>
      <webElementGuid>71bcf636-cb88-4058-b87e-068ed7925d8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control</value>
      <webElementGuid>ee8dba30-04c1-4c69-afc7-ee09dac47feb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            
                                                            1
                                                            2
                                                            3
                                                            4
                                                            5
                                                            6
                                                        </value>
      <webElementGuid>f5d30fdf-4cbf-4519-9860-5d3e9bc0dd93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control&quot;)</value>
      <webElementGuid>f1c1da91-4334-4da5-ad04-c3f7a2f1f793</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control']</value>
      <webElementGuid>dda4fdf7-bfc6-436d-ac4b-f5f9c24270fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS']/select</value>
      <webElementGuid>1590e958-0bfb-4cf8-bbe1-24c1571533b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ročník'])[2]/following::select[1]</value>
      <webElementGuid>fc3accba-2894-475c-9199-4b9a1c6a70ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='III. stupeň'])[2]/following::select[1]</value>
      <webElementGuid>1f6b7f97-cb1e-470d-bfac-b9cf6ed2570e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Predpokladaný dátum štátnej skúšky'])[2]/preceding::select[1]</value>
      <webElementGuid>a5b517db-2479-459f-b932-403d3bf67409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zobraziť detail'])[3]/preceding::select[1]</value>
      <webElementGuid>c05aa21b-f18f-4a28-989a-4b7537e565d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/select</value>
      <webElementGuid>d6833504-af68-41a9-9096-d1c7b8767f3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_RocnikVS-control' and (text() = '
                                                            
                                                            1
                                                            2
                                                            3
                                                            4
                                                            5
                                                            6
                                                        ' or . = '
                                                            
                                                            1
                                                            2
                                                            3
                                                            4
                                                            5
                                                            6
                                                        ')]</value>
      <webElementGuid>4be7458c-f19b-41ce-a1a4-e68c9b314c97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
