<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vber Fakulta priemyselnch technolgi _aa995f</name>
   <tag></tag>
   <elementGuidId>05abb782-150b-45f0-b4f3-003c0e81906a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>04c6cb76-6e25-4639-a47d-1f887fa3a015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>e33f7509-50fc-438e-b816-d0d32ab65e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control</value>
      <webElementGuid>5bbeb029-9d36-4b5f-8e7e-b2e8fc2c6b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control</value>
      <webElementGuid>88c2bfad-7714-4576-9c72-1fa7e277305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Výber Fakulta priemyselných technológií v Púchove Fakulta sociálno-ekonomických vzťahov Fakulta zdravotníctva Fakulta špeciálnej techniky</value>
      <webElementGuid>6188049e-d3cd-448b-8c8b-effdbdb141ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control&quot;)</value>
      <webElementGuid>9390a0f5-63d8-4358-8c87-f67c2fbd61a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>433</value>
      <webElementGuid>410cac1f-e058-4579-972d-d2c657ad5765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control']</value>
      <webElementGuid>c33c71d7-b377-4c6c-8673-ad2593671080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_NazovFakulty']/select</value>
      <webElementGuid>608e096c-2dd1-493e-9592-5b126e87e97c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[1]/following::select[1]</value>
      <webElementGuid>20ab50af-cbe5-4e7b-aff7-0fde72466a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[1]/following::select[1]</value>
      <webElementGuid>06e895b9-334a-42c7-9525-5cda945aa2a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Adresa školy'])[1]/preceding::select[1]</value>
      <webElementGuid>9f9d8673-7af0-412e-a8d1-d2ee2582be96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte adresu školy.'])[1]/preceding::select[1]</value>
      <webElementGuid>2dbfc331-cf9b-40d8-a1b2-de823619067d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>0cb3e57e-edac-4f46-87a9-9a8b1801e16b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control' and @name = 'UI_V_ZP_in_SkolaSlovenska_NazovFakulty-control' and (text() = ' Výber Fakulta priemyselných technológií v Púchove Fakulta sociálno-ekonomických vzťahov Fakulta zdravotníctva Fakulta špeciálnej techniky' or . = ' Výber Fakulta priemyselných technológií v Púchove Fakulta sociálno-ekonomických vzťahov Fakulta zdravotníctva Fakulta špeciálnej techniky')]</value>
      <webElementGuid>3a5c7dfc-f1cb-4dbd-ac22-a4d267b7ced4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
