<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Hlavn                               _477f09</name>
   <tag></tag>
   <elementGuidId>b8f72d2b-c112-4e3c-87ad-e141ad27c34f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//select[@name='Studium'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'Studium' and (text() = '
                                                            
                                                            Hlavné
                                                            Súbežné
                                                            Nenavštevujem
                                                        ' or . = '
                                                            
                                                            Hlavné
                                                            Súbežné
                                                            Nenavštevujem
                                                        ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb0f73b0-e890-4328-9b1e-b471e5105712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>e4a3382f-0a77-40b8-98eb-32ab32da5484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Studium</value>
      <webElementGuid>e31199e4-3b7e-45fc-a79b-d8e1098b760d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                            
                                                            Hlavné
                                                            Súbežné
                                                            Nenavštevujem
                                                        </value>
      <webElementGuid>282a004c-6cd2-4013-b622-5606e15975df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tabulkaStudium&quot;)/tbody[@class=&quot;govuk-table__body&quot;]/tr[2]/td[@class=&quot;govuk-table__cell&quot;]/select[@class=&quot;govuk-select&quot;]</value>
      <webElementGuid>0c875bb7-c038-40e4-9531-d76f4bde922b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>424</value>
      <webElementGuid>ef4d0c48-f961-4117-9cc3-801b1de5bc01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//select[@name='Studium'])[2]</value>
      <webElementGuid>d6df2f4a-2624-4353-8094-0b26579ca0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tabulkaStudium']/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>5152353b-ba4a-48c7-baba-a4e560cb4160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trenčianska univerzita Alexandra Dubčeka v Trenčíne'])[2]/following::select[1]</value>
      <webElementGuid>412bac92-ef4b-40ab-a0a3-feb222e2a323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trenčianska univerzita Alexandra Dubčeka v Trenčíne'])[1]/following::select[1]</value>
      <webElementGuid>e8dee66c-21d1-45e9-8579-6ab56fe2bf5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Univerzita Komenského v Bratislave'])[1]/preceding::select[1]</value>
      <webElementGuid>9f141ef9-5b23-41e2-99f2-c9e23114f216</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lekárska fakulta'])[1]/preceding::select[1]</value>
      <webElementGuid>ed8f287c-739e-4fd8-9691-bcec9530faac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/select</value>
      <webElementGuid>3a593e8e-9b20-4657-b560-1b99fdeeb76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Studium' and (text() = '
                                                            
                                                            Hlavné
                                                            Súbežné
                                                            Nenavštevujem
                                                        ' or . = '
                                                            
                                                            Hlavné
                                                            Súbežné
                                                            Nenavštevujem
                                                        ')]</value>
      <webElementGuid>af9d3658-fab3-463d-9a3d-d0f23a4dd4fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
