<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vber Akadmia ozbrojench sl generla M_e1eb3a_1</name>
   <tag></tag>
   <elementGuidId>5e66cce4-84f5-4e9c-b23b-a5474fd354b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b6e58d5-1824-444a-baee-90089f7e3265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>72248c2c-760b-4394-a50a-b0587767a037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      <webElementGuid>9aa666cf-ce51-4db7-9a75-0e56c428bcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      <webElementGuid>47509256-4f33-4e05-b016-6f7d3cc835bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>572</value>
      <webElementGuid>4de02fb0-8802-4c8a-8523-5f044d70b016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline</value>
      <webElementGuid>ce6605c7-b937-4cd2-a2ba-b672c061811e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control&quot;)</value>
      <webElementGuid>d1a3304c-135e-43a8-a7f2-0014a5e7caf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control']</value>
      <webElementGuid>ed07ebf1-798c-40c6-bd4e-350bd2fca200</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly']/select</value>
      <webElementGuid>ece10f5c-81a2-43bb-afce-da5658b46089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov vysokej školy, kde študujete.'])[2]/following::select[1]</value>
      <webElementGuid>ea096c0e-39a1-49df-bdd5-265c7253aad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov vysokej školy'])[2]/following::select[1]</value>
      <webElementGuid>06205971-ab29-4dbd-a38d-193806439722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[2]/preceding::select[1]</value>
      <webElementGuid>fb90018d-47c9-4f29-a794-c2272ab045e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[2]/preceding::select[1]</value>
      <webElementGuid>3e2bd0b0-328a-49e8-8298-8550249cc905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>8d1f185c-f3eb-43d9-ba0d-873a625174bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and (text() = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline' or . = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline')]</value>
      <webElementGuid>698c2199-d7ac-4f21-8092-d65700fcd135</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
