<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vber Akadmia ozbrojench sl generla M_e1eb3a_1 (1)</name>
   <tag></tag>
   <elementGuidId>5b01c150-0847-41d6-a0cc-3512aac43b92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cea77337-259d-4b28-af05-efe8669a5a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>b2787516-6fb7-475e-a8a1-5f857374469a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      <webElementGuid>2e46f7e3-251c-4175-9d94-c39c1fcd3a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control</value>
      <webElementGuid>961186c3-1f22-4e63-8214-acf58e5c6882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>572</value>
      <webElementGuid>f2ada0ec-16b3-4d6c-8ecc-d3b3aeb7ad4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline</value>
      <webElementGuid>bc5cfaf7-975b-4e6c-9c23-4195cc9e536d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control&quot;)</value>
      <webElementGuid>1b70aa91-2a7d-4446-ab8d-3bfbb5d0c401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control']</value>
      <webElementGuid>14164d4b-c7dc-47fa-b586-dc3f468e1b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly']/select</value>
      <webElementGuid>d385d8b5-600a-4515-b974-97b3bcc187cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov vysokej školy, kde študujete.'])[2]/following::select[1]</value>
      <webElementGuid>cad64f00-5df7-4622-841f-7aeb5c854d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov vysokej školy'])[2]/following::select[1]</value>
      <webElementGuid>c95bf7b8-afd0-43f0-807b-907c4f77325f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[2]/preceding::select[1]</value>
      <webElementGuid>26e1a885-bccd-4bc4-bf2e-45f0a86fae97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[2]/preceding::select[1]</value>
      <webElementGuid>4443bf04-c2a0-4751-8395-9e4fde233855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>0fbbf503-9d85-4ab0-b314-e9a1f6ec9abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and (text() = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline' or . = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline')]</value>
      <webElementGuid>a2ea2c77-528c-43d3-8e21-e9ca3a514c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
