<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Vber Akadmia ozbrojench sl generla M_e1eb3a</name>
   <tag></tag>
   <elementGuidId>b9d4900d-3014-40b7-a538-5c780a888ff0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e58f956d-3c49-47ce-a769-f9ffb0c890c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>3773e9d5-bbd3-4edd-b96e-59dea394b972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control</value>
      <webElementGuid>47bd8681-ba19-47bc-ab13-d2883da1ddfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control</value>
      <webElementGuid>a8ee42e9-a05a-47cf-972b-2bd1807a5643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline</value>
      <webElementGuid>7867ec81-a32a-4b12-b05b-d7573e26e4bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control&quot;)</value>
      <webElementGuid>3802a998-1bd4-4ef6-a3a0-1aec20605fee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>456</value>
      <webElementGuid>00b203d5-52cf-4af8-8117-3340c2c48517</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control']</value>
      <webElementGuid>a4ada85d-a3b1-438a-a37d-f185bbc8deb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_NazovSkoly']/select</value>
      <webElementGuid>230dfb9e-489e-4a41-bf2c-eefe79ded01d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov vysokej školy, kde študujete.'])[1]/following::select[1]</value>
      <webElementGuid>566646d3-78c8-4034-a9bc-16b379eef13c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov vysokej školy'])[1]/following::select[1]</value>
      <webElementGuid>d27ab733-1456-4741-93f2-86a405fdbf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[1]/preceding::select[1]</value>
      <webElementGuid>72b111ab-86ae-4452-9f2d-90e1bc233b05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[1]/preceding::select[1]</value>
      <webElementGuid>537a7feb-05e8-4127-abfc-d373f3961245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset[2]/div/select</value>
      <webElementGuid>b6c2eeec-2306-4fa2-bde4-7b6e164e6734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control' and @name = 'UI_V_ZP_in_SkolaSlovenska_NazovSkoly-control' and (text() = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline' or . = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline')]</value>
      <webElementGuid>9590cf7a-1fb8-41f7-a16a-48f8a2233fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control']</value>
      <webElementGuid>ecd17115-68c4-41ab-b221-3264d12a826c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly']/select</value>
      <webElementGuid>fbc53113-4882-419c-9851-4442b10574c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov vysokej školy, kde študujete.'])[2]/following::select[1]</value>
      <webElementGuid>6a76c033-a465-48c3-adde-1baf35f09cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov vysokej školy'])[2]/following::select[1]</value>
      <webElementGuid>4a0910a7-ec9d-4288-bc4d-a927315ee4df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Názov fakulty'])[2]/preceding::select[1]</value>
      <webElementGuid>b3c14b54-1d26-434c-a1c0-87c3208783d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zadajte oficiálny názov fakulty vysokej školy, kde študujete.'])[2]/preceding::select[1]</value>
      <webElementGuid>44611344-3088-4b08-a347-56f77d7e53a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/select</value>
      <webElementGuid>6e2a7c45-3e5a-4edd-a6ab-9642069c9576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and @name = 'UI_V_ZP_in_DalsieStudiumSlovenska_NazovSkoly-control' and (text() = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline' or . = ' Výber Akadémia ozbrojených síl generála Milana Rastislava Štefánika Akadémia Policajného zboru Akadémia umení v Banskej Bystrici Bratislavská medzinárodná škola liberálnych štúdií Ekonomická univerzita v Bratislave Hudobná a umelecká akadémia Jána Albrechta - Banská Štiavnica, s. r. o., odborná vysoká škola Katolícka univerzita v Ružomberku Paneurópska vysoká škola Prešovská univerzita v Prešove Slovenská poľnohospodárska univerzita v Nitre Slovenská technická univerzita v Bratislave Slovenská zdravotnícka univerzita v Bratislave Technická univerzita v Košiciach Technická univerzita vo Zvolene Trenčianska univerzita Alexandra Dubčeka v Trenčíne Trnavská univerzita v Trnave Univerzita J. Selyeho Univerzita Komenského v Bratislave Univerzita Konštantína Filozofa v Nitre Univerzita Mateja Bela v Banskej Bystrici Univerzita Pavla Jozefa Šafárika v Košiciach Univerzita sv. Cyrila a Metoda v Trnave Univerzita veterinárskeho lekárstva a farmácie v Košiciach Vysoká škola bezpečnostného manažérstva v Košiciach Vysoká škola Danubius Vysoká škola DTI Vysoká škola ekonómie a manažmentu v Bratislave Vysoká škola manažmentu Vysoká škola medzinárodného podnikania ISM Slovakia v Prešove Vysoká škola múzických umení v Bratislave Vysoká škola neuvedená v CRŠ Vysoká škola výtvarných umení v Bratislave Vysoká škola zdravotníctva a sociálnej práce sv. Alžbety v Bratislave, n. o. Žilinská univerzita v Žiline')]</value>
      <webElementGuid>16b13c2a-af6a-4663-b3c8-e8ed7e1be01e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
