<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_1                                   _3dfe8f</name>
   <tag></tag>
   <elementGuidId>89ccdaeb-f212-4066-898e-e1d33c437c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_SkolaSlovenska_RocnikVS-control</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_RocnikVS-control']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9350284-281f-47ac-8772-b6fe6194a799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>govuk-select</value>
      <webElementGuid>ee4200c9-2b73-405f-bbe8-f3874927e4b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_RocnikVS-control</value>
      <webElementGuid>cf6c037c-e967-408c-b5ba-5274db1834e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UI_V_ZP_in_SkolaSlovenska_RocnikVS-control</value>
      <webElementGuid>94e24ea9-0167-4783-b4e0-1613d3abcc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                
                                                1
                                                2
                                                3
                                                4
                                                5
                                                6
                                            </value>
      <webElementGuid>8500d26f-4cf3-4eab-a566-ca5de1d9762f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_SkolaSlovenska_RocnikVS-control&quot;)</value>
      <webElementGuid>1fc60662-862d-4518-adc8-5eb92aed6717</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>522</value>
      <webElementGuid>fccfef69-7eb6-435e-8a76-cbe298a11b68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UI_V_ZP_in_SkolaSlovenska_RocnikVS-control']</value>
      <webElementGuid>73bac5d7-e017-46f8-a4fc-66afd034febb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_SkolaSlovenska_RocnikVS']/select</value>
      <webElementGuid>2fab4d09-7843-49b0-990b-cbcd326777a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ročník'])[1]/following::select[1]</value>
      <webElementGuid>b56bdbd7-4ce9-4a4f-94fb-09667190a485</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='III. stupeň'])[1]/following::select[1]</value>
      <webElementGuid>c31f16d3-9a10-4ad3-b035-883b6687d5aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dĺžka štúdia'])[1]/preceding::select[1]</value>
      <webElementGuid>e98b943f-57e6-4aa9-9797-be9440a39420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zobraziť detail'])[1]/preceding::select[1]</value>
      <webElementGuid>a670770b-d3e9-4f4a-8ac8-aa094cce8e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/select</value>
      <webElementGuid>8afbf1ed-434d-4c78-8b37-c7746fb87233</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UI_V_ZP_in_SkolaSlovenska_RocnikVS-control' and @name = 'UI_V_ZP_in_SkolaSlovenska_RocnikVS-control' and (text() = '
                                                
                                                1
                                                2
                                                3
                                                4
                                                5
                                                6
                                            ' or . = '
                                                
                                                1
                                                2
                                                3
                                                4
                                                5
                                                6
                                            ')]</value>
      <webElementGuid>042f6b56-8edc-498e-a0f8-61de037fb8d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
