<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2148</name>
   <tag></tag>
   <elementGuidId>d061ed40-25bf-4b39-bee9-400b63138ae6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>015fe3b3-3fe9-41ac-b363-2972f58abffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>d293641a-f33e-4efa-a966-94f6dde3199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2148</value>
      <webElementGuid>a2bb967e-8fa9-4478-93c3-620b012c09ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>7f733d02-306d-4a66-bf9b-a072ef9569da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      <webElementGuid>15fb97bc-a3f2-4fa0-b41c-34f2b3c7cecc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pri vypĺňaní sa vyskytli nasledovné problémy'])[1]/following::span[1]</value>
      <webElementGuid>5f484444-b1a8-4d58-911f-a735b70ae4b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje žiadateľa'])[2]/preceding::span[6]</value>
      <webElementGuid>4e0cbef2-4015-4723-90d5-d0d9e0a6339c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2148']/parent::*</value>
      <webElementGuid>dfc35a0d-535a-4528-bd98-77d19a05a24f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>89222d40-76e1-44fe-80ea-676753d6e4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ESRVS-2024-2148' or . = 'ESRVS-2024-2148')]</value>
      <webElementGuid>c588db68-f61c-4cd1-9884-98892b151521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
