<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_0101031238</name>
   <tag></tag>
   <elementGuidId>9e9486fe-7af1-4df0-92ff-2b87eac0fd79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_IdentifikacneUdaje_RodneCislo > label.govuk-label.bold > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_RodneCislo']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ae0bbfa4-ea33-48eb-8491-eae8384bbb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>ae0b1cf4-19fe-4603-bfe5-45973a48416e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>335</value>
      <webElementGuid>8c34bbe4-c0ed-4b97-863f-aa239f9582fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>0101031238</value>
      <webElementGuid>b0e8d7cd-c75b-4e5c-950d-6a7cc91db2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_IdentifikacneUdaje_RodneCislo&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>12fb60d5-421d-41d1-931f-b2483d4f8690</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_RodneCislo']/label/span</value>
      <webElementGuid>1cceb125-34aa-487a-bbff-55e11023ab68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chamraz'])[1]/following::span[3]</value>
      <webElementGuid>b558858a-ba54-4ffa-bf9a-93b3535fb3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[1]/preceding::span[6]</value>
      <webElementGuid>286cb903-ffc7-4f10-9282-2e826802e5d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='0101031238']/parent::*</value>
      <webElementGuid>854840d6-a782-4782-af78-c48da0eff92c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/span</value>
      <webElementGuid>0e4e4375-15e8-4763-af6d-4fa43c993bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '0101031238' or . = '0101031238')]</value>
      <webElementGuid>fbc53541-6ea4-4c30-bac9-edfd9cb183b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
