<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_03.01.2001</name>
   <tag></tag>
   <elementGuidId>d505e33e-b3f4-4f18-9770-6cc3fd4d0cd3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia > label.govuk-label.bold > span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ada5c5c1-cb71-4ffa-a281-a6222b8690b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>2e73cdf1-f3c2-447c-9649-adb68efb15cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>334</value>
      <webElementGuid>23b862e6-d103-4c37-a6e5-c2a1eb7ea345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>03.01.2001</value>
      <webElementGuid>e185725f-dfd8-4a64-8d87-372999ccbdf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>e873f567-b8a7-4257-a755-b3742032c9ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_IdentifikacneUdaje_DatumNarodenia']/label/span</value>
      <webElementGuid>9b603d34-6ed0-48f2-a395-8fb18b2dfec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Štátna príslušnosť'])[1]/preceding::span[3]</value>
      <webElementGuid>58b33c8a-9270-4b77-9cf2-14a3f3cb7cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slovenská republika'])[1]/preceding::span[5]</value>
      <webElementGuid>8f92c844-cce3-43a7-bbd1-c8598035bad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='03.01.2001']/parent::*</value>
      <webElementGuid>ccf4ef57-b9fb-4de0-8634-403e47668b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/label/span</value>
      <webElementGuid>cf3202b5-a3dc-4e13-b1bb-a0314a253ffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '03.01.2001' or . = '03.01.2001')]</value>
      <webElementGuid>89738f82-e21b-48c1-88dd-1676381f3298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
