<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_ESRVS-2024-2168</name>
   <tag></tag>
   <elementGuidId>6b67e845-a8bd-486a-b0c5-15867e749fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.value</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81d60484-9622-431f-af0f-f767fe4f5d0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>8dfdca83-9b75-4c38-bfab-942886909f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zn_id</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>08db56c3-ad89-4bc9-8407-0bb28a865e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ESRVS-2024-2168</value>
      <webElementGuid>9f014e71-3203-4893-a396-73a07b36c814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania&quot;)/label[@class=&quot;govuk-label bold&quot;]/span[@class=&quot;value&quot;]</value>
      <webElementGuid>133f7208-7f74-41a1-9d6d-8c412e154668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='UI_V_ZP_in_UdajeZiadosti_IdentifikatorPodania']/label/span</value>
      <webElementGuid>00d6f88e-fb5b-490c-b6a2-76ab20161649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pri vypĺňaní sa vyskytli nasledovné problémy'])[1]/following::span[1]</value>
      <webElementGuid>93579780-e35d-4833-b9ad-2c49e9f995ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Osobné údaje žiadateľa'])[2]/preceding::span[6]</value>
      <webElementGuid>7e4fed70-bc26-4381-ace3-e0243cd581ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ESRVS-2024-2168']/parent::*</value>
      <webElementGuid>e72351df-cd0f-434a-8f88-b963523e23b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/span</value>
      <webElementGuid>eed85811-1e65-4fd5-beb6-26338dfc8dc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ESRVS-2024-2168' or . = 'ESRVS-2024-2168')]</value>
      <webElementGuid>9d048550-534c-41ec-b267-2e17d6f7a8cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
